recipes/sueddeutsche_mobil.recipe
recipes/sueddeutschezeitung.recipe

now use datetime.utcnow() and add one hour for Germany

Daily Cover from https://zeitung.sueddeutsche.de/webapp

---

recipes/tyzden.recipe

Article urls were working, although they were wrong (different from the actual ones on the site).

tyzden recipe: Fixed article url

---

src/calibre/utils/formatter_functions.py

Problem pointed out at http://www.mobileread.com/forums/showthread.php?t=259229

Fix raw_field returning incorrectly rendered lists.

---

recipes/zeitde_sub.recipe

Hi there,
I noticed the zeit.de (subscription) recipe wasn't working anymore after some recent changes on the zeit.de website.
With these changes I got the recipe to work again.
Cheers and keep up the great work on Calibre,
Henning

Updated zeit.de (subscription) recipe after website change

---

recipes/discover_magazine_monthly.recipe
recipes/mit_technology_review.recipe

...ded description, tags, etc.

Updated mit_technology_review.recipe and new discover_magazine_monthly.recipe

---

src/calibre/gui2/store/stores/ebooks_com_plugin.py
src/calibre/gui2/store/stores/kobo_plugin.py

I've removed some of the affiliate links for stores that I'm not really updating any more. The Kobo one has become a pain to deal with because their programs expire (about monthly).

Remove some affiliate ids.

---

src/calibre/headless/fontconfig_database.cpp
src/calibre/headless/fontconfig_database.h

This just imports changes from Qt 5.5 and puts them behind appropriate
QT_VERSION #ifdefs.

Fix build with Qt 5.5.x

---

recipes/houston_chronicle.recipe

@kovidgoyal updated 'Houston Chronicle' recipe to accommodate some recent changes to their website.
Thanks,
Dale

updated houston chronicle recipe

---

recipes/chosun.recipe
recipes/hankyoreh.recipe
recipes/hankyoreh21.recipe
recipes/joongang.recipe
recipes/kyungyhang.recipe
recipes/maekyung.recipe
recipes/sisainlive.recipe

update outdated recipes for Korean news sites:
* kyungyhang.recipe
* hankyoreh.recipe
* hankyoreh21.recipe
add recipes for new Korean news sites
* chosun.recipe
* joongang.recipe
* maekyung.recipe
* sisainlive.recipe

update and add korean recipes

---

src/calibre/db/categories.py

1) a GST is not included in the tag browser unless at least one "real" user category is defined.
2) GSTs are supposed to be consolidated: identical (case insensitive) items are supposed to only appear once.
Some efficiency improvements

Bug fixes in get_categories

---

src/calibre/db/categories.py
src/calibre/gui2/tag_browser/model.py

4 commits.
It turned out that to get the counts right I had to do something like you did with average rating.

Tag browser stuff we discussed.

---

recipes/heise.recipe

Two minor adjustments
- add two more heise feeds with articles on software development and open source software
- download the print-Version of the artices. This version is easier to read on ebook viewers

Extend heise recipe

---

recipes/caravan_magazine.recipe

Caravan Magazine has changed layout and current recipe got outdated. Modified recipe to fetch news from latest site.

Updated Recipe for Caravan Magazine

---

recipes/readers_digest.recipe

Fixing recipe for RD, empty articles were turning up in existing recipe.
Sample Epub with existing recipe: https://www.dropbox.com/s/vm0c7nt8mxtctc7/readers_digest_before.epub?dl=0
Sample Epub with modified recipe: https://www.dropbox.com/s/91qu8xjmeypy59x/readers_digest_after.epub?dl=0

Update Readers Digest - no more empty articles

---

recipes/der_standard.recipe

- Fix cover URL (the old code didn't work anymore)
- Add some missing feeds

Fix and update der_standard recipe

---

src/calibre/gui2/store/stores/cdp_plugin.py
src/calibre/gui2/store/stores/ebookpoint_plugin.py
src/calibre/gui2/store/stores/virtualo_plugin.py

a bunch of fixes, koobe store fix is to follow soon.

update store plugins

---

recipes/houston_chronicle.recipe

Hi @kovidgoyal here are some changes to the Houston Chronicle recipe due to changes in their website.
Thanks,
Dale

Changes to Houston Chronicle Recipe

---

recipes/al_ahram.recipe

* Fix broken urls.
* Tidy recent website changes.

Update Al-Ahram (Arabic) recipe.

---

src/calibre/gui2/custom_column_widgets.py

Ensure that text in some custom column edit widgets is not highlighted

---

src/calibre/gui2/store/stores/woblink_plugin.py

Thanks for your previous commit on this plugin. I wouldn't manage to do it myself.

woblink plugin: fix price detection and list discounted ebooks

---

src/calibre/ebooks/metadata/sources/ozon.py

Hi!
I've updated the ozon.py file so that Russian language metadata can be downloaded again.
This is my first time I am contributing, so sorry for any mistakes...

Update OZON.ru metadata download file to reflect site changes

---

src/calibre/devices/kobo/bookmark.py
src/calibre/devices/kobo/driver.py

Changed all access to the Kobo device database from using sqlite3 to apsw. While doing this, refactored the accesses to one point plus did a little other refactoring.
Also added some fixes for cover images that I keep forgetting to do.

Change Kobo drivers to use apsw instead of sqlite

---

src/calibre/devices/kobo/driver.py

I forgot to test the ignore collections and delete empty collection option together. This fixes that.
Plus, have confirmed the firmware for the new Aura One in the 3.20.x series.

Fix ignore collection deleting and bump firmware version.

---

src/calibre/devices/kobo/driver.py

I don't know how I missed these before.

Add device names for the two new Kobo Devices

---

src/calibre/devices/kobo/driver.py

Several things:
- Support for OverDrive books.
- Support for about to be released firmware version 4.1.
- Fix bug when removing empty collections.
- Fix bug where previews could be seen as real books.

Kobo driver - OverDrive, 4.1 and bug fixes

---

recipes/nakedcapitalism.recipe

Recipe nakedcapitalism.recipe now works again.

Fixed bug #1529990.

---

recipes/sciencedaily.recipe

Recipe sciencedaily.recipe now works again.

Fixed bug #1458142

---

recipes/ba_herald.recipe
recipes/science_news.recipe

Fixed bug #1589276. science_news.recipe now works again.
Fixed bug #1556341. Buenos Aires Herald recipes ba_herald.recipe now works again.

Fixed bugs #1589276 and #1556341

---

recipes/hindu.recipe

the hindu has added some new tags on 
http://www.thehindu.com/todays-paper/
adding these changes will remove state specific news.
Please include these changes for improving performance.
Thanks

updating is_accepted_entry

---

src/calibre/devices/kobo/driver.py

Recent changes in the handling of collections in the KoboTouch driver broke how these were handled for the 1.9.x firmware. The change meant the reading status of all books in the device was reset. The problem was reported in http://www.mobileread.com/forums/showthread.php?t=278987.

Fix reading status problem with old Kobo firmware

---

src/calibre/devices/kobo/driver.py

If the KoboTouch driver or subclasses had settings saved from a very long time ago, they did not migrate to the new configuration properly. This fixes the migration if the last or the last two options are
missing.

Bug 1635909: Migration of very old KoboTouch settings broken

---

src/calibre/ebooks/metadata/sources/amazon.py

Support for searching book metadata via Amazon.cn (aka z.cn)

Metadata: Support Amazon.cn in the Amazon metadata plugin

---

recipes/korea_herald.recipe

Fixed KoreaHerald's recipe to show the content of the articles again.

Fixed KoreaHerald's recipe

---

recipes/mediapart.recipe

Hi,
I registered the bug and I am proposing to pull this commit as a way to fix it.
Best Regards,

Closes-Bug: #1657118

---

recipes/nytimes.recipe
recipes/nytimes_sub.recipe

removes the "what do you think" footer item

Remove hidden div in NY Times

---

recipes/sunday_times_magazine

Supplementary to The Times' daily and Sunday recipe.

Sunday Times UK & Sunday Times Style

---

recipes/apple_daily.recipe

- Fix Nonetype when download
- Clear nbsp; in title name
- Improve Download Size in Hong Kong
- Update Cover Photo

Appledaily Patch 20170121

---

recipes/oriental_daily.recipe

- Add cover image
- Reduce TOC by removing summary

Orientdaily patch 20170121

---

recipes/apple_daily.recipe

- Better translation on nav bar
- Better Cover Image
- New Download Logic
- Change Font Size

Appledaily patch 20170123

---

recipes/apple_daily.recipe

Fix flow-player parent div to display none

Fix Video Player Space

---

recipes/apple_daily.recipe

- Better Div cleanup
- Font Size Change in ExtraCSS
- Add missing pub type

Layout Improvement

---

recipes/am730.recipe

Almost rework whole recipe.
Fetch most popular 7 sections to avoid oversize (ie. < 30MB).
Try to reduce to below 20MB, but 2X MB artifact is my best effort.

Rewite non-working recipe

---

src/calibre/headless/fontconfig_database.cpp
src/calibre/headless/fontconfig_database.h
src/calibre/headless/headless_integration.cpp
src/calibre/headless/headless_integration.h

This finally fixes the Qt 5.8 by add conditional includes.

Add conditional includes for Qt 5.8.0

---

recipes/apple_daily.recipe

Clean meta, link tags in head tag

Clean more tags

---

recipes/nytimes.recipe

This removes the captions from the videos which are stripped out.

remove video captions

---

recipes/nytimes_sub.recipe

see https://github.com/kovidgoyal/calibre/pull/624

remove 'masthead-social'

---

resources/content_server/browse/browse.js
resources/viewer/hyphenate/Hyphenator.js
setup/installer/windows/XUnzip.cpp
src/calibre/devices/apple/driver.py
src/calibre/ebooks/hyphenate.py
src/calibre/ebooks/markdown/extensions/footnotes.py
src/calibre/ebooks/mobi/reader/mobi8.py
src/calibre/ebooks/oeb/base.py
src/calibre/ebooks/pdb/plucker/reader.py
src/calibre/ebooks/rtf2xml/field_strings.py
src/calibre/utils/formatter.py
src/calibre/utils/opensearch/__init__.py
src/calibre/utils/threadpool.py
src/duktape/duktape/duktape.c

Just minor fixes in comments.
Thanks for merging this PR.

Fix minor typos

---

recipes/strange_horizons.recipe

https://www.mobileread.com/forums/showthread.php?t=283337
Hi everyone,
I'm an avid reader of the Strange Horizons magazine of speculative fiction, and for several years I've used Anoved's Calibre recipe (see https://github.com/anoved/Calibre-Recipe-for-Strange-Horizons)
The magazine re-designed its site in late 2016 and the changes were extensive enough to break that recipe. I've written my own recipe that takes the changes into account.  This is my first Calibre recipe, so I welcome feedback and suggestions for improvement. I've "exercised" it on a bunch of back issues and it seems to be working well. I hope that you find it useful enough to merge into Calibre!

Added recipe for Strange Horizons

---

recipes/atlantic.recipe

removed some things that were uglifying it. added imgs in addition to lead. smaller captions to distinguish from body. right-aligned credits

improvements to atlantic recipe

---

recipes/kstar.recipe

old one doesn't work, auto cleanup for now

update to a new feed URL

---

recipes/tyzden.recipe

Update .týždeň recipe

---

src/calibre/gui2/actions/choose_library.py
src/calibre/gui2/dialogs/check_library.py
src/calibre/gui2/ui.py

Reload formatter functions in check library and don't refresh GUI during shutdown

---

src/calibre/devices/smart_device_app/driver.py

See the comment on the bug report.

Bug #1676522

---

recipes/private_eye.recipe

Not able to test as have not setup a dev env on my PC - but old URL is causing 404 errors.

URL has changed for current online issue

---

src/calibre/devices/kobo/driver.py

This adds:
- Support for new device Kobo Aura H2O Edition 2.
- Bump firmware supported to 4.4.x
- When there is an external SD card, check the presented drivers to make sure correct one is the main memory.

Update for firmware 4.4.x and new Kobo Aura H2O Edition 2

---

src/calibre/ebooks/metadata/search_internet.py

Fix bug #1690349 in bugtracker

Change Goodreads search author URL

---

src/calibre/headless/fontconfig_database.cpp
src/calibre/headless/fontconfig_database.h

Compilation tested under qt5 5.9.0 and 5.7.1.

Compatibility with qt5-5.9.0

---

recipes/tyzden.recipe

Add additional CSS, formatting.

Update tyzden recipe

---

src/calibre/gui2/search_box.py

Also move the actions to the top in case there are lots of saved searches.

Add 'get saved search text' to new right-click search button.

---

recipes/economist.recipe
recipes/economist_free.recipe

Due to recent UI changes. Tested.

Fix blog content inside Economist

---

recipes/private_eye.recipe

Thanks to Kovid for his help with this.

private_eye.recipe: Attempt to get Series details into Calibre library

---

recipes/private_eye.recipe

Apologies - I am not having a  good day today.

private_eye.recipe: Fix another typo

---

src/calibre/gui2/widgets.py

Display multiple shortcuts instead of only the first

---

recipes/politico.recipe

May need further cleaning but at least returns articles now.
Fixes https://bugs.launchpad.net/calibre/+bug/1674042

Fix for no articles returned

---

src/calibre/gui2/dialogs/search.py

I don't know if I need to do something for the translation to be added to transifex?

Insert _( ) to add missing translation

---

src/calibre/customize/builtins.py
src/calibre/gui2/actions/show_quickview.py
src/calibre/gui2/init.py

Quickview shortcut changes and a margin change

---

format_docs/rb.txt
manual/template_lang.rst
src/calibre/gui2/metadata/basic_widgets.py

The 'N' in ISBN already stands for number.

Fix redundant initialism

---

src/calibre/gui2/store/stores/amazon_au_plugin.py
src/calibre/gui2/store/stores/amazon_ca_plugin.py
src/calibre/gui2/store/stores/amazon_de_plugin.py
src/calibre/gui2/store/stores/amazon_es_plugin.py
src/calibre/gui2/store/stores/amazon_in_plugin.py
src/calibre/gui2/store/stores/amazon_it_plugin.py
src/calibre/gui2/store/stores/amazon_uk_plugin.py

Update price detection for non US kindle stores

Update price detection for Amazon get books plugins

---

src/calibre/gui2/dialogs/quickview.py

Also make the semantics of comparing None against a non-None value explicit.

Quickview: fix sort failure on None dates

---

src/calibre/linux.py

Changed name of the editor to the same format as the viewer.

E-book Editor name change.

---

recipes/dunyahalleri.recipe
recipes/dunyahalleri_haftaninozeti.recipe

added https://www.dunyahalleri.com/ and https://www.dunyahalleri.com/haftanin-ozeti/ recipes.

added two new recipes

---

src/calibre/gui2/dialogs/quickview.py

Allows viewing of books not in the current virtual library from QuickView. Enhancement #1717665.

Quickview: add a context menu with a "View" action to the book table.

---

src/calibre/devices/kobo/driver.py

New firmware with no changes needed except bump the firmware version.
Also, a small performance improvement for older devices and a debug log change for cover generation.

Bump supported firmware for Kobo device

---

src/calibre/gui2/jobs.py

When trying to stop a specific BG jobs (one of several converts running), I noticed that frequently the wrong job would be stopped.
I tracked it down to the rows changing due to other jobs finishing while the confirm dialog was up.
This change converts rows to jobs immediately instead of after the confirm dialog.

Kill selected BG jobs, not selected rows.

---

resources/default_tweaks.py
src/calibre/gui2/library/alternate_views.py
src/calibre/gui2/store/stores/libri_de_plugin.py

1) update the libri.de store (actually ebook.de) to use the new affiliate codes
2) add a tweak to modify the behavior of the ENTER key on the list and grid views.

Two separate changes:

---

recipes/economist.recipe
recipes/economist_free.recipe

Current method does not pull highest resolution available but instead a very low quality thumbnail

Fix cover resolution and add log line

---

recipes/nikkei_news.recipe

Current nikkei_news.recipe doesn't work.  Nikkei news changed their website recently and the fix is needed.

Fixed recipe to follow recent Nikkei site renewal.

---

src/calibre/ebooks/metadata/sources/overdrive.py
src/calibre/utils/text2int.py

Conforming these two files to the others would also help with the FreeBSD port maintenance.

Collapse double space.

---

src/calibre/gui2/dialogs/metadata_bulk.py

Also added Text into the ProgressBars.

QProgressBars fill parent layout in MyBlockingBusy

---

src/calibre/gui2/__init__.py
src/calibre/gui2/init.py

Let me know if I should do something differently

Make Virtual Library tabs lockable (no close button)

---

src/calibre/ebooks/metadata/sources/search_engines.py

Fix for https://bugs.launchpad.net/calibre/+bug/1750692

Fix for empty list error triggered by ASIN search

---

recipes/granta.recipe

Tested from issues 142 to 122, downloads them all correctly.  Will continue testing.

Fixes some edge cases in formatting

---

recipes/al_monitor.recipe

- prev version was getting confused by anchor tags

fix to al-monitor.recipe

---

src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/dialogs/tag_list_editor.ui

1) Make search show all matching items, not just the next one.
2) Add an undo button
3) fix problem with tabbing between columns

Enhancement #1743896:

---

recipes/bloomberg_columns.recipe
recipes/economist.recipe
recipes/economist_free.recipe
recipes/houston_chronicle.recipe

Hi Kovid @kovidgoyal 
Here are:
(1) Revisions to existing Houston Chronicle recipe (changes to their website)
(2) Added new recipe which scrapes Bloomberg for columnists' blog postings
(3) Revisions to existing economist recipe, added description metadata to articles via populate_article_metadata method override.
Thanks for your consideration, and all your work on Calibre!
Dale

Revisions to Houston Chronicle, Economist, new Bloomberg Columns Recipe

---

src/calibre/customize/builtins.py
src/calibre/gui2/store/stores/beam_ebooks_de_plugin.py

The broken links made the store not work at all.

Remove broken affiliate links in beam.de store

---

src/calibre/utils/icu.c
src/calibre/utils/icu_calibre_utils.h
src/calibre/utils/matcher.c

I'm not sure how this ever worked without PyTypeObject.tp_new, but
adding a generic constructor seems to work fine.

Build matcher in py3

---

recipes/ald.recipe

A recipe to pull the contents of the facing page of Arts and Letters Daily https://www.aldaily.com/
The recipe creates an index of all the links listed on the page, and then pulls in the content from each link.

Recipe for Arts and Letters Daily

---

recipes/le_peuple_breton.recipe

Recipe for the French newspaper Le Peuple Breton.

Le Peuple Breton recipe

---

src/calibre/devices/kobo/books.py
src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py

Added options to decide to update metadata, for the Subtitle and whether to update purchased books. The update will use a metadata plugboard if there is one.

Update metadata in Kobo database

---

src/calibre/devices/kobo/driver.py

And I meant to bump the driver version before.

Fix error when no author on Kobo device

---

recipes/al_jazeera.recipe

"Al Jazeera in English" is broken currently, it only retrieves titles but no content. So I updated the recipe so content is preserved.

Update "Al Jazeera in English"

---

src/calibre/devices/kobo/driver.py

Fix for https://bugs.launchpad.net/calibre/+bug/1807914.
With the last set of changes, if the metadata management was not set to automatic, books sent to the device would have the title showing as "Unknown" in the device list.
Also bumping supported firmware version to 4.12.12111 which has just been released.

Fix #1807914: Title showing as "Unknown" in device list for Kobo devices

---

src/tinycss/tokenizer.c

cf. https://github.com/kovidgoyal/calibre/pull/905#issuecomment-447883954

tokenizer: fix compile errors in merge of python3 port

---

setup/build_environment.py
src/calibre/constants.py
src/calibre/devices/mtp/unix/libmtp.c
src/calibre/devices/mtp/windows/device.cpp
src/calibre/ebooks/pdf/render/qt_hack.cpp
src/calibre/ebooks/pdf/render/qt_hack.h
src/calibre/utils/fonts/freetype.cpp
src/calibre/utils/podofo/doc.cpp
src/calibre/utils/podofo/outline.cpp

Plus some general cleanups for plugins I have not entirely touched yet, and another *.py fix during early startup.

py3: port headless/qt_hack plugins

---

recipes/mediterraneo.recipe

Recipe for elperidicomediterraneo.com based on the recipe for elperidicodearagon.com by desUBIKado

Add recipe for elperiodicomediterraneo.com

---

src/calibre/devices/mtp/unix/libmtp.c
src/calibre/devices/mtp/unix/upstream/update.py
src/calibre/devices/mtp/windows/content_enumeration.cpp
src/calibre/ebooks/compression/palmdoc.c
src/calibre/utils/fonts/winfonts.cpp
src/calibre/utils/lzx/compressor.c
src/calibre/utils/lzx/lzxmodule.c
src/calibre/utils/podofo/doc.cpp
src/calibre/utils/podofo/outline.cpp
src/calibre/utils/podofo/output.cpp
src/calibre/utils/podofo/podofo.cpp
src/lzma/lzma_binding.c

I've tried to fix up PyInt usage as well as format strings, so hopefully most of the remaining C work will just be fixing up the module declarations...

py3: misc porting work and port podofo/libmtp

---

recipes/nasa.recipe

All of the NASA RSS feeds have been deprecated, so I replaced them, and changed the some of the news topics entirely.

Fixed dead RSS feeds.

---

src/calibre/ebooks/metadata/search_internet.py
src/calibre/ebooks/metadata/sources/search_engines.py

On python3, there is explicit decoding already, so this would fail.

py3: check if quote_plus returns bytes or str

---

src/calibre/gui2/tweak_book/editor/text.py

See https://github.com/Sigil-Ebook/Sigil/commit/781a5e32879b26030164fbdd60c36886c1820a0b#commitcomment-33165094

Update comment to be accurate about the current state of calibre

---

src/calibre/ebooks/oeb/transforms/split.py
src/calibre/gui2/tools.py

I suppose my real question, though, is why anything needs to be written to the file at all?

py3: make conversion in the GUI work

---

src/calibre/ebooks/metadata/rb.py
src/calibre/ebooks/rb/__init__.py
src/calibre/ebooks/rb/reader.py
src/calibre/ebooks/rb/writer.py

tested by comparing an epub roundtripped through rb on python2/python3.

py3: rb format compat

---

src/calibre/utils/complete.py

Stop using python2 hack to duplicate python3 print behavior.

py3: make completion work

---

src/calibre/ebooks/docx/writer/container.py
src/calibre/gui2/preferences/server.py
src/calibre/srv/books.py
src/calibre/srv/render_book.py
src/calibre/srv/utils.py

The server successfully starts in the background on py3, this PR allows me to:
- read books
- use user authentication
And during the course of testing out the authenticated bits in the server, I also discovered a DOCX conversion issue, which is fixed as well.

py3: misc fixes to server and docx conversion

---

src/calibre/devices/kobo/driver.py

Just the version number changes.

Bump supported Kobo firmware version

---

src/calibre/devices/kobo/driver.py

The py3 changes highlighted an error in how the ContentType was being handled. This should have been fixed ages ago.
Also fixed an issue with the Language column and old firmware/database versions.

Correct handling of ContentType for newer Kobo firmware.

---

src/calibre/ebooks/metadata/sources/douban.py

Get subtitile from Douban API and merge it to title.
This feature is optional and is disabled by default.

Support subtitle in Douban metadata plugin

---

manual/faq.rst
src/calibre/gui2/dialogs/smartdevice.ui

Apologies for this second request ...

Corrected CC URLs.

---

src/calibre/ebooks/metadata/odt.py

https://bugs.launchpad.net/calibre/+bug/1844210

Fix typo keywords -> keyword on get_metadata for odt file

---

src/calibre/customize/builtins.py
src/calibre/ebooks/metadata/odt.py

Fix: https://bugs.launchpad.net/calibre/+bug/1841506

Implement setMetadata for odt files - 1841506

---

setup/install.py
src/calibre/linux.py

And other misc install fixups in the process.

fix loading of bash completion

---

format_docs/pdb/apnx.txt

Add URL for MobileRead APNX wiki page.

Update "Page Mapping Header" information.

---

recipes/telegraph_uk.recipe

Cleanup and login now required.

Updating Telegraph UK for paywall added 2 years ago

---

src/calibre/gui2/store/stores/litres_plugin.py

- Fixed some incompability issues with http response headers
- added unicode currency character for RUB

Corrected store plugin 'Litres'

---

Changelog.yaml

Was missed in the notes and some people have commented.

Add Kobo driver update.

---

COPYRIGHT

before this commit,
line 201 ~ 206 are same as line 195 ~ 200
line 343 ~ 348 are same as line 251 ~ 256
remove them

remove duplicate items from COPYRIGHT

---

src/calibre/devices/smart_device_app/driver.py

Additional string encoding fixes, as per #1109.

More encoding fixes

---

src/calibre/ebooks/metadata/sources/base.py
src/calibre/ebooks/metadata/sources/douban.py

- Fix Douban API (https://bugs.launchpad.net/calibre/+bug/1853091)
- Make metadata searching smarter when there are special CJK symbols in author names and book titles. (https://bugs.launchpad.net/calibre/+bug/1865507 and more)

Improve CJK support

---

src/calibre/ebooks/metadata/sources/douban.py

Fix the issues failed to get Douban metadata.
1. isbn is not correctly parsed, which made results merged to one item.
2. it failed to get data with isbn or douban id.

Fix the Douban metadata download plugin

---

src/calibre/gui2/dialogs/tag_categories.py
src/calibre/gui2/dialogs/tag_categories.ui

#1866405 (Filter available items) and #1866400 (Add languages to categories)

User Category Editor Enhancement requests

---

recipes/zeitde.recipe

* Implement forced cookie consent
* Skip paywalled articles
* Fix feed names and URLs, also use HTTPS
* Fix retrieving multipage articles
* Correctly display article and gallery images
* Remove cover (this is not provided anymore)

Update Zeit Online recipe

---

recipes/mit_technology_review.recipe

i think they changed their front end framework.  matching exact class names no longer works with the previous implementation of "keep_only_tags" and "remove_tags". i've identified relevant class names to keep and to remove and used regex. tested and ran ok.

fix recipe after website redesign

---

manual/faq.rst

This is to prevent others from having the issues I ran into in bug #1874370

Improve FAQ to emphasize issues with Android Devices

---

src/calibre/gui2/actions/choose_library.py

PR to the correct branch this time!

Fix for #1875758 - double space issue

---

src/calibre/devices/kobo/driver.py

Kobo will be updating the firmware soon. There are no changes except to update the supported firmware and database version numbers.

Update KoboTouch driver for upcoming firmware release

---

src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/edit_authors_dialog.ui
src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/dialogs/tag_list_editor.ui

In addition:
- Unified behavior of "Search"
- Added "Clear" buttons to the completion boxes
- Various text/message improvements

Enhancement #1879134: Add filters to all the Category editors

---

src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/dialogs/tag_list_editor.ui
src/calibre/gui2/dialogs/tag_list_editor_table_widget.py
src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/tag_browser/view.py

Enhancements #1880175 and #1880174 

---

src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/tag_browser/view.py

1) allow deletion of virtual hierarchical nodes
2) fix problem where couldn't drag twice without a mouse click intervening
3) separate the "Are you sure" dialogs for deletion so the user will the delete multiple question at least once.

Tag browser D & D changes:

---

src/calibre/devices/smart_device_app/driver.py

https://www.mobileread.com/forums/showthread.php?p=3993721

Send the client a message when calibre ejects the device.

---

src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/tag_browser/ui.py

1) Remove an incorrect comma when creating a string constant
2) Various improvements to edit authors, triggered by the performance penalties someone with 125,000 authors is seeing.

Two commits:

---

src/calibre/db/cache.py
src/calibre/gui2/preferences/create_custom_column.py

Kovid, I haven't marked this as "committed" in launchpad because I am not sure you will accept the change.

Enhancement #1886079: default value for custom columns

---

src/calibre/devices/kobo/driver.py

Removed a doubled parenthesis in the code added to support Kobo Nia

Fixed a typo in the Nia addition

---

src/calibre/gui2/dialogs/quickview.py
src/calibre/gui2/ui.py

Also a possible fix for startup problems on Linux. Let me know if this changes QVs behavior on start.

Fix for QV Refresh button not working.

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py

- added if .. then .. else ... fi expressions. The else part is optional. The 'if' has a value: a = if ... then fi works
- added infix string relational operators ==, !=, <, <=, >, >=
- added infix numeric relational operators ==#, !=#, <#, <=#, >#, >=#
- numerous performance improvements. In particular, the "field' function is now evaluated inline
NB: if, then, else, and fi are now reserved words. 
I will update the documentation later today. No need to wait

Improvements to program mode template language:

---

manual/template_lang.rst

I don't know if all the formatting is correct.

Update template documentation

---

recipes/Aftonbladet.recipe
recipes/SVT Nyheter.recipe

Please add these Swedish recipes.

Add new recipes

---

src/calibre/utils/formatter.py

- performance improvement: build and save an interpretable tree instead of parsing and executing at the same time
- improve syntax error detection
- performance improvement: automatically convert "test" to "if then else", avoiding executing the unused branch
- performance improvement: inline raw_field (field was already inlined)
I have tested these changes quite extensively so a new beta isn't necessary. Wouldn't hurt though. :)

Improvements to template parser:

---

src/calibre/utils/formatter.py

Fix incorrect inlined raw_field function.

---

src/calibre/devices/kobo/bookmark.py
src/calibre/devices/kobo/books.py

Found an error when in debug mode, so decided to remove dependencies on polygot while there.

Fix Error displaying Kobo book details in logs

---

src/calibre/devices/smart_device_app/driver.py

Python 3 conversion problem ...

Fix wireless device driver not using cached metadata

---

manual/template_lang.rst
src/calibre/gui2/tag_browser/view.py

I don't know if I got the formatting right. In particular I moved the function reference to the end, which I hope doesn't break anything.

Updates and cleanups of the template documentation.

---

recipes/livemint.recipe

Added News, Sports, Technology. Removed homepage which is not a valid feed

Added more RSS feeds from LiveMine rss feeds

---

src/calibre/gui2/tag_browser/view.py

Sorry about the multiple pull requests.

Fix allowing expand children when no child is expandable

---

resources/default_tweaks.py
src/calibre/gui2/custom_column_widgets.py

- Add tweaks to move the elision point and to disable elision.
- Fix some problems with the tooltips
- Make the gutter between the label and the widget the same as the standard fields
- Various other cleanups

Edit metadata custom column widgets.

---

src/calibre/gui2/dialogs/enum_values_edit.py
src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/preferences/create_custom_column.py
src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/tag_browser/view.py

Plus an enhancement: add an editor to change the list of permitted values.

Bug 1900921: various problems with enumerated types.

---

src/calibre/db/backend.py
src/calibre/db/cache.py
src/calibre/utils/formatter_functions.py

Provided a template function annotation_count() that returns the number of annotations for a book

Bug #1902313: Option to mark all books with annotations/bookmarks

---

recipes/netzpolitik.recipe

* Give the class a proper name.
* Update feed URL.
* Set publication type.
* Use embedded content and remove “remove_tags”.
* Remove duplicate title image.
* Add cover.

Update recipe “Netzpolitik”.

---

src/calibre/db/cli/cmd_add.py

As commented in #1285 and #1290
The automerge is very useful functionality to keep unicity in muntilingual librarys (avoid duplicates and update book with new versions )
(In my Library management I have to update with new versions of the book's content along the time, and keep the last one)
This is the CLI implementation of the functionality similar to the GUI, but it permits scripts automation and external integration with other tools like transmission daemon.

Add automerge option to add command CLI v3

---

recipes/atlantic.recipe
recipes/atlantic_com.recipe

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kovidgoyal/calibre/1296)

fixed bug : can't parse atlantic's article images

---

src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/library/delegates.py

Also:
- In bulk edit added tool buttons to set bools to True or False
- In single edit changed the buttons on bools from text to icons

Enhancement #1907140: add keyboard shortcut for undefined bools.

---

src/calibre/gui2/preferences/coloring.py

Enhancement #1907919: Rules editor: Convert/duplicate rule to advanced rule.
Enhancement #1907918: Add "Duplicate rule" button
Also fixed moving multiple selected items up and down

Multiple changes in rules editor

---

src/calibre/gui2/store/stores/nexto_plugin.py

The nexto's direct referral program is probably going to be closed.
Fortunately they also work with the BUY.BOX as well.

nexto plugin: migrate to buybox

---

manual/template_lang.rst
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

1) Added a 'for' statement
2) Added the ability for a developer to pass a dict of extra information to a template.

Template/formatter enhancements:

---

recipes/schwarzerpfeil.recipe

Please add this recipe for schwarzerpfeil.de.

Add recipe “SchwarzerPfeil”.

---

recipes/guardian.recipe

|      previous style      |     the new style          |
|----------------------|---------------------|
| ![old_version](https://user-images.githubusercontent.com/1683811/103264493-cd8f6f80-49e5-11eb-8110-5736b379b1d2.jpg)  | ![new_version](https://user-images.githubusercontent.com/1683811/103264499-d122f680-49e5-11eb-8835-651f8e97473e.jpg)|
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kovidgoyal/calibre/1320)

update guardian.recipe style

---

manual/conversion.rst
manual/plugin_examples/helloworld/__init__.py
manual/plugins.rst
manual/template_lang.rst
manual/viewer.rst
src/calibre/customize/__init__.py

I am new to this project. Just spent some time reading the docs. This PR is for some formatting and other minor documentation issues I found. Calibre is a wonderful tool!

Typo in manual

---

src/calibre/db/search.py
src/calibre/gui2/dialogs/saved_search_editor.py
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/search_query_parser.py

Enhancement #1912074: make the saved search editor multiline.
Enhancement #1912081: make saved search lookup case insensitive.
Improvement: show the template function type in the template editor's function list.

Three independent commits

---

manual/template_lang.rst
src/calibre/utils/formatter_functions.py

1) new function field_exists()
2) make add() and multiply() accept a variable number of arguments

Two template function enhancements:

---

recipes/zeitde.recipe

Address had changed and was slowing recipe down

Update masthead_url to correct image location

---

manual/template_lang.rst
src/calibre/gui2/preferences/search.py
src/calibre/utils/formatter_functions.py

1) Add the alias "list_contains" to the "in_list" function so that naming is more consistent.
2) Add composite categories to valid grouped searches.

Two changes:

---

src/calibre/gui2/store/stores/chitanka_plugin.py

Update html parser to be consistent with the current version of the site.

Fix chitanka store

---

src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py
src/calibre/utils/img.py

Plus bump the supported firmware version for the recent release.

Add option for cover letterbox color to KoboTouch driver

---

src/calibre/gui2/store/stores/biblio_plugin.py

Update html parser to be consistent with the current version of the site.

Fix biblio store

---

manual/template_lang.rst
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

1) add the possibility to specify a separator in a for statement.
2) add the template function list_remove_duplicates()

Template language changes:

---

manual/template_lang.rst
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

1) added the infix compare operator 'in'. Usage: pattern in expression.
2) added the template function list_count_matching()
3) documentation for the above.

Template language improvements:

---

setup/liberation.py

https://github.com/liberationfonts/liberation-fonts/compare/2.1.1...2.1.3

Bump bundled liberation fonts from 2.1.1 to 2.1.3

---

manual/template_lang.rst
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

1) Changes to the template program language discussed in https://www.mobileread.com/forums/showthread.php?t=337668
2) General improvement of the template documentation, including documentation of the above changes. I looked at the changes using a markdown interpreter, but there might be problems exposed by generation of the web page.
3) Focus the program text box when opening the template dialog
4) Small changes to non-built-in template functions to improve performance

Various improvements:

---

manual/template_lang.rst

The commit on 27 Feb isn't good. The manual page should be regenerated from this commit.

Rewrite much of the template language manual document.

---

recipes/the_conversation.recipe

Signed-off-by: Alistair Francis <alistair@alistair23.me>

recipes: Increase the conversation articles date

---

manual/template_lang.rst
src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/utils/formatter.py

1) Fix a regression in the template language introduced sometime in V5
2) Bug #1918030

Two independent commits:

---

manual/templates/layout.html

This is to address a recommendation from LGTM (https://lgtm.com/projects/g/kovidgoyal/calibre/?mode=tree&severity=recommendation&ruleFocus=4860080).

Added Explicit Semicolon

---

src/calibre/gui2/ui.py

I made this change to address a suggestion from LGTM (https://lgtm.com/projects/g/kovidgoyal/calibre?mode=tree&severity=recommendation&ruleFocus=1818040193).

I removed the duplicate `import` of `collections`.

---

src/calibre/gui2/dialogs/quickview.py

This problem is caused by Quickview filling in the entite table whenever the book changes. Unfortunately this is necessary because the table is sorted.
I improved performance using two methods:
- Compute the data for a column only when it is needed. This means that in general only the data in the sorted column is computed before displaying the table.
- Delay a bit before redisplaying the table. This lets the main gui remain responsive at the cost of a small delay in seeing the quickview data.

Bug #1920733: Slight lag when viewing composite column in quickview.

---

manual/template_lang.rst
src/calibre/utils/formatter_functions.py

Many other cleanup, spelling, and grammar changes.

Bug #1921348: English text in code block. 

---

manual/template_lang.rst

Many other cleanup, spelling, and grammar changes.

Bug #1921348: Fix Jellby's second example.

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_dialog.ui
src/calibre/utils/formatter.py

Formatter:
- Clean up line number processing to make them more accurate
- Provide more detail in breakpoint labels
- Ensure all error strings are translatable
- Clean up error strings to distinguish between translated and untranslated parts
Tester:
- Remove context menu, replacing it with 2 small buttons for load and store

Template formatter and tester changes:

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_dialog.ui
src/calibre/gui2/dialogs/template_dialog_code_widget.py

1) Add button to set breakpoints on every line
2) Make using Tab and Shift-Tab do indenting
PS: I thought I created this pull request several days ago but there isn't one. Yet another senior moment.

Template tester changes:

---

src/calibre/gui2/dialogs/template_dialog.ui
src/calibre/gui2/library/alternate_views.py
src/calibre/gui2/preferences/coloring.py
src/calibre/gui2/widgets2.py

1) Allow advanced emblem rules to return multiple icon names 
2) Separator class and template tester changes

Two independent commits

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_dialog_code_widget.py

Also fixed a few other small problems such as the placeholder text being hidden by the line highlight.

Enhancement #1922526: Template editor: Toggle word-wrap.

---

src/calibre/constants.py
src/calibre/customize/__init__.py
src/calibre/customize/ui.py
src/calibre/gui2/dialogs/plugin_updater.py
src/calibre/gui2/preferences/plugins.py
src/calibre/gui2/ui.py

As discussed in: https://www.mobileread.com/forums/showthread.php?t=333893
Open points:

RFC: load plugins from system-wide directory

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_dialog.ui
src/calibre/gui2/preferences/template_functions.py
src/calibre/gui2/preferences/template_functions.ui

- Better help text in the stored template editor
- Support hiding the help text in stored templates
- Clean up the grid layouts

Template dialog improvements:

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py

Added "return expr" to the template language.
Improvements to parser error messages.

Template processing improvements

---

recipes/the_saturday_paper.recipe

Signed-off-by: Alistair Francis <alistair@alistair23.me>

recipes: Initial commit of The Saturday Paper

---

recipes/the_saturday_paper.recipe

Signed-off-by: Alistair Francis <alistair@alistair23.me>

recipes: Improvements to The Saturday Paper

---

recipes/crikey.recipe

This is an initial commit to support Crikey. It's currently able to fetch the list of articles with a description but the login doesn't seem to work as the articles are empty. Any ideas to login to their php login would be greatly appreciated.
Signed-off-by: Alistair Francis <alistair@alistair23.me>

recipes: Initial commit of Crikey

---

manual/template_lang.rst
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

- Replace the newline() function with the character('name') function
- Document the new function
- In the template editor/debugger, display special characters like newline as escaped characters

More template stuff:

---

README.md

Added periods at the end of few sentences for consistency.

Added periods in sentences

---

src/calibre/devices/kobo/driver.py

Kobo have told me what the version numbers will be. The last part of the version is a build number and will change, but is not tested by the driver.

Update firmware version for Kobo Elipsa

---

recipes/hindu.recipe

Gets today's front page image displayed in Hindu ePaper website.
Also add some styles to the lead image and caption.

Recipe: add cover_url to The Hindu

---

src/calibre/utils/lzx/lzxd.c
src/calibre/utils/lzx/mspack.h
src/calibre/utils/podofo/doc.cpp
src/calibre/utils/smartypants.py
src/odf/opendocument.py
src/tinycss/color3.py
src/tinycss/parsing.py

fix typos grammar on ```calibre```

minor fixing

---

recipes/foreignaffairs.recipe

Image before PR:
Image after PR:

Better cover image for Foreign Affairs recipe

---

resources/calibre-portable.bat

One capitalization was missed in the last merge.

Small typo fix

---

recipes/le_monde.recipe
recipes/le_monde_sub.recipe

The login form on the website of Le Monde was changed and the recipe needs to be updated accordingly.
This commit also includes a minor change to remove the small pictures of authors that have recently started to show up below the headline of some articles.

Update Le Monde

---

src/calibre/ebooks/metadata/book/render.py
src/calibre/gui2/book_details.py
src/pyj/book_list/book_details.pyj

Added the copy options as well as search and remove to composites, bools, numbers, etc

Bug #1950033: Book Details: Missing copy options on composite columns

---

src/calibre/utils/formatter.py

1) make strcat() inlined
2) fix incorrect argument checks for inlining test() and first_non_empty()

Two template language changes:

---

src/calibre/gui2/dialogs/metadata_bulk.ui
src/calibre/gui2/dialogs/template_dialog.py

Moved the mode field, which as a side benefit makes it more "important".

Bug #1951673: Clicking on field Search Mode resets previous field

---

src/calibre/gui2/preferences/create_custom_column.py

-- Added the ability to auto-generate a lookup name
-- Now checks the calibre "can't configure" before adding a new column
-- Fixed parameter names

More improvements to the new CreateNewCustomColumn class.

---

src/calibre/gui2/preferences/create_custom_column.py

My apologies for the multiple commits. I have been working with @davidfor and we cycled a few times. I hope this is the last, barring bugs.
This version supports safely creating more than one column and uses docstring-format comments.

Yet another version of CreateNewCustomColumn.

---

src/calibre/gui2/preferences/create_custom_column.py

- Improved documentation
- Check column headings for duplicates
- Method to return the current column headings as a dict
- Improved exception handling

More CreateNewCustomColumn stuff.

---

src/calibre/gui2/preferences/columns.py

While testing the enum change I found several problems related to adding and editing columns when the table was sorted differently.
I also prevented moving rows when the table is sorted by anything but row number ascending. This isn't the nicest fix but making it work with new columns while the sort is descending is harder than I want to deal with tonight.

Another enum cleanup.

---

src/calibre/library/coloring.py

1) Performance improvements for icon etc rules.
2) Make comparisons of undefined floats and ints consistent with template language conditionals, where undefined is assumed to be zero.

Two improvements to rules templates

---

src/calibre/ebooks/conversion/utils.py

Fix line unwrap for Polish. Add Cyrillic alphabet.

Unwrap line after more characters

---

src/calibre/ebooks/metadata/sources/search_engines.py

Fix Google Search Engine Results

---

recipes/mmc_rtv.recipe

The old recipe wasn't generating any content at all due to significant changes to the website. I fixed the recipe and added a few feeds that were missing.

Fixed news recipe for www.rtvslo.si

---

recipes/mainichi_en.recipe

The present version of the Mainichi (en) version was not working. I
remade it from scratch, taking into account the current layout of the 
Mainichi website

Recipes - Redo Mainichi (English version) from scratch

---

recipes/rt.recipe

This adds RT in Russian as a news source.

Add RT news source

---

recipes/courrierinternational.recipe

Add categories to the recipe (duplicates ignored because some article appear both in all and in categories, also "Réveil" contains articles from all categories)

Update courrierinternational recipe

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py

1) Support for defining nested template functions.
2) An operator, &, to do string concatenation like strcat().
3) A fair amount of clean up. mostly reording methods to make them easier to find.

Improvements to the template language:

---

src/calibre/devices/kobo/books.py
src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py

Updates to support firmware 4.32. This adds some books stats such as word and page count and expected reading time. Plus did some code cleanup.

Updates for new Kobo firmware with book stats

---

recipes/new_yorker.recipe

* Has correct section names now
* Sections are in right order now
* Mail article is included now

Update New Yorker recipe

---

recipes/ieeespectrum.recipe

- Fixed the description.
- Removed cover URL that no longer works.

Update IEEE Spectrum recipe

---

recipes/caravan_magazine_hindi.recipe

This PR adds a new recipe for Caravan Magazine in Hindi, by modifying the English recipe that is built in.

Add recipe for Caravan Magazine in Hindi language

---

recipes/omgubuntu.recipe

Removed the cover URL which is a 404 now.

Update OMG! Ubuntu! recipe

---

src/calibre/devices/kobo/books.py
src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py

A template can be used as well as the existing columns to create collections on Kobo ereaders. The template can return a list of collection names but uses ":@:" as the separator between the names.

Add support for templates for collections

---

recipes/donga.recipe

This PR adds recipe for Donga ([https://donga.com/](https://donga.com/))

Create recipe for Donga

---

recipes/asahi_shimbun_en.recipe

Recipe made from scratch
I flattened the Asia&World, Culture and Opinion subsections because I did not find anything about making subsections in the News Feed documentation.

Recipes - The Asahi Shimbun (English)

---

src/calibre/devices/kobo/driver.py

Whoops. I was sure I fixed and tested that.

Error for handling new templates for collections

---

src/calibre/gui2/library/models.py
src/calibre/gui2/library/views.py
src/calibre/gui2/preferences/create_custom_column.py

Radio buttons that control showing icon, text, or both

Enhancement #1977681: additional display options for yes/no columns

---

src/calibre/gui2/preferences/create_custom_column.py

I am a bit concerned about why shift-tab works differently from tab. It clearly does, but perhaps because of a bug in Qt? In any event, without the code one gets stuck in the group box.

Make the accelerator on &Show work.

---

recipes/smh.recipe

Current recipe is outdated and returns empty articles.

Fix for Sydney Morning Herald (SMH) recipe

---

recipes/nrc.nl.recipe
recipes/volksrant.recipe

The old recipes are based on (outdated) RSS feeds; the new ones download the actual daily editions of each newspaper.

Updated NRC, Volkskrant to download the daily editions

---

src/calibre/gui2/preferences/template_functions.py
src/calibre/gui2/preferences/template_functions.ui

- Support filtering to show only user defined functions or all functions
- Show the function type in the function name combo box
- Minor improvement in when the delete button is enabled or not

Improvements to the user defined template function preference editor:

---

src/calibre/gui2/custom_column_widgets.py

See https://www.mobileread.com/forums/showthread.php?t=347919

Yet another enum change problem. Sigh.

---

bypy/windows/portable-installer.cpp

This is a repeat commit, removing the white space processing my editor did.
I thought I had made a PR but there is no record of it. Apologies if this is a duplicate.

Fix an amusing typo. :)

---

recipes/german_gov.recipe
recipes/zaobao.recipe
resources/calibre-portable.bat
resources/templates/fb2.xsl
src/calibre/devices/eb600/driver.py
src/calibre/gui2/icon_theme.py
src/calibre/gui2/preferences/metadata_sources.py

Fix source typos

---

src/calibre/gui2/dialogs/search.py

1) Add a button to copy the current search into the boxes to make editing easier.
2) Add a toolbutton to open the template editor. This is more discoverable than a right-click.

Improvements to Advanced search: Template searches:

---

resources/default_tweaks.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/tag_browser/model.py

I made no attempt to migrate the effect of the tweaks.

Enhancement 1987235: Easier way to rearrange Tag Browser

---

src/calibre/gui2/tag_browser/model.py
src/calibre/srv/metadata.py

1) do a proper migration of the tweak
2) Fix the server's usage of the migrated value
3) Fix an exception in the server related to hierarchical user categories

Three things related to tag_browser_category_order:

---

src/calibre/devices/kobo/driver.py

Added in new USB id and other required changes for Kobo Clara 2e

Updates to the Kobo driver to add support for the Kobo Clara 2e.

---

recipes/scmp.recipe

Fixes https://www.mobileread.com/forums/showthread.php?t=349346

Fix SCMP recipe

---

manual/template_lang.rst
src/calibre/gui2/dialogs/template_dialog.py

1) If the user presses ESC, ask "are you sure" if the template has changed.
2) Fix syntax highlighting of comments in python.
3) Improve the python template example in the template docs, better using the new_api.

Three changes to template processing:

---

src/calibre/db/tests/reading.py
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py

1. More improvements in syntax highlighting for comments and strings
2. Permit using a custom python template context class. Add a test for it.

Two improvements:

---

manual/template_lang.rst
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py

A introspection system that allow to use, in Python template mode, the fonctions currently loaded in the TemplateFormatter.
The functions can be retrieve by they name and they name plus a '_' at the end in case of conflict with Python language keywords.

Python template introspection

---

src/calibre/utils/formatter.py

It was possible for the recursion to occur if mi.deepcopy() was called after (un)safe_format(). Change the state save/restore mechanism to ensure all instance variables are always restored to base settings.
Apologies for not noticing this before the previous commit.

Improved Metadata deepcopy recursion fix.

---

recipes/calcalist.recipe
recipes/en_globes_co_il.recipe
recipes/globes_co_il.recipe
recipes/walla.recipe
recipes/ynet.recipe

fix: selectors for existing recipes
also added globes english feed
relates to https://bugs.launchpad.net/calibre/+bug/1999964

bug #1999964 : update broken recipes

---

src/calibre/db/search.py
src/calibre/gui2/layout.py
src/calibre/gui2/search_box.py

This fix is really an enhancement, adding better error presentation to the GUI search box.

Bug #2002195: Search breaks if non-number used in numeric-sorted column.

---

recipes/nature.recipe

Just a simple fix to get the higher-res cover image.

Fix Nature cover resolution

---

manual/url_scheme.rst
src/calibre/gui2/ui.py

I will update the documentation in a day or so.

Enhancement #2003712: URL scheme: 'virtual_library' for show-book.

---

recipes/dr_dk.recipe

The old one was completely broken (DR's website is completely different), so I had to rewrite it from scratch.

Fix DR Nyheder recipe

---

recipes/el_pais.recipe

Removed unrelated text
Added author of the article
Downloads all pictures
Improves downloaded pictures quality
Downloads cover if available
Updated some feeds
Adds some style to author's name, photographer's name, picture text 
Added publication_type

El País recipe: Improved style and design, updated some feeds on 

---

src/calibre/ebooks/metadata/book/render.py
src/calibre/gui2/book_details.py

Fix links for series and custom series columns being confounded

---

src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/metadata/basic_widgets.py
src/calibre/gui2/metadata/single.py

Authors, Series, Tags, Publisher, custom columns

Add Category edit buttons to columns that have category editors.

---

src/calibre/gui2/preferences/search.py

Add a check for periods in grouped search names

---

recipes/scientific_american.recipe

Site got updated recently and link in the original recipe no longer exists.

Fix Scientific American recipe

---

src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/dialogs/tag_list_editor.ui

Note: I rolled back commits d5dbb3c63a1fe05f85a31cf1e4cd021ec76e750a and 89391da7b7074b42aad7c440e97ac76cfd18175a.

Bug #2017316: Error when renaming tag in Tags Manager.

---

src/calibre/gui2/dialogs/book_info.py
src/calibre/gui2/dialogs/quickview.py

Enhancement #2017318: Open book details window from Quickview.

---

src/calibre/db/backend.py
src/calibre/db/backup.py
src/calibre/db/cache.py
src/calibre/db/copy_to_library.py
src/calibre/db/tests/writing.py
src/calibre/gui2/actions/choose_library.py
src/calibre/gui2/actions/view.py

This PR is for the base API for the extra files cache, including clearing when files are added and with the directory is views using the calibre UI.
My assumption: you will review this code. I will build the formatter functions once the review is finished.

API for the extra_files cache

---

resources/default_tweaks.py
src/calibre/gui2/library/models.py
src/calibre/gui2/library/views.py
src/calibre/gui2/metadata/basic_widgets.py
src/calibre/library/field_metadata.py

Also add not setting a delegate for non-editable standard columns

Remove the column heading tweak.

---

src/calibre/gui2/book_details.py
src/calibre/gui2/library/delegates.py
src/calibre/gui2/markdown_editor.py
src/calibre/gui2/markdown_syntax_highlighter.py

1) Make F2 on a markdown column in the booklist use the new markdown dialog.
2) Fix some problems in the markdown syntax highlighter that threw exceptions.
Sorry, somehow your encoded URL commit got into mine. I didn't change anything so you can ignore it.

Two related changes

---

recipes/irish_independent.recipe
recipes/irish_times_free.recipe

Created a new recipe for Irish Times with google feeds, login isn't actually required to fetch content. Didn't want to edit the login-based recipe.

New feed based recipe for Irish Times, and update for Independent

---

recipes/harpers_full.recipe

Re: https://www.mobileread.com/forums/showthread.php?t=354014
This PR updates the recipe to not require subscription/login while still extracting the full article. This is done by not sending cookies.
I've compared the recipe output with my library's electronic copy and it appears to be complete.

Update Harper's Magazine Print recipe

---

recipes/bloomberg-business-week.recipe
recipes/bloomberg.recipe
recipes/google_news.recipe

Increased delay significantly, even the 2 second delay doesn't seem to work anymore. Let it take half an hour to fetch.

Bloomberg recipes update

---

recipes/private_eye.recipe

Rewrite (by Sophist-UK) to fit latest web pages, correctly identify pages to include and improve formatting.
Please run the existing recipe and this revised one and compare the contents between them. Also compare new output to web site to see how much closer it looks.

Improve Private_Eye.Recipe

---

src/calibre/gui2/ebook_download.py

https://bugs.launchpad.net/calibre/+bug/2025355
I have tested this locally and things seem working.
But I'm completely new to calibre's internals so I'm not sure if this is the right way to do it.

Fix for #2025355 Metadata wrong for books from gui.download_ebook

---

recipes/al_masry_alyoum_arabic.recipe

News site is specifically egyptian.

al_masry_alyoum_arabic.recipe: Mark as being Egyptian Arabic

---

recipes/kyivpost_ar.recipe

kyivpost_ar.recipe: Mark as Arabic edition of a Ukrainian newspaper

---

src/calibre/gui2/init.py

https://www.mobileread.com/forums/showthread.php?p=4339960#post4339960

Use the new layout icon on the status bar as suggested here:

---

recipes/bloomberg-business-week.recipe
recipes/bloomberg.recipe

increased delay further, facing s2s error. fixed somethings.

bloomberg again

---

src/calibre/gui2/tag_browser/view.py

See https://www.mobileread.com/forums/showthread.php?p=4341802#post4341802

Fix for flashing in the tag browser.

---

src/calibre/gui2/store/stores/ebookpoint_plugin.py
src/calibre/gui2/store/stores/legimi_plugin.py
src/calibre/gui2/store/stores/nexto_plugin.py
src/calibre/gui2/store/stores/virtualo_plugin.py

Some updates for website changes.
More to come...

Updates for polish stores

---

src/calibre/db/backend.py
src/calibre/db/cache.py
src/calibre/db/notes/connect.py

Add a function that return a dict {field:[item_id, ], } of all notes defined in the DB.

Add retrieve all item_id for each field assosiated to a notes

---

recipes/st_louis_post_dispatch.recipe

feed links and site formatting have changed for st louis post-dispatch. this PR updates sources and filters to reflect those changes.

fix st louis post-dispatch recipe

---

src/calibre/db/categories.py

See https://www.mobileread.com/forums/showthread.php?t=356598

Fix sort order of similarly-named hierarchical categories.

---

recipes/el_diplo.recipe

This updates includes the following changes:
- Download the cover
- Add the author names below the article titles
- Group the articles into sections mimicking the publication's organisation as close as possible
- Cleanup anchors to avoid broken links

Update recipe for El Diplo

---

src/calibre/gui2/search_restriction_mixin.py

This behavior has been there for years.

Bug 2041357] Editing non-active VL changes sort of book list.

---

recipes/cumhuriyet.recipe

1-) This commit completely rewrites the `cumhuriyet.recipe` to
bring it up to date since the previous change was made
years ago.
2-) Add additional feeds
3-) Remove the part having no useful information such as
'google-news'
4-) Add the most common user-agent
5-) Time format is changed as well.

Refactor: Rewrite cumhuriyet.recipe

---

recipes/outlook_india.recipe
recipes/project_syndicate.recipe

also fix missing images in outlook due to ssl error

Project Syndicate update

---

src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/tag_list_editor.py

- Eliminate the NotesItem class for performance
- Ensure the edited icon is displayed as appropriate
- Add context menus
- Lots of refactoring
- Bug fixes for tag_list... where changes were lost when the list was filtered
Opening authors and tags for the "big library" now takes at most a few seconds.
I will continue to test it. I wouldn't be surprised if I broke something.

Changes to category editors:

---

src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/tag_list_editor.py

Various little improvement on the NotesUtilities.
The big part is to remove the duplicate `edit_note()`.

improve NotesUtilities

---

recipes/bloomberg-business-week.recipe
recipes/bloomberg.recipe

looks like bloomberg isn't working. changed the user agent to latest firefox one.

Bloomberg update

---

recipes/epoch_times.recipe
recipes/mit_technology_review.recipe
recipes/phillosophy_now.recipe

MIT Tech Review update

---

src/calibre/gui2/tag_browser/ui.py

Use the defined user custom icons

Use user custom icons

---

recipes/theeconomictimes_india_print_edition.recipe
recipes/toiprint.recipe
recipes/wsj.recipe
recipes/wsj_free.recipe

TOI Print update

---

recipes/natgeo.recipe
recipes/natgeohis.recipe
recipes/natgeomag.recipe
recipes/theeconomictimes_india_print_edition.recipe
recipes/toiprint.recipe

Nat Geo update

---

src/calibre/gui2/tweak_book/check.py

Fixes [2043200](https://bugs.launchpad.net/calibre/+bug/2043200).

Include line numbers when copying ebook editor error messages to clipboard

---

manual/template_lang.rst
src/calibre/utils/formatter_functions.py

I put this in notes to avoid any hassle with collisions with the other new template functions.

Enhancement 2043330: Template function to fetch links

---

src/calibre/gui2/tag_browser/ui.py

Small optimization of commit b43a329

---

README.md

Split into 3 columns and added a badge header
Preview:

README: cosmetic enhancements to repology badge

---

recipes/wsj.recipe
recipes/wsj_free.recipe

added delay. it seems to fix the "Too Many Requests" error for some articles.

WSJ update

---

src/calibre/gui2/__init__.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/tag_browser/view.py

Clicking the "buttons" works because of how mouse tracking works. The user must move the mouse over/into the current item line before clicking a button, which causes that line to be painted. When the line is painted the horizontal positions of the buttons on the line are recorded. If/when a click happens, the click X point is checked to see if it is in the ranges defined by the horizontal positions.

The tag browser notes/links icon stuff.

---

src/calibre/ebooks/metadata/sources/amazon.py

1.- Amazon changed the way manage book images.
I fixed this on lines 880-888 (original file) - 906-920 (new file)
2.- Amazon also changed the <div> name for the book comments
I fixed this on lines 724 and 729 (original file) - 741 and 748 (new file)
Keeped both names to be compatible with cached pages 
All others changes in the new file are log for debug info, that can be deleted

Update amazon.py to adapt to changes in Amazon web pages 

---

src/calibre/gui2/library/delegates.py

described in https://www.mobileread.com/forums/showthread.php?p=4390503#post4390503

Fix for edit widget placement problem

---

src/calibre/gui2/library/alternate_views.py

- Correct some comments so they reflect what the code is now doing.
- Make return None explicit in a few places.
- Wrap render_cover() in an if to check that cover_tuple is valid. This doesn't change behavior because the thrown exception would do the same thing, but being explicit is nice.

Minor changes:

---

recipes/martinfowler.recipe

Creates a news recipe for the Martin Folwer blog at https://martinfowler.com/.

feat: creates a recipe for the Martin Fowler Blog

---

recipes/ugeskriftet.recipe

Added recipe for ugeskriftet for læger - medical journal in danish

Add ugeskriftet recipe

---

src/calibre/customize/builtins.py
src/calibre/gui2/__init__.py
src/calibre/gui2/actions/layout_actions.py

I added this to the existing Layout Actions. In addition I added the ability to toggle panels on/off in addition to turning them on and off.
I am unable to test the docstrings.

Enhancement 2052897: save and restore GUI panel layouts.

---

src/calibre/gui2/actions/all_actions.py

Add the icons to the actions in last section.

Add icons to actions in last section

---

src/calibre/ebooks/metadata/sources/amazon.py
src/calibre/gui2/store/stores/amazon_mx_plugin.py

Adds option to search books in Amazon Mexico store.
At first I've tried to add it as a plugin but didn't find any good plugin examples for adding new store. So I've figured to contribute on core instead since we already have examples there.

Adds Amazon Mexico store

---

src/calibre/db/cache.py
src/calibre/ebooks/metadata/book/base.py
src/calibre/gui2/dialogs/book_info.py
src/calibre/gui2/library/views.py
src/calibre/library/save_to_disk.py

1) Fix save-to-disk templates containing template expressions ...
2) Another try at debouncing book details. This includes on-demand evaluation of composite columns in Metadata instances returned by db.get_metadata()

The commits (again)

---

src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/library/alternate_views.py
src/calibre/gui2/metadata/single.py

It really isn't clear if the image can be non-None but not have a bounding box, or if getbbox can throw any exceptions. Just to be safe, check.

Small change to commit d84b1e2 to be a little safer.

---

recipes/the_week_magazine_free.recipe
recipes/the_week_uk.recipe

Update The Week

---

src/calibre/gui2/search_box.py
src/calibre/gui2/search_restriction_mixin.py

Also fixed a similar problem in the virtual library additional restrictions menu.

Bug 2063171: still another ampersand escape bug

---

recipes/wsj.recipe

cant fetch because of present headers.

add cover wsj

---

src/pyj/read_book/view.pyj

Fixes the same issues as #2290 with minimum changes

fix height calculation on mobile browsers

---

src/calibre/gui2/metadata/diff.py

implemented a "Previous" button on the multiple compare dialog that appears during the bulk match if the user clicks on "Review downloaded metadata"
the implementation includes a previous list that each call to next_item function - append the current accepted/rejected book to the list,
if the user presses the previous button - the previous book will be displayed, current book edit is canceled, and any edit that was done to the previous book will be discarded as well

implemented previous button on the multiple compare dialog

---

src/calibre/gui2/metadata/diff.py

Clear a translation key with a f-string format introduced in the commit befb04ee

Clear translation key

---

recipes/radio_canada.recipe

Added all the rss feeds available.
Fixed the classes so it pulls the article. Previously, the content was empty. Added comment for easier customisation and understanding  why I chose specific classes to be included or ignored.

Fix for Radio-Canada recipe + update

---

setup/commands.py
setup/install.py
setup/iso_codes.py
setup/resources.py
setup/translations.py

Previous discussions: https://bugs.launchpad.net/calibre/+bug/2054284
I add some code to allow setting more local resource files from cli when bootstraping.

Allow setting more local resource files from cli

---

src/calibre/linux.py

Add `Keywords` to desktop entry file.
It helps desktop application search.

Add keywords to desktop application entry file

---

recipes/ancient_egypt.recipe
recipes/bloomberg-business-week.recipe
recipes/lex_fridman_podcast.recipe
recipes/military_history.recipe
recipes/minerva_magazine.recipe
recipes/world_archeology.recipe

Update for specific_options

---

recipes/deutsche_welle_bs.recipe
recipes/deutsche_welle_de.recipe
recipes/deutsche_welle_en.recipe
recipes/deutsche_welle_es.recipe
recipes/deutsche_welle_hr.recipe
recipes/deutsche_welle_pt.recipe
recipes/deutsche_welle_ru.recipe
recipes/deutsche_welle_sr.recipe

Update DW group of recipes

---

recipes/atlantic.recipe
recipes/caravan_magazine.recipe
recipes/foreignaffairs.recipe
recipes/frontline.recipe
recipes/harpers.recipe
recipes/hindufeeds.recipe
recipes/hindustan_times_print.recipe

caravan, foreign affairs, frontline

more options

---

src/calibre/ebooks/metadata/epub.py

Sorry for the drive-by PR. Let me know if I should file a bug first, and/or if I should figure out how to add unit tests.
Some manga epubs sold online have two issues:
- They contain multiple OPF entries in META-INF/container.xml.  But only one exists.  Solution: check if the entry actually exists, and ignore it otherwise.
- The cover is not actually tagged as a cover.  But since this is a manga, the "first spine entry" is already a JPG/PNG.  Instead of trying to render it (which for me gives a black rectangle), try to parse it as an image and return it directly if it is actually an image.

Fix import of manga epubs

---

recipes/mediapart.recipe

The Google News feed was not functioning properly, so I removed it and implemented a custom feed parser. This allows us to keep the different sections of the journal, even though only one RSS feed is available.

Fix Mediapart recipe

---

src/calibre/devices/kobo/driver.py

Add MimeType 'application/epub+zip' so that these books are also being listed.

Books from the Tolino Cloud are EPUBs (not KEPUBs).

---

recipes/economist_search.recipe
recipes/science_advances.recipe
recipes/science_journal.recipe
recipes/sciimmunol.recipe
recipes/scirobotics.recipe
recipes/scisignaling.recipe
recipes/scistm.recipe

reduced image size, option to change img-res
also added economist search recipe.

Update Science Journals

---

recipes/le_gorafi.recipe

Fix Le Gorafi Recipe

---

recipes/cumhuriyet.recipe

delete the author name

---

recipes/hurriyet.recipe

update the recipe tags

---

recipes/star_gazetesi.recipe

1-) correct the name of the publisher
2-) capitilaze some letters according to the Turkish grammar.
modified:   star_gazetesi.recipe

fix metadata

---

recipes/star_gazetesi.recipe

1-) update the rss for all feeds
2-) make h1 and h2 tag smaller a little bit
3-) change the color of h1 to red
4-) change the oldest_article to 1 because this is a daily newspaper, and max_article_per_feed to 10 instead of 100.
modified:   star_gazetesi.recipe

update the recipe

---

recipes/cumhuriyet.recipe

remove empty feeds

---

recipes/computer_weekly.recipe

new file:   computer_weekly.recipe

add computer weekly recipe

---

recipes/computer_weekly.recipe

modified:   computer_weekly.recipe

add language code

---

manual/template_lang.rst
src/calibre/utils/formatter_functions.py

1) Fix plain_text not working in template get_note() function
2) Add documentation for get_note()

Two changes for the get_note() template function

---

recipes/courrierinternational.recipe

- **Fix Tags:** Remove undesired elements.
- **Add Extra CSS:** 
- Add margin below article summary
- Set different style for captions, credit and other info smaller and italic
- Set article keyword (strapline) as a bigger element.
- **Update RSS Feeds**
- **Ignore Duplicate Articles**

Fix Courrier International

---

recipes/afr.recipe
recipes/bar_and_bench.recipe
recipes/deccan_herald.recipe
recipes/firstpost.recipe
recipes/hamilton_spectator.recipe
recipes/hindutamil.recipe
recipes/ifzm.recipe
recipes/inc42.recipe
recipes/irish_times_free.recipe
recipes/live_law.recipe
recipes/mainichi_en.recipe
recipes/moneycontrol.recipe
recipes/newsminute.recipe
recipes/scroll.recipe
recipes/singtaohk.recipe
recipes/usatoday.recipe

google feeds dont work anymore.

---

recipes/nikkeiasia.recipe

google webcache no longer works.

Update Nikkei Asia Magazine

---

recipes/indian_express.recipe
recipes/the_wire.recipe

Update The Wire

---

manual/template_lang.rst
src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

1) New template operator 'field_inlist'. It operates directly on data in a multi-valued field instead of converting the field to a string then splitting it.
2) Add a count column to manage authors.
3) Change the name of format_date_field() to field_format_date()

Some independent commits

---

src/calibre/ebooks/pdf/reflow.py

Try to improve the indentation and right margin processing.
The divide-by-zero fix has been changed here by other amendments.  It should not occur.

More margin/indentation processing

---

manual/template_lang.rst
src/calibre/utils/formatter_functions.py

- Return the list of item values with notes if the empty string is passed as the value
- Add documentation to the template language page.

Improvements to the has_notes() template function:

---

src/calibre/ebooks/pdf/reflow.py

Add more margin processing, and tidy joining lines into paragraphs.

Adjust joining lines into paragraphs

---

.gitattributes

Enable syntax highlight for *.pyj files on github for improved readability on code reviews

enable syntax highlight for *.pyj on github

---

src/calibre/web/fetch/simple.py

by adding png for compression the size of some magazines will be decreased up to 10 times. worked for me well, so I wanted to provide the setting for all.

add png in  simple.py for copress_news_images

---

src/calibre/devices/kobo/kobotouch_config.py

updated several instances of 'bookshelves' to 'collections,' mainly in tooltips

String changes to kobotouch_config.py

---

manual/template_lang.rst

I took out the inline documentation, changing it to reference the generated documentation. I also added a lot of :ref:.
I'm unable to verify that the changes work or that I didn't break something. I'll check it once another version of the generated web doc is available.
NB: I will be away from a development environment from 24/11 to 4/12.

Changes to the template documentation.

---

src/calibre/gui2/dialogs/ff_doc_editor.py
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_general_info.py
src/calibre/utils/ffml_processor.py

* Update the documentation for the new tags
* Add a "Documentation" button to the FFML editor dialog
* Fix problems with escaping text in code blocks.

Changes related to FFML documentation:

---

src/calibre/gui2/preferences/look_feel.ui

no longer needs system tray icon on Windows, so removed that bit.

string changes in look_feel.ui

---

src/calibre/gui2/dialogs/template_dialog.py

1. fix text not in english when checkbox is True
2. fix text not switched to english/translated when checkbox change

2 fix for template_dialog.py

---

recipes/economist.recipe
recipes/economist_free.recipe
recipes/economist_search.recipe
recipes/economist_world_ahead.recipe
recipes/substack.recipe

uodate econ

---

src/calibre/gui2/preferences/template_functions.py
src/calibre/gui2/preferences/template_functions.ui

- Add some tooltips
- Improve button alignment.

Stored templates preferences:

---

recipes/lwn_weekly.recipe

This adds support to download older LWN articles by the article identifier

add support for downloading older LWN articles

---

ruff-strict-pep8.toml
setup/check.py

Light version of #2605, with only the `check.py` and `ruff-strict-pep8.toml` change.

setup.py check: Add the option --strict 

---

src/calibre/srv/metadata.py

The name is in the dict entry 'value_icon', which might not exist, be a file name, or be None. This is a path rooted at the 'tb_icons' directory. Icons that come from templates are in the 'template_icons' subdirectory, in which case a slash is used as the path separator.

Pass the tag browser icon names to the content server client.

---

manual/gui.rst
src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/view.py
src/calibre/srv/metadata.py

- Documentation
- bug fixes in icon template evaluation
- Better enabling/disabling of menu lines in the tag browser context menu

Stuff for value icons:

---

manual/gui.rst

- Describe the icon selection decision hierarchy
- Add the new menu action added ny @un_pogaz

Update documentation for the tag browser section

---

manual/gui.rst
src/calibre/db/cache.py
src/calibre/db/fields.py
src/calibre/db/search.py
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

- Fix composites that use database methods not working in the content server.
- Fix template searches using the database API not working in the content server.
- Update the manual.

Three things related to templates in the content server.

---

src/calibre/gui2/preferences/look_feel.py

Fix a regresion: displayed metadata are not show in book details

fix regresion: displayed metadata are not show in book details

---

src/calibre/gui2/preferences/look_feel_tabs/cover_grid.ui

Fix string accidentaly changed during the previous PR

Fix string changed during the previous PR

---

src/calibre/gui2/preferences/look_feel_tabs/__init__.py

Fix a error in LazyEditRulesBase widget.

Fix LazyEditRulesBase widget

---

src/calibre/ebooks/metadata/book/base.py
src/calibre/ebooks/metadata/book/render.py
src/calibre/gui2/book_details.py
src/calibre/gui2/preferences/create_custom_column.py
src/calibre/gui2/preferences/look_feel_tabs/__init__.py

The first two commits are straightforward. The third, render.py, was much more difficult. I'll be away until Tuesday so I'm pushing it today so you can see what I'm doing.
I tested all the column types but I'm not confident there isn't some edge case I missed.

Commits to implement using a template for a web URL in custom columns

---

src/calibre/ebooks/metadata/book/render.py

Fix a UnboundLocalError for the custom colums links.
Also clear a never reached code, a DRY, and a regresion fix.

Fix a UnboundLocalError for the custom colums links

---

recipes/the_wire.recipe

This fixes the issue where the `oldest_article `value was not working as expected

Update the_wire recipe

---

recipes/the_wire.recipe

Sorry, i missed removing a hard-coded value in my previous PR (https://github.com/kovidgoyal/calibre/pull/2673/)  i was trying out for `oldest_article` before it got merged

Remove hard-coding from previous PR

---

src/calibre/gui2/toc/main.py

Allows moving and indenting in the TOC editor when multiple items are selected.

feat: multi-select support in toc editor

---

recipes/private_eye.recipe

Addresses https://bugs.launchpad.net/calibre/+bug/2105419

Fix private_eye.recipe after web site changes

---

pyproject.toml

Slightly improve `pyproject.toml` by adding basic fields and usefulls urls.

Slightly improve 'pyproject.toml'

---

recipes/wash_post.recipe
recipes/wash_post_print.recipe

wapo update

---

src/calibre/ebooks/metadata/sources/amazon.py

Just found a piece of redundant code during tracing the source code.

remove redundant code.

---

src/calibre/customize/__init__.py
src/calibre/devices/kobo/kobotouch_config.py
src/calibre/gui2/device_drivers/tabbed_device_config.py
src/calibre/utils/formatter.py

There are three commits for this change. I did this to (I hope) better explain what the changes were for.

Add validation of column keys for collections to the kobo driver.

---

recipes/business_standard.recipe
recipes/business_standard_print.recipe

old code seems to be creating two br tags

update business standard

---

recipes/ancient_egypt.recipe
recipes/economist_news.recipe
recipes/military_history.recipe
recipes/minerva_magazine.recipe
recipes/world_archeology.recipe

Added support for selecting image resolution via a new 'res' option and updated image URLs to use the specified resolution. Enhanced tag filtering logic to include additional classes for keeping and removing tags, improving content extraction accuracy.

Update Ancient Egypt Magazine

---

src/calibre/utils/ffml_processor.py
src/calibre/utils/formatter_functions.py

1) formatter_functions.py: change a quoted string to an italic string so it is the same as in other functions.
2) ffml_processor.py: use look ahead in the parser to detect parse nodes with text that can be inlined.

Two independent FFML-related changes:

---

recipes/tijd.recipe

A lot of broken links caused the python script to fail.

Fix broken links in tijd.recipe

---

recipes/todoist.recipe

Hi there,
This recipe provides integration with Todoist (https://www.todoist.com), a task management application. Todoist is organized into projects containing tasks and offers numerous plugins and integrations to simplify adding tasks to a project.
The recipe calls Todoist's API, retrieves all the tasks in a specified `project_id` that contain URLs, builds an ebook with a chapter for each unique domain, and optionally calls the API again to close the retrieved tasks.
The parameters are specified in lines 27–30:
- `URL_KEYWORD_EXCEPTIONS` – list of keywords; if the URL of an article contains any of these, the recipe will ignore the article.
- `ARCHIVE_DOWNLOADED` – True/False
- `TODOIST_PROJECT_ID` – your Todoist project ID; you can find it in the URL of your Todoist project, e.g., …

Todoist recipe

---

recipes/el_diplo.recipe

I've updated the tag for extracting the cover URL since it wasn't working properly. I've also added some preprocessing to remove annoying text that otherwise appears at the beginning of each article ("Post type: POST"). Please let me know if there are additional steps I should follow in order for this to be merged.

Update El Diplo recipe

---

recipes/1843.recipe
recipes/economist_news.recipe
recipes/economist_search.recipe
recipes/economist_world_ahead.recipe

implement changes across all econ recipes.

Update econ recipes
