kovidgoyal/calibre

src/calibre/gui2/preferences/coloring.py

1) fix for bug 1436690. Apostrophes in file names create syntax errors. The fix is to remove the apostrophes.
2) fix icon not appearing  in the combo box until the rule editor is closed and reopened.

Two fixes:

---

src/calibre/gui2/actions/choose_library.py

Just like you can't change libraries while there are BG jobs running, I don't think you should be able to change libraries while there are outstanding updates waiting on the gui.proceed_question dialog.
This wasn't an issue when proceed_question was modal, but now it can happen.

Block lib change when proceed_question has questions.

---

src/calibre/devices/smart_device_app/driver.py

Two fixes: 
1) The CC modified date is UTC not local time.
2) Thread switching can trigger 10ms accept timeout. Make it longer.

Two fixes: modified date and thread timeout

---

src/calibre/gui2/preferences/misc.ui

Until a user pointed it out today, I never realized the worker_max_time option affected PI jobs because it said 'conversion' on it.

Change working of BG job options in Pref/Misc--also affects plugin jobs.

---

src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/library/delegates.py

The first commit improves the category editor available from the tag browser. The second commit makes Shift F2 (or whatever the edit key is) on a tags-like column in the book list open the tags editor instead of the line editor. The third removes the edit tag button in single edit metadata because it alters the order of the tags.

Three changes for editing tags

---

src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/dialogs/tag_editor.py
src/calibre/gui2/library/delegates.py

You were right -- drag/drop was trivial. However, I didn't find a straightforward way to know that the order had been changed, so I changed the code to regenerate the applied tags list whenever necessary.
I thought about changing it to work on "authors" but that turned out to be more work than I wanted to do. :)

Handle custom is_names columns in the tag editor.

---

src/calibre/gui2/dialogs/saved_search_editor.py
src/calibre/gui2/dialogs/tag_editor.py

#1473140 Improvement/Feature Request: Tag Editor Change Initial focus is given to the filter available tags box instead of the add tag box.
#1467147 Rename search creates a new one instead

Fixes for #1473140  and #1467147

---

recipes/xkcd.recipe

xkcd recipe crashes on current version of xkcd website. Update the xkcd recipe so articles are only pulled from A tags in the middleContainer div.

Fix xkcd recipe.

---

recipes/harpers_full.recipe

Updated login endpoint for “Harper’s Magazine - articles from printed
edition”. The login stopped working a few months ago, resulting in all
articles being abbreviated with “Subscribe to Harpers…”.
New endpoint was found by inspecting harpers.org and tested
with `ebook-convert`.

Update login for “Harper’s Magazine"

---

src/calibre/gui2/library/delegates.py

When editing cells on the book list:
- Make CTRL-F2 clear pub date to undefined instead of 1/1/2000
- Make CTRL-F2 clear an integer/float to undefined instead of zero
- Remove SHIFT-F2 to avoid conflict with SHIFT-TAB when editing
- Make CTRL-SHIFT-F2 set dates to now()

Bug #1507945

---

src/calibre/gui2/ui.py

Loading the tray icon from the theme allows the user to customize the
desktop in greater extend. If the icon is not present in the icon set,
then the bundled one is loaded, so the previous behavior is preserved.
The themed icon name is consistent with the application name - calibre.

Load system tray icon from the current theme

---

src/calibre/library/comments.py

FanFicFare calls calibre.library.comments.sanitize_comments_html() before setting comments.
sanitize_comments_html() now does some processing before calling sanitize_html().
But if given HTML such as "<div></div>", sanitize_comments_html() reduces it down to an empty string before calling sanitize_html(), which then throws an exception when it calls serializer.render().

sanitize_html shouldn't error when handed an empty string.

---

src/calibre/ebooks/metadata/book/render.py

Commit f7e8e5e8f066b07672a9be34ae283089c16406bd added click-able link handle for all `metadata['datatype'] == 'text'` entries in book details.  This was in answer to bug [#1521004 Non-clickables in the book details](https://bugs.launchpad.net/calibre/+bug/1521004).
The bug report is specifically talking about custom columns, so I assume the fact it also changed handling for Title was incidental.
Being able to click on the title to do a search for identical titles is situationally useful.  Being able to right-click and *delete the title* is IMO a bad idea.
This change explicitly exempts title from getting a link in book detail.

Don't apply clickable link to title in book details.

---

src/calibre/gui2/ui.py

Calibre already has an 'are you sure' check before quitting for running background jobs, and checks before switching libraries for both running background jobs and outstanding proceed_questions.  This change brings parity.  And I've accidentally quit before accepting updates a couple times.

Add 'are your sure' check to quit when proceed_question is waiting.

---

recipes/brand_eins.recipe

This commits fixes the brand_eins recipe to reflect changed sharing links and ads in the website source code. Previously, the recipe also purged the author line from each article (was this done on purpose?), I fixed this as well.

Update brand_eins.recipe: remove sharing links, ads

---

src/calibre/gui2/tweak_book/__init__.py
src/calibre/gui2/tweak_book/boss.py
src/calibre/gui2/tweak_book/file_list.py
src/calibre/gui2/tweak_book/preferences.py

Adds an option to show full file pathnames in Editor File Browser.  That makes working with books containing directories and especially duplicate file names in different directories easier.  EpubMerge creates such books.
I saved this as two separate commits so you could clearly see the fix in 1460b7a for duplicate file name (in different dirs) appearing as file.xhtml/file.xhtml instead of dir/file.xhtml.

Add option to shown full file pathnames in Editor File Browser, fix for for file.xhtml/file.xhtml

---

src/calibre/gui2/dialogs/message_box.py
src/calibre/gui2/dialogs/saved_search_editor.py
src/calibre/gui2/dialogs/saved_search_editor.ui
src/calibre/gui2/proceed.py
src/calibre/gui2/search_box.py

Save/reuse ViewLog size from proceed_question when called with log_viewer_unique_name.
Plugins use proceed_question() to safely update the database.  I'd like to have the ViewLog dialog remember its size when called from my plugin.
This change allows that, but only if proceed_question() is called with parameter log_viewer_unique_name to preserve existing behavior everywhere else.
(I considered using the existing log_viewer_title instead of a new parameter, but thought that was too likely to not be unique.)

Save/reuse ViewLog size plus Saved Search Changes

---

recipes/economist.recipe
recipes/economist_free.recipe

This removes noisy "related articles" widget content from The Economist recipe:
(example of the widget takes from [this article](http://www.economist.com/news/united-states/21698712-republicans-are-tatters-over-donald-trump-learning-love-don))

Remove "related" widget content from Economist recipe

---

src/calibre/utils/imageops/imageops.cpp

While updating the FreeBSD port I noticed a failure on i386 (32bit) only on FreeBSD 9.3.
I'd like this modifications which fix the problem to be included in calibre.
This is caused by the fact that FreeBSD 9.3 is still using gcc 4.2.1 as it's system compiler, and generated these error messages:
g++ -c -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/local/include/python2.7 -I/usr/local/include/python2.7 -I../../../src/calibre/utils/imageops -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I. -I/usr/local/include -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-g++ -o imageops.o ../../../src/calibre/utils/imageops/imageops.cpp …

Fix build on FreeBSD 9.3 i386.

---

src/calibre/devices/eb600/driver.py

According to the manual, the tolino shine and vision names are spelled in lowercase.

Correct spelling of tolino shine and vision devices

---

src/calibre/debug.py
src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py
src/calibre/gui2/device_drivers/tabbed_device_config.py

This implements a new tabbed configuration dialog for drivers. The dialog uses the common configuration for the first tab and allows device specific tabs to be added as needed. Group boxes are used to group options together and make dependencies easier. For backwards compatibility, it displays the "extra configuration" options as a separate tab.
The tabbed configuration has been implemented for the KoboTouch driver. This has a lot of options with dependencies between the options. 
There is some more details about the changes in http://www.mobileread.com/forums/showthread.php?t=273129. This includes screenshots and tests by other users.

New tabbed configuration for the KoboTouch driver

---

src/calibre/gui2/device.py

As suggested, this saves and restores the dialog size for the device configuration dialogs. This was already being done when the configuration was opened from the plugin list, so the same preference name is used.

Save/restore dialog size changes for the device driver configuration.

---

src/calibre/devices/kobo/driver.py

Missed adding some properties for the KOBO driver that is used by the
older devices.
Also, I forgot to update the version number.

Fix #1596801 - Unable to connect to Kobo

---

src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py

If the KoboTouch configuration was last saved using a very old version of calibre, the migration to the new style will fail. This will increases the likelyhood that the migration will work.
Plus realised I wasn't using the cached settings, so the migration kept happening.

Fix #1598017 - KoboTouch configuration migration not working for older settings

---

setup/build.py

While updating the FreeBSD ports I had a problem with the new extensions code.
Old code had a simple check 'if islinux or isosx:' around the libusb definition. New code as is includes whatever is not windows or osx in linux, so that extension is now included and fails to build.
I slightly modified the parsing code to differentiate BSDs from Linux.

Make new extensions parsing code differentiate BSD from Linux.

---

src/calibre/ebooks/metadata/book/render.py
src/calibre/gui2/preferences/create_custom_column.py
src/calibre/srv/metadata.py
src/pyj/book_list/book_details.pyj

- collapse the two booleans controlling the heading into one string
- allow short-text to appear on the right in book details
- make the new server and book details do (more-or-less) the same thing with headings
- use different CSS for short-text and long-text.
I changed the name of the show_heading property to heading_position to ensure the properties had no odd values, making it easier to test.
I did not change the old content server. It displays all comments as html.

Comments custom columns:

---

src/calibre/gui2/tweak_book/editor/text.py

Append final user replace regex-function output to marked text (see #1609111)
Introduces a new flag "append_final_output_to_marked".
Depends also on existing flag "call_after_last_match".
Following two lines at the end of a user replace function will cause,
that the return value of the last additional call (after all replacements
are completed) will be appended to the marked text:
replace.call_after_last_match = True
replace.append_final_output_to_marked = True
TODO: Documentation update is required.
Part: Editing books
Chapter: Function Mode for Search & Replace in the Editor
Section: Having your function called an extra time after the last match is found

Append final replace function output to marked text (#1609111)

---

manual/function_mode.rst
src/calibre/gui2/tweak_book/search.py

This is the second part of the proposal filed originally as bug #1609111.
The result dialog, shown after replacements, slows down book editing in some cases.
For example, when the user repeatedly applies his own regex-function to relatively small pre-marked text fragments.
User should have a choice to suppress the result dialog.
This implementation allows for the following switch inside the user replace function:
replace.suppress_result_dialog = True
This way it nicely fits to the first part (see #1609111) and it allows individual configuration from case to case.
Actually, it's not dependent on the other two switches ('call_after_last_match' and 'append_final_output_to_marked'),
so it can be used in combination with any of them or even individually.
This implementation also should not …

Configurable suppression of replace result dialog (see 1610658)

---

src/calibre/devices/kobo/books.py
src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py

Kobo are releasing the Aura One and Aura Edition 2. This adds the device ids but does not update the firmware version. The firmware for these devices have not been released. It will probably be compatible, but, there might be changes. 
This also includes an extra configuration option to ignore some collections. With this, the named collections will not be touched by the drivers collection management.

Add device Aura One and support for ignoring some collecitons.

---

src/calibre/devices/kobo/driver.py

I think the title says it all.

Kobo decided the new firmware should be 4.0.

---

src/calibre/ebooks/metadata/pdf.py

Check explicitly for `info is None`, since an empty dict also evaluates to false. Otherwise it raises an exception when there is no metadata, and prevents from generating the cover.
This has started to happen recently with some arxiv PDF's, like this one: https://arxiv.org/pdf/1605.02391v2

metadata: Do not raise an exception if a PDF file has empty metadata

---

src/calibre/ebooks/metadata/sources/ozon.py

They've changed search results markup, so searching for metadata in Calibre is broken.

Update parsing code according to the new ozon.ru page markup

---

recipes/instapaper.recipe

(Also discussed in [this forum thread](http://www.mobileread.com/forums/showthread.php?t=279130)...)
I recently experienced errors using the Instapaper recipe with some longer articles, and traced it down to this error:
```
SplitError: Could not find reasonable point at which to split: feed_0/article_9/index_u33.html Sub-tree size: 606 KB
http://www.w3.org/1999/xhtml}h3 /*/*[2]/*[4]/*/*[2]/*[6]/*[19]
```
I looked at the processed HTML of one of the articles, and found a huge section of hidden HTML in a `<div id='speedRead'>` element which replicated the text of the article with each word wrapped in individual `<span>` elements. I tried adding the "speedRead" div to the `remove_tags` attribute of the recipe, and that solved the problem.
Thanks!

Instapaper recipe:  remove hidden "speedRead" div to fix SplitError

---

recipes/lwn_weekly.recipe

More resilient behavior if article title contains non-html-encoded
characters. E.g. "<Programming>" string in the title start is recognized
by beatiful soup as html tag, but it is not, making the title a
NoneType, and raising an exception on Article creation.
This is actually a bug in the news page itself, but it anyways breaks
the recipe; hence, adding here a fixed string if for any reason the
article title end up with a NoneType.

lwn_weekly: Prevents fail if article title is not defined.

---

src/calibre/ebooks/conversion/plumber.py

From
http://www.mobileread.com/forums/showthread.php?p=3421577#post3421577, when an epub is converted to kepub, if the ToC had an entry pointing to the cover, it is removed. This does not happen when doing an epub-to-epub conversion. Found that the Plumber was treating epubs specially for this, so added kepub as another exception.

Kepubs should follow epub rules for covers and ToC

---

recipes/wired.recipe

This small patch pulls the latest magazine cover image for Wired from `wired.com`, to improve the display of the resulting book (for example in a Kindle library).

Retrieve the latest Wired cover's thumbnail to use as the cover

---

src/calibre/devices/kobo/driver.py

Kobo are about to release a new firmware version. No changes are needed except to bump the version numbers.

Update supported Kobo firmware to 4.2

---

src/calibre/devices/kobo/driver.py

Fix a couple of typos related to getting the sizes of the covers for Kobo devices. It meant that everything got the size for the Glo. The other was the dimensions of the full size cover for the Aura ONE were swapped.

Fix cover file size determination in KoboTouch driver

---

setup/installer/windows/en-us.xml
src/calibre/ebooks/oeb/polish/parsing.py
src/calibre/ebooks/oeb/polish/utils.py
src/calibre/gui2/actions/device.py
src/calibre/gui2/preferences/server.py
src/calibre/gui2/tweak_book/diff/_patiencediff_c.c
src/calibre/gui2/tweak_book/editor/smarts/html.py
src/calibre/gui2/tweak_book/editor/syntax/html.py
src/calibre/srv/loop.py
src/calibre/utils/filenames.py

I noticed the content server pop-up modal saying it "could take upto a minute" so I fixed the typo. While I was in there, I just found/replaced it globally.

Fix typo for `upto` => `up to` globally

---

src/calibre/ebooks/metadata/sources/amazon.py

- tests were sucessful
- series_test will fail beccause that information is not available on amazon.ca
- i did not see any region specific code in parse_series and that leads me to beleive that lack of series information is handled elsewhere
- sidenote: my first attempt at squashing my commit history, I hope this doesn't turn out to be a mess on your side

Amazon.CA amended with tests

---

src/calibre/devices/kobo/driver.py

Reworked the cover image generation for uploading. There was an error in calculating the size, the Glo HD sizes needed to be diffrent, the cover file was being read multiple times and the full size was not being
resized when it should have. Also, some refactoring was done at the request of someone subclassing the driver.
Lastly, the firmware build version has been bumped to match the latest release from Kobo.

Rework cover upload

---

setup/build.py

platformsupport-private was modularized in Qt 5.8.
Use the appropriate theme_support-private module

Fix build with Qt >= 5.8.0

---

recipes/apple_daily.recipe

Problem is raised by user:
- ebook-convert + beautifulsoup  generate <hr\> tag
- calibre gui + beautifulsoup  generate <hr \/>tag
Solve by revising the regexp.

Fix navbar localization

---

recipes/nytimes.recipe

this shows up on blogs like "The Upshot". See the source of https://www.nytimes.com/2017/02/01/upshot/strife-over-immigrants-can-california-foretell-nations-future.html?ref=todayspaper. Without the fix "The Upshot" always has "Follow Us" and then three blank bullet points at the top then "Get the Upshot in your Inbox".

remove 'masthead-social' tag

---

recipes/atlantic.recipe

keeping metadata causes each article to start off with an ugly list of author's of most popular articles

don't keep metadata

---

recipes/the_week_magazine_free.recipe

confusing to call this "The Week Magazine". The magazine is a separate publication behind a paywall. This is their website, which has different content.

change title

---

src/calibre/devices/kobo/driver.py

Kobo have released firmware 4.3.8842. No changes are needed other than bumping the supported firmware and database versions.

Bump firmware version for Kobo Driver

---

src/calibre/utils/smtp.py

Some MTAs/spam filters/etc seem more likely to treat an email as spam if it has no Message ID. 
This patch should hopefully make it less likely for an email to be dropped .

Add Message-Id header to outgoing emails.

---

src/calibre/devices/kindle/driver.py
src/calibre/devices/usbms/driver.py
src/calibre/ebooks/metadata/kfx.py

Support getting metadata from sideloaded KFX files by treating the main KFX file of a book as the actual book path instead of the 'metadata.kfx' file. Read metadata.kfx only if the main book file is encrypted.
Also improve KFX metadata reading in general.

Improve KFX metadata handling

---

recipes/nytimes.recipe

NYTimes web sections 'World', 'U.S', and others have <article> tags. This fixes web edition downloads, e.g. World, with zero articles.

[NYTimes] Support <article> tags

---

src/calibre/devices/kobo/driver.py

New firmware from Kobo. No changes need for function except to bump the supported database version.

Bump firmware and database version for latest Kobo firmware

---

src/calibre/ebooks/metadata/sources/cli.py
src/calibre/ebooks/metadata/sources/identify.py

This is very useful for shell scripts that need to compare metadata from different sources or when we have hardcoded preferences (ex. prefer Goodreads to Amazon to Google, etc.)

fetch-ebook-metadata: add option to use only a single metadata plugin

---

src/calibre/utils/lzx/lzxd.c

This includes the changes from the following upstream commits:
https://github.com/kyz/libmspack/commit/6a42ddd1d472afeaf0f7da91e16b60ab2063fb92
https://github.com/kyz/libmspack/commit/ce3cc03aa500dd9c0b6b820f9519f6b6b9dede05

Fix bounds error in lzxd_static_init

---

recipes/private_eye.recipe

I have permission by email from previous author to replace his version.

private-eye.recipe: New version which avoids needing a 3rd party freed

---

recipes/instapaper.recipe

Perhaps there's is a new blog post about the recipe and the line with ["Homepage" entry](https://github.com/kovidgoyal/calibre/blob/master/recipes/instapaper.recipe#L3) should be changed as well.  
It can be left as it is for historical reasons though.

Replacing link to outdated Bitbucket repo with the current one

---

src/calibre/devices/kobo/driver.py

Had inconsistently mangled the case of the collections. Removed the lower() as it the case should be considered.

Fix ignored collections in Kobo Driver

---

src/calibre/devices/kobo/driver.py
src/calibre/ebooks/metadata/book/__init__.py

Collections were not being shown in the device list if either the collection management was off in the driver, or no collections column were configured. There were two reasons, one was the empty configuration
string was handled incorrectly. The other was the device_collections attribute could be cleared by the smart_update of the metadata.

Fix collections not displaying in device list for KoboTouch driver

---

recipes/wsj.recipe

Separately, i've noticed the current recipe includes the "whats news" section which is a compendium of prior days' top posts. This doesn't feel like a fit. I'd propose that a new variable be set, defaulting to False, like include_whats_news that a user could then enable if desired. Thoughts?

Remove junk from redesigned wall street journal

---

src/calibre/db/backend.py
src/calibre/gui2/__init__.py
src/calibre/gui2/actions/edit_metadata.py
src/calibre/gui2/actions/show_quickview.py
src/calibre/gui2/dialogs/quickview.py
src/calibre/gui2/dialogs/quickview.ui
src/calibre/gui2/init.py
src/calibre/gui2/library/views.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/ui.py

This commit contains many improvements and changes to Quickview.
- Add preference tab in Look & Feel to choose columns displayed in QV table and their order
- Option to permit changing the selected column from the quickview widget with return or double-click
- Option to show QV at startup
- Option to ignore virtual libraries in QV searches
- Remove margins on the docked window (tighter display
- Better handling of changes made on the booklist
- Many bugs fixed, some refactoring

Enhancement request #1701833: ability to add columns to quickview pane.

---

src/calibre/gui2/actions/edit_metadata.py
src/calibre/gui2/actions/show_quickview.py
src/calibre/gui2/dialogs/quickview.py
src/calibre/gui2/library/views.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/ui.py

1) handle the odd case where the quickview action is initialized but the actual_plugin is not
2) Fix regression causing QV column headers not to be initialized on startup.

Two Quickview fixes:

---

src/calibre/ebooks/readability/readability.py

This was setting `i` to 1 every loop iteration instead of incrementing it.

Correct a "=+" typo in readability.py's `sanitize` method.

---

src/calibre/devices/kobo/driver.py

New firmware just released. No changes needed except to bump the firmware and database versions.

Bump Kobo supported firmware version to 4.5.9587

---

src/calibre/linux.py

Changes:
* replace root node "application" with "component"
* move the "type" attribute from the "id" node to the "component"
* put screenshot urls into "image" nodes
* change installation location to .../metainfo

Update appstream xml files to current appstream format

---

src/calibre/gui2/actions/edit_metadata.py
src/calibre/gui2/actions/show_quickview.py
src/calibre/gui2/dialogs/quickview.py
src/calibre/gui2/dialogs/quickview.ui

1) Fix regression that broke the "Lock quickview" checkbox.
2) Add a "refresh" action that refills the QV pane when QV is locked.

Two quickview changes

---

manual/gui.rst
manual/virtual_libraries.rst
src/calibre/db/search.py
src/calibre/library/field_metadata.py
src/calibre/srv/errors.py
src/calibre/srv/handler.py
src/calibre/srv/opds.py

Also fix not recomputing the search cache when vls are edited.
There is one backwards incompatibility that I found. If a user has created a grouped search term with the name "vl" then the new vl search location will hide that grouped term.

Add ability to search for books in a vl (vl:foo).

---

recipes/nytimes.recipe
recipes/nytimes_sub.recipe

Currently content links to alternate articles when available in Spanish or Chinese language. These shouldn't be downloaded in a English language paper. Those wishing for foreign language content can acquire this by separately downloading the Chinese or Spanish editions proper.

NYTimes: Exclude CN and ES lang content

---

src/calibre/gui2/dialogs/tag_categories.py
src/calibre/srv/ajax.py
src/calibre/srv/tests/auth.py
src/calibre/web/feeds/news.py

- Add missing args in format strings
- Add missing `self` or `cls` param
- Use new style class in one location where it makes sense

Fix a few minor nits

---

recipes/wired.recipe

1. use seperator "." instead of "-", e.g. tag/magazine-25-02/page/1 => tag/magazine-25.02/page/1 
Note: if you access the magazine for "LOAD MORE RESULTS" from the page (e.g. https://www.wired.com/magazine/what-lies-ahead/), WIRED will still give you the link "tag/magazine-25-02/page/1". But the actual url is "tag/magazine-25.02/page/1".
2. find story links in div.archive-list-component__items
3. use the same remove_tags, keep_only_tags etc. as in latest wired_daily.recipe, so the article can be downloaded successfully.
4. If no new stories are fetched, morepages = False
The old way of making "morepages = False" is to catch HTTP exception. But accessing "tag/magazine-25.09/page/100" will not raise exception any more.
5. The url of story should begin with "/story" instead of …

Make Wired Monthly Recipe Work again

---

src/calibre/ebooks/metadata/sources/douban.py

Reported by calibre user runsun. This bug was introduced in 5f8a7c04, which changed the URL of metadata services from http to https, but forgot to change the namespace URI from http to https.

[Bug] Unable to fetch Douban metadata, due to wrong XML namespace

---

recipes/list_apart.recipe

Seems like the abridged feedburner URL is no longer active (only adverts) so switching to the main feed. If there is any reason to keep it on feedburner, then here is the other URL: http://feeds.feedburner.com/alistapart

Updating feed URL for A List Apart Recipe

---

src/calibre/gui2/metadata/single_download.py

There is space after authors names, so space before `ISBN:` produces two whitespace in row.

Removes needless whitespace in "Downloading metadata" dialog window

---

src/calibre/gui2/dialogs/tag_list_editor.ui

Fix incorrect tooltip.
If I need to do something else let me know (I had flagged this in transifex, if everything is OK I will mark it as resolved there)

Fix incorrect tooltip in tag list editor

---

recipes/mediapart.recipe

Access the login form via its property "id" instead of its (changing) position, as it's not possible to use its name (this form has no name)

Change the way to address login form

---

recipes/nytimes.recipe
recipes/nytimes_sub.recipe

Newseum no longer has the NYTimes cover, so pulling a (sadly lower res) version from NYTimes.com now.

Fix NYTimes cover

---

src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/dialogs/metadata_bulk.ui

1) make the bulk custom and standard series column editors behave similarly
2) allow zero as an increment so that all the books can be set to the same series number (standard and bulk)
The enhancement request suggested that the "Apply changes" checkbox be removed for custom series. I didn't do that because that checkbox is used for all custom columns.

Changes for enhancement #1731750

---

src/calibre/utils/localization.py

In case of LANG=hu_HU.UTF-8 and LC_MESSAGES=C, the expected behavior is
that the UI is English, not Hungarian.
The problem was that we did not differentiate between a not set
LC_MESSAGES and one that is set to C, as locale.getdefaultlocale()
returns None in both cases.

localization: differentiate between C and not set Linux env. variables

---

src/calibre/devices/kobo/driver.py

Kobo is about to release new firmware is about release new firmware. No changes are needed except to bump the support firmware version.

Bump supported firmware version for Kobo 4.7.x firmware

---

recipes/new_yorker.recipe

The XHTML produced by the recipe had an ill-formed XHTML that, when converted to KEPUB, was not properly parsed on Kobo devices.

Fixed New Yorker Magazine recipe

---

setup/build.py
setup/build_environment.py
setup/extensions.json
src/calibre/constants.py
src/calibre/devices/libusb/libusb.c

Don't exclude libmtp on FreeBSD systems.
Don't exclude libusb on FreeBSD systems.  Our libusb has a different include
path structure and libname than Linux, but compiles fine once those are
corrected.
Correct path to py-sip on FreeBSD.  We install it to a different directory
than build_environment.py was looking in.

Compatibility improvements for FreeBSD systems

---

src/calibre/srv/legacy.py

re: "[Feature Request: calibre-server 3.0 should rewrite pre-3.0 URLs](https://bugs.launchpad.net/calibre/+bug/1698411)":
I have implemented client-side redirection of URLs such as:
https://mysite.com/calibre_prefix/browse/book/2542
→ https://mysite.com/calibre_prefix#book_id=2542&panel=book_details

redirecting legacy /browse/book/ URLs

---

src/calibre/devices/mtp/unix/driver.py
src/calibre/devices/scanner.py

The HAL scanner adds a needless dependency on a runtime service and the
libusb scanner is perfectly fine.
This fixes detection of MTP devices on FreeBSD.
The logical patch was written by Guido Falsi; additionally, I removed
the legacy FreeBSDScanner class.

Just use libusb to scan USB devices on FreeBSD

---

src/calibre/gui2/toc/main.py

Add a submenu with more case options in the contextual menu of the TOC
editor and rearrange the menu for better readability.

Case submenu in TOC editor contextual menu

---

src/calibre/devices/smart_device_app/driver.py

- listen(0) doesn't work on Linux, select.select() and socket.accept() return no connection

Fix Calibre Companion sync on Linux

---

src/calibre/gui2/dialogs/trim_image.py

Currently there is no space: https://i.imgur.com/2bW41RX.png

Added a space before image dimensions in “Trim Image” window

---

src/calibre/devices/kobo/driver.py

My brand new Kobo Aura Edition 2 (firmware 4.6.10188), bought today in FNAC shop (France) has these UBS IDs:
VENDOR_ID: 0x2237
PRODUCT_ID: 0x4226
BCD: 0x401
This BCD isn't known by the drivers: adding it into the BCD list variable fix device detection.

Fix Kobo Aura Edition detection (Bug 1756556)

---

recipes/oregonian.recipe

Current codebase `cover_url` points to someone's personal photobucket (it seems) and has a cover from 2010.
Judging by other recipes, kioskio is commonly used as a source for up-to-date covers.
Thanks for Calibre!

Switch to kioskio for Oregonian cover_url

---

src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py

Adding an option for overriding the Kobo firmware behaviour when a book is replaced. The default behaviour is for the book to be removed from the internal database and then treated as a new book. This means the reading status is lost. But, the KoboTouch driver has always overriden this behaviour and to allow the reading status to be kept. The option is to override the firmware behaviour and defaults to on to keep the existing driver behaviour.
Kobo has released new firmware. The only change is to bump the firmware and database versions.

New option to override KoboTouch driver book resend behaviour and bump the supported firmware version

---

src/calibre/gui2/library/views.py

When using split book list, horz scroll of the _other_ pane can change unexpectedly when changing selection if the last selected cell in that pane is no longer in sight.  This change preserves the current horz scroll.

Save/restore horz scroll when mirroring selection across splitter.

---

src/calibre/db/cli/cmd_add.py

The recent change to the "calibredb add" command is not detecting when filetype plugins have changed the format during import.

Detect when format has changed during import

---

recipes/lwn_weekly.recipe

As security section has no URLs in article titles, findNext() boldly returns whatever
next link is encounered after the anchor. This leads to downloading and including in generated
document of heavy CVE reports, as links to them usually placed after the article title.
Instead we'd better search under anchor tag only, this way we'll filter useful articles' links.

lwn_weekly: fix security section articles parsing

---

src/calibre/devices/kobo/driver.py

Kobo has announced a new device, the Clara HD. It is the same size and resolution as the Glo HD, so just needed to add the device id.

Add support for Kobo Clara HD

---

setup/linux-installer.py
setup/linux-installer.sh

If the umask is set up to exlude execute, the installer will set up
calibre to be unreadable by any user other than the installing user.
When installing as `root`, a starting umask of `0o077` results in the
installer choosing a new umask of `0o033`, which means the calibre
install directory (and child directories) are installed with permissions
`0o744`, so only the installing user can actually use the resulting
calibre install.
To test, start with a system umask of `0o077` and run the installer
script as root:
```
% sudo sh ./setup/linux-installer.sh
Using python executable: /usr/bin/python3
WARNING: Your current umask disallows reading of files by some users, this can cause system breakage when running the installer because of bugs in common system utilities.
Should the installer (f)ix …
```

Exclude execute from umask

---

src/calibre/devices/kindle/driver.py
src/calibre/devices/kobo/driver.py

A recent change to BeautifulSoup broke the building of annotations. This fixes them. But, has only been tested for Kobo devices. The code is identical for Kindles at this point, so it should work.
Also, Kobo have just release a firmware update. The only change is for the supported version numbers.

Fix annotation retrieval and bump Kobo fimware version

---

src/calibre/devices/kindle/driver.py
src/calibre/ebooks/metadata/kfx.py

Add the ability to create Kindle thumbnails for books sent in KFX format. 
The content_id and cde_type are extracted from the KFX file and used to create the thumbnail filename in much the same way that the equivalent fields are extracted from MOBI/AZW3 files.

Create thumbnail images on Kindle for KFX format

---

src/calibre/devices/kobo/driver.py

A new firmware version is coming. There are no changes needed except to bump the supported firmware version.

Bump supported Kobo firmware version

---

setup/build.py
src/calibre/utils/spell/hunspell_wrapper.cpp

py27 result:
```
test_dictionaries (calibre.spell.dictionary.TestDictionaries) ... ok [0.2 s]
```
Manually tested on py3 (since it's not possible to import the test on py3):
```
>>> import hunspell
>>> dic = open('/home/user/dev/calibre/resources/dictionaries/en-US/en-US.dic')
>>> aff = open('/home/user/dev/calibre/resources/dictionaries/en-US/en-US.aff')
>>> dic = dic.read()
>>> aff = aff.read()
>>> hunspell.Dictionary(dic, aff)
<Dictionary object at 0x7f2399a26770>
>>> d = hunspell.Dictionary(dic, aff)
>>> d.suggest('foo')
('few', 'foo', 'goo', 'fop', 'foot', 'fool', 'food', 'foe', 'for', 'fro', 'too', 'fol', 'loo', 'coo', 'fog')
>>> d.recognized('foo')
True
>>> d.suggest('ade-quately')
('ad-quately', 'aide-quately', 'lade-quately', 'made-quately', 'bade-quately', 'fade-quately', …
```

Build hunspell in py3

---

src/calibre/gui2/tweak_book/check.py

In ebook-edit, if a filename contains a '%' clicking 'Run check'
results in an error:
File "/usr/lib/calibre/calibre/gui2/tweak_book/boss.py", line 72, in ans
return func(*args, **kwargs)
File "/usr/lib/calibre/calibre/gui2/tweak_book/boss.py", line 1249, in check_requested
c.run_checks(current_container())
File "/usr/lib/calibre/calibre/gui2/tweak_book/check.py", line 221, in run_checks
self.current_item_changed()
File "/usr/lib/calibre/calibre/gui2/tweak_book/check.py", line 206, in current_item_changed
template % (err.HELP, ifix, fix_tt, fix_msg, run_tt, run_msg))
ValueError: unsupported format character '_' (0x5f) at index 167

Escape part of a template string

---

src/calibre/gui2/actions/edit_metadata.py
src/calibre/gui2/actions/tweak_epub.py
src/calibre/gui2/metadata/basic_widgets.py
src/calibre/gui2/metadata/single.py

Feature change for Context (right-click) menu in Edit metadata formats list.
- View for any format type, duplicates double-click feature.
- Edit for 'Edit book' supported types only.
- Prompt to save metadata before Edit book, if metadata was changed and `update_metadata_from_calibre`.
- 'Restore XXX from the original' functionality retained as-is.
99% of the time, I want to edit epub.  But for that 1% I want to edit azw3, this gives me a better option than going into Edit book to change the "Ask which format" setting.  (Especially since that setting is kind of hard to find once you've changed it from the dialog in Calibre.  I had to search the source to find it.)
Tested on Win10, Ubuntu18.04(VM), MacOS10.14(VM).
(Tested and committed against v3.31.0 tag because kovidgoyal/calibre master …

Add context menu with View & Edit to Edit metadata formats list

---

src/calibre/gui2/notify.py
src/calibre/linux.py

Due to Gnome Guidelines https://wiki.gnome.org/Initiatives/GnomeGoals/NotificationSource
Now, due to the absence of these parameters, notifications from the calibre are displayed as "Others"

Gnome notifications fix

---

setup/extensions.json
src/calibre/srv/http_response.py

Done by disabling building zlib extension in py3, and falling back to
py's zlib when calibre's zlib extension fails to load.
However, I can't see much point in calibre shipping it's own zlib2 module, in either py2 or py3:
With calibre's zlib2:
```console
$ python2 -m timeit -s  'import test; f = open("./rand", "rb")' -n 2 'list(test.compress_readable_output(f))'
2 loops, best of 3: 1.39 sec per loop
```
With python's zlib2:
```console
$ python3 -m timeit -s  'import test; f = open("./rand", "rb")' -n 2 'list(test.compress_readable_output(f))'
2 loops, best of 5: 1.39 sec per loop
$ python2 -m timeit -s  'import test; f = open("./rand", "rb")' -n 2 'list(test.compress_readable_output(f))'
2 loops, best of 3: 1.4 sec per loop
```
test.py:
```python
import struct
#import zlib2 as zlib
import …
```

Use builtin zlib in py3

---

src/calibre/utils/icu_calibre_utils.h

I was looking at your changes to `python_to_icu32` and realized that I messed up the call to memcpy in `python_to_icu`.

Fix incorrect memcpy

---

src/calibre/gui2/tweak_book/editor/syntax/html.c

I haven't been able to test this in py3 because this module depends pretty closely on other calibre internals. `Tag()` and the attributes do seem to work fine though.

Convert html to py3

---

src/calibre/devices/kobo/driver.py

New device, the Forma is coming. Already added the product ids, but the firmware will be version 4.11.x.

Bump Kobbo firmware version for the upcoming Forma

---

src/calibre/gui2/preferences/plugboard.py

This allows modification of comments to add info not displayed on the device as part of the comments/description/synopsis or whatever on the device. It was discussed in https://www.mobileread.com/forums/showthread.php?t=291138. I have been running this since before then with no issues for Kobo devices and save-to-disk. It includes a warning prompt as mangled comments could cause a problem. But, mangled any field could as well.
I should have done this ages ago.

Add comments to metadata plugboard

---

src/calibre/ebooks/metadata/sources/base.py
src/calibre/gui2/metadata/basic_widgets.py

Extend identifier from URL parsing to use metadata source plugins and the identifier rules. Each plugin needs to override the id_from_url method.

Use metadata source and identifier rules to generate identifiers

---

.gitignore
src/calibre/gui2/tweak_book/editor/syntax/html.c
src/tinycss/tokenizer.c

- The actual unicode manipulation wasn't converted to the new 3.3+
style, since it would lead to lots of ifdefs and become quite ugly. This
can be done when py2 support is dropped. The drawbacks will be
temporary slower code (there will be extra copying required).
- The CLEANUP() macro is also used more extensively to avoid redundant
code
I also used my IDE's formatting tools to add some newlines and make things a little easier to read. If you'd like, I'd be happy to revert these changes. You can ignore the whitespace changes in the github diff by appending `?w=1` to the url.

Build tokenizer on py3

---

src/calibre/gui2/viewer/config.py

The box appears when the user has edited a shortcut and clicks 'OK' before
the shortcut is actually created.

Improve formatting for an infobox when editing keyboard shortcuts in viewer

---

src/calibre/devices/kobo/driver.py

I can't see how you can get to this line with the series index not set, but someone has, and it should have been done this way for safety.

Catch exception if the series index is somehow None

---

setup/mathjax.py

If unpacked mathjax resources cannot be found, fallback to the packed version.
Allow symlinking a system mathjax directory as `resources/mathjax`.

Add option to build against system mathjax

---

setup/install.py

Without this, python's default behavior was to dereference the mathjax symlinks and install the file contents instead.

build: preserve symlinks when installing

---

src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/dialogs/metadata_bulk.py
src/calibre/gui2/library/delegates.py
src/calibre/gui2/metadata/basic_widgets.py

This fix is suboptimal in that one cannot edit the timezone. This is AFAIK a QDateTimeEdit restriction.

Sort-of fix for #1812560: editing datetimes with iso format doesn't work

---

src/calibre/utils/fonts/freetype.cpp

If I understand correctly, the freetype data is bytes and so should use `y#`.

Port freetype plugin to build on python2/python3

---

src/calibre/devices/libusb/libusb.c
src/calibre/devices/mtp/windows/device.cpp
src/calibre/devices/mtp/windows/wpd.cpp
src/calibre/devices/usbobserver/usbobserver.c
src/calibre/ebooks/compression/palmdoc.c
src/calibre/utils/fonts/winfonts.cpp
src/calibre/utils/windows/winutil.c
src/lzma/lzma_binding.c

Just some more basic translation to python3 compatible module definitions, but I cannot even test that they compile properly for the Windows/OSX specific ones. Still, they "should" work.
EDIT: now they do

py3: finish up the rest of the C extension ports

---

src/odf/userfield.py

Commit 55151a3cdd4e595be49f2392731b972439f51408 tried to replace this with python2/python3 compatible code, but missed the closing quote, so it is compatible with neither. :D

Fix syntax error introduced while getting rid of basestring

---

src/calibre/ebooks/pdf/render/graphics.py

Reference bug: https://bugs.launchpad.net/calibre/+bug/1821923
The QtPen's `pen.style()` return value for an SVG element with a stroke-dasharray attribute is Qt.CustomDashLine, which was not previously in the list of values checked by graphics.py's `apply_stroke()` method.
This code adds a check for Qt.CustomDashLine and if present, usees the `pen.dashPattern()` and `pen.dashOffset()` values for the dashArray and dashPhase parameters to the 'd' operator respectively.
It also now always sets the 'd' operator. Previously, the 'd' operator would only be set if the `pen.style()` was found in the list. Without this change, the 'd' operator's value persists to future paths, making them dashed even if they wouldn't have been otherwise.

Fixing stroke-dasharray rendering bug (#1821923)

---

src/calibre/customize/ui.py
src/calibre/db/cli/cmd_add.py
src/calibre/db/fields.py
src/calibre/debug.py
src/calibre/devices/kobo/books.py
src/calibre/devices/udisks.py
src/calibre/ebooks/metadata/fb2.py
src/calibre/ebooks/txt/processor.py
src/calibre/gui2/add.py
src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/metadata/single.py
src/calibre/gui2/preferences/create_custom_column.py
src/calibre/gui2/preferences/emailp.py
src/calibre/gui2/preferences/server.py
src/calibre/gui2/store/__init__.py
src/calibre/gui2/store/loader.py
src/calibre/linux.py
src/calibre/test_build.py
src/calibre/utils/config.py
src/calibre/utils/filenames.py
src/calibre/utils/fonts/metadata.py
src/calibre/utils/fonts/sfnt/cff/dict_data.py
src/calibre/utils/fonts/sfnt/metrics.py
src/calibre/utils/fonts/win_fonts.py

Found while looking at python3 issues:
- import `JSONConfig` from where it is defined, rather than transitively from somewhere it is used
- port old code to use `unicode_type` instead of `type(u'')`, including one place in gui2/store/ which is not actually being loaded dynamically, thus does not need this as a backwards-compat mechanism.
- as a followup on 3bece11b09bc61380a438c7580dc9faf7463015e I think we can just use unicode_literals here, which in general means less work writing new code, and easier removal of python2 compat sometime down the line.

cleanup misc neatness issues

---

src/calibre/devices/kobo/driver.py

New firmware released. No changes that affect the function. Just bumping the supported firmware version number.

Bump supported Kobo firmware version number

---

src/calibre/db/cli/main.py
src/calibre/ebooks/conversion/cli.py

When checking for a minimum requirement of arguments and aborting with the help text otherwise, we should first check to see if the help text was explicitly asked for.
Found while otherwise fiddling with python3 stuff

do not exit with an error when $command --help is successfully used

---

src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py

Kobo changed what format the language is expected to be in the database. Plus I somehow missed saving an option.

Fix language metadata on device and an option

---

src/calibre/ebooks/oeb/polish/container.py

Fixes saving books in the editor.

py3: encode string before writing ebook mimetypes to the container

---

src/calibre/devices/kindle/driver.py
src/calibre/devices/kobo/driver.py

I have only tested the Kobo version, but the Kindle is the same at this point.

Fix typo in BS4 changes for fetching annotations

---

src/calibre/ebooks/snb/snbfile.py

conversion of a sample epub to snb on python3 produces identical results as on python2.

py3: make SNB output work

---

src/calibre/ebooks/metadata/kfx.py

KFX format has both an old-style and new-style method of handling metadata. Some older KFX books contain both types of metadata and their content does not always match for reason unknown to me.
Process any old-style metadata present in a KFX book last so that new-style metadata will take precedence if both are present. This makes it consistent with how the KFX Input plugin processes metadata and corrects the occasional mismatch of book titles shown in Device view for a Kindle vs. the title shown in calibre if the book is imported.

Improve handling of KFX metadata

---

src/calibre/gui2/dialogs/plugin_updater.py

calibre's internal version representation is a tuple. On python3, it no longer suffices to compare this to json.loads() list-based representations.
Also update one instance of map where we need something subscriptable.

py3: make plugin updater work

---

src/calibre/web/fetch/simple.py

Just some more juggling around of bytes types. Specifically note that urls are encoded and quoted, then decoded before being given to mechanize as mechanize expects to see unicode (at least, try to `import mechanize; b = mechanize.Browser(); b.set_handle_robots(False); b.open(b'https://www.google.com')` and it will complain inside the guts of mechanize._rfc3986). Furthermore, ascii_filename is already there to sanitize filenames.
...
The mechanize handling quoting thing is something that might be nice to fix in mechanize itself, eh? ;)
Anyway, some randomly chosen recipes (abc.recipe) now download in the GUI for me, some others don't (ars_technica.recipe) -- the latter complains that it cannot do self.attrs.get(key, default) via the overridden preprocess_html method. I'd guess that this …

py3: basic news fetching works

---

src/calibre/utils/complete.py
src/calibre/utils/serialize.py

msgpack.loads will produce mutable, unhashable lists by default when unpacking values that were originally saved as dicts with tuple keys. Which ebook-convert-complete does. This results in errors when
trying to reassemble the dict.
Fix by allowing our msgpack wrapper to forward arguments, and by having ebook-convert-complete unpack lists as tuples.

fix CLI completion for ebook-convert

---

src/calibre/ebooks/metadata/__init__.py

python3 zip() is depleted the first time you use it, but this will need to be used many times.
Noticed while running the python3 version and seeing a series appear as " of XXX", rather than 
"# of XXX".

 py3: fix metadata panel showing roman series numbers 

---

src/calibre/gui2/preferences/toolbar.py

The sort() call is operating on objects that have no comparison functions and span multiple types, so they were always compared by their hash(). This resulted in adding an action, then removing it, causing the entire "Available Actions" box to be sorted seemingly at random.
This was uncovered during python3 porting, as the objects cannot be compared at all and therefore return errors.
The default sort order (before anything is done) is to sort based on pretty names, and therefore use this as the sort key when re-sorting.

preferences: fix sort order when moving an action out of the toolbar

---

setup/commands.py
setup/git_version.py
src/calibre/constants.py

This creates an additional variable containing the version number extracted from a git checkout via `git describe`, and diverts all human-readable output to use that via get_version.
Take 2, incorporates feedback from #985

setup: add subcommand to update the version in constants.py from git

---

setup/install.py
src/calibre/linux.py

When installing calibre for distro packaging, there are some slightly non-intuitive snags. The primary issues are:
- calibre-uninstall is useless as we don't want to give users the option to circumvent the package manager
- xdg-utils doesn't really have a decent mode for doing staged (`DESTDIR`) installs, thus, some hacks are needed. I've long since implemented these hacks in my packaging, but I suspect others have not... and anyway I would like to drop this code from my packaging, so here is my attempt to merge those actions directly into calibre's build system.
The changes I've implemented here are intended to only run when --prefix is not the same as --staging-root, since we can presume in that case that any user who is not installing directly to their final destination (a live …

Staged install: misc fixups

---

src/duktape/__init__.py

Bootstrapping of Calibre with Python 3 currently fails with the following error message:
```
File "/home//aimylios/calibre/src/duktape/__init__.py", line 259, in __init__
self.g.Duktape.load_file = partial(load_file, base_dirs or (os.getcwdu(),), builtin_modules or {})
AttributeError: module 'os' has no attribute 'getcwdu'
```
This commit replaces the last occurrence of os.getcwdu() with getcwd from polyglot.builtins to fix this issue. Bootstrapping with Python 3 still does not work for me, but at least I get a different error message.

py3: Remove last occurrence of os.getcwdu()

---

src/polyglot/builtins.py

This resulted in e.g. ebook-convert-complete still storing most formats in msgpack as bytestrings, and therefore not being completed.

py3: recursive forcing to unicode missed converting set()

---

recipes/insider.recipe

Strings that contain non-ascii literal characters cannot be made into bytestrings merely by adding b'' and must either be encoded or use hex escapes.

py3: fix regression in commit 96a8aeaaf5420dcdbb3cbeb1856a4985e8942395

---

resources/templates/html_export_default.tmpl
resources/templates/html_export_default_index.tmpl
src/calibre/ebooks/conversion/plugins/fb2_input.py
src/calibre/ebooks/conversion/plugins/html_output.py
src/calibre/ebooks/conversion/plugins/pml_input.py
src/calibre/ebooks/conversion/plugins/snb_output.py
src/calibre/ebooks/conversion/plugins/txt_input.py
src/calibre/ebooks/conversion/preprocess.py
src/calibre/ebooks/mobi/reader/mobi8.py
src/calibre/ebooks/oeb/base.py
src/calibre/ebooks/pdb/header.py
src/calibre/ebooks/pdb/palmdoc/writer.py
src/calibre/ebooks/pml/pmlml.py
src/calibre/ebooks/rtf2xml/ParseRtf.py
src/calibre/ebooks/rtf2xml/line_endings.py
src/calibre/ebooks/rtf2xml/paragraph_def.py
src/calibre/ebooks/rtf2xml/process_tokens.py
src/calibre/ebooks/rtf2xml/tokenize.py

It is now possible to convert to and from most formats. Note that I haven't touched tcr input/output, and rtf2xml is a hot mess (of unmaintained upstream code that has two commits for python3 that don't actually fix any but the most superficial problems).

py3: various conversion fixes

---

src/calibre/ebooks/djvu/__init__.py
src/calibre/ebooks/djvu/djvu.py
src/calibre/ebooks/djvu/djvubzzdec.py

The surplus space characters may confuse packaging scripts that try to automatically find and delete or modify shebang lines, e.g. to replace "#!/usr/bin/env python3" by "#!/usr/bin/python3".

Remove space characters from djvu shebangs

---

COPYRIGHT
setup/extensions.json
src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py
src/calibre/utils/imageops/imageops.h
src/calibre/utils/imageops/imageops.sip
src/calibre/utils/imageops/ordered_dither.cpp
src/calibre/utils/img.py

* Optional dithering down to the exact eInk color palette.
Recent FW versions got better at this than they used to,
but it's still not perfect.
Note that Mk. 7 devices can and *will* enforce HW dithering,
at the very least on sleep screens, using an ordered dither pattern,
like we do.
Speaking of, said ordered dithering pattern has been ported from ImageMagick.
This has the added bonus of generating much smaller PNG files.
Depends on B&W covers to avoid nonsensical results.
* Optional letterboxing of full-screen covers to avoid extra Nickel
processing.
Depends on Keep AR to avoid nonsensical results.
* Optional storage as PNG to avoid JPG wrecking the dithering
Depends on B&W covers to avoid storing stupidly large color PNGs.
* Revamp thumbnail dimension calculations to match what's done …

Greater control over Kobo thumbnails & sleep cover processing

---

src/calibre/devices/kobo/kobotouch_config.py

The order of the existing options should have been maintained. Plus centering one of the didn't look good,

Better layout of new cover options in KoboTouch driver.

---

src/calibre/headless/headless_integration.cpp

In https://github.com/qt/qtbase/commit/01e1df90a7debd333314720fdd5cf6cd9964d796, screenAdded was deprecated, and as of qt 5.13 it is fully removed. Adapt to this change by using the new API in QWindowSystemInterface.

fix qt 5.13 compatibility

---

setup/build.py

Sort input file list
so that `calibre/plugins/lzma_binding.so` builds in a reproducible way
in spite of indeterministic filesystem readdir order
and http://bugs.python.org/issue30461
See https://reproducible-builds.org/ for why this is good.

Sort input file list

---

src/calibre/utils/open_with/linux.py

If the cache failed to load, it is initialized as a defaultdict and all mtimes compare as 0. If the cache did load, however, then an ordinary dict was used, and if new icon directories appeared on the system since the cache creation, they would raise a KeyError and Open With would not load data.
Fix by using a defaultdict in all cases, but initializing with the contents of the cache if possible.
Discovered when crazy applications added crazy subdirectories in /usr/share/pixmaps (???) and suddenly calibre failed to do the right thing, but the same should apply if the system adds a new icon theme.

Open With: don't raise KeyError if cache exists and there are new dirs

---

src/calibre/ebooks/metadata/archive.py

The [ComicBookInfo](http://code.google.com/p/comicbookinfo/wiki/Example) metadata includes a 'language' field.

Add missing 'language' field to ComicBookInfo metadata for .CBR files.

---

recipes/new_yorker.recipe

not a significant one here...
In Kindle app or Kindle devices, if the resolution of a book's cover is too low, the device would only show a generic (blank) cover. It makes the screen looks ugly if your whole library displays the cover nicely except for one or two.
replacing the original src img size with a bigger size solves this issue
this is discuessed in
https://www.mobileread.com/forums/showthread.php?t=293114

if the cover img resolution is too low, kindle wouldn't show it.

---

recipes/nature.recipe

kindle app on larger tablets does not show cover
if the cover img resolution is too low.
(same as my previous PR)
sorry i'm just doing this for the periodicals that I read..

enlarge cover img resolution by change the url

---

src/calibre/ebooks/metadata/html.py

All of the below formats are supported and would be interpreted as "foo:bar"
```
<meta name="DC.identifier" scheme="foo" content="bar" />
<meta name="dc:identifier.foo" content="bar"/>
<meta name="DCTERMS:identifier" scheme="foo" content="bar" />
<meta name="dcterms.identifier.foo" content="bar" />
```
Refactoring the existing meta and comment tag parsing to use the same `HTMLParser` subclass would make it straightforward to only parse the HTML once and reduce the reliance on regular expressions but I didn't want to go rewriting things before making sure this PR would be accepted.

Support Dublin Core id tags when importing HTML

---

recipes/globe_and_mail.recipe

Updated article title so it no longer includes the section the article belongs to (g&m includes it in the a tag, so now we find the div with the headline alone inside the a tag), 
Added article meta data to remove_tags because it was taking up almost 1 full page of dummy text.
Added real estate section. 
Updated newspaper name to its proper one.

Updated The Globe and Mail recipe

---

setup/mathjax.py

There is actually no real consequential change here, because the update is a trivial bugfix that doesn't affect calibre's use, but let's do it anyway because it is both simple and harmless.

resources: bump mathjax version to 2.7.6

---

src/calibre/devices/kobo/driver.py

A last minute change from Kobo bumped the database version in the release for the Libra H2O.

Bump dbversion in KoboTouch driver

---

recipes/wsj.recipe

due to i18n, the text "Sign Out" might not appear in the returned html. Therefore for people sending the requests from non english speaking country, the if condition would incorrectly raise an exception despite a successful login. I am changing the if condition to check the a tag href instead.
The <i>a<i> tag for logging out is : 
```
<a href="https://accounts.wsj.com/logout?target=">登出</a>
```

wsj.recipe: update the if condition to check successful login

---

src/calibre/devices/mtp/unix/driver.py

When I launch the calibre application build for python3 I get two errors about expecting bytes not str and the other way around.
in src/calibre/devices/mtp/driver.py and src/calibre/devices/mtp/unix/driver.py
I found that theses edits remove the error.

Avoid error on python3 about str and bytes

---

src/calibre/gui2/store/stores/nexto_plugin.py

There's no need to run regular expressions on a str(list()) of lxml element results, to see if anything contains a string -- simply use the XPath grammar contains() and check if any results were returned.
...
Turns out we don't need to care whether this gets ported to unicode_type or not, since it's totally unneeded. :D

Nexto store: remove use of type('') with better xpath

---

setup/linux-installer.py
setup/linux-installer.sh

I was looking for a way to install a specific version of calibre instead of latest.
I'm not sure about the `check_version` function. It doesn't seem to be used and I'm not sure what it does.

Allow a user to specify the version that is installed

---

src/calibre/ebooks/fb2/fb2ml.py

Hi,
Thank you for adding the [support for PNG images](https://bugs.launchpad.net/calibre/+bug/1844911), it speeds up the conversion.
But even after these changes the conversion of one average book takes roughly one hour. I looked into the code and found that most of the time spent on splitting of the base64 string. Python strings are immutable and appending just one char to a string leads to copying the whole string on each iteration. The better way to use the slice method.
The old code converts one image with size of 820 Kb more than 11 minutes, the new one – faster than one second of time.
Code | Seconds
--- | ---
old | 680.590
new | 0.014
[split_test.zip](https://github.com/kovidgoyal/calibre/files/3696952/split_test.zip)
So now the conversion of one book takes only several seconds.
We …

Speed-up of the FB2 writer and other fixes

---

src/calibre/gui2/dialogs/template_dialog.py

0 isn't a valid comparison for ICU sort_key() output and returns tracebacks instead, but sort_key(0) is.

py3: use correct sort key for forcing an element to sort first

---

setup/check.py

Some of these files no longer exist due to being devendored. BeautifulSoup.py is now something else entirely which is calibre-specific code and deserves the right to be linted.

check: cleanup file exclusions

---

src/calibre/gui2/actions/polish.py

Assuming I guessed right on the column icon rule, the problem is that Polish doesn't clear the icon caches (or any other cache). I fixed this by adding a call to refresh_ids
after line 532. My problem is that I don't know what to do with the resulting lines 534-536. Do they need to stay? They are updating the book details pane. As far as I can tell, refresh_ids does not do that update, so the lines should stay. Do you agree?

Possible fix for #1850764.

---

src/calibre/gui2/book_details.py

Calibre v3 had right click copy link for ids & author links, just trying to put it in again.
I'd _like_ to have drag-and-drop for ids at least again, but that's beyond me this evening.

Add right-click copy link for identifiers and author links in book details.

---

setup/linux-installer.py
setup/linux-installer.sh

This does not seem to have been a very commonly hit case, since it's been broken for python3 since before 2014, but a user has just hit it for the first time.
Fixes #1851873

linux installer: fix python3 re.sub with mismatched str/bytes

---

src/calibre/devices/kobo/driver.py

Had wrong database version for addition of ISBN column. Also missed Libra H2O in the names of supported devices.

Fix for https://bugs.launchpad.net/calibre/+bug/1830101

---

recipes/denikn.cz.recipe

Fix Czech local time handling in Denik N recipe

---

setup/hyphenation.py
setup/mathjax.py
setup/revendor.py

Motivation: I'd like to be able to point the hyphenation dicts at a cached tarball for non-network builds. So I figured I could reuse the mathjax code, and I'd previously attempted to refactor this so I had a bit of handy progress.
I've also taken a stab at making the download code not clean and retry it if it already exists: https://github.com/eli-schwartz/calibre/commit/627955f7d2224059bab192837f64a397fa1b1315
But I'm not sure about this since the similar mathjax code checks the version in the mathjax manifest. I think it would be quite nice to do this somehow, though, because currently every execution of setup.py resources will redownload this tarball. (But with this PR, you can make it use --path-to-hyphenation instead.)
P.S. Why do these need to be stored compressed, and then …

setup: add option to use offline hyphenation dicts

---

src/calibre/gui2/win_file_dialogs.py

It's the format argument, not actual data, and it's perfectly happy to be a plain str. But using a b'' string in python3 means we cannot interpolate an int inside, so we get the error message:
>>> serialize_binary('foo', True)
File "<stdin>", line 1, in <module>
File "/home/eschwartz/git/calibre/src/calibre/gui2/win_file_dialogs.py", line 61, in serialize_binary
return struct.pack(b'=B%ssB' % len(key), len(key), key, int(val))
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'int'
Fixes https://www.mobileread.com/forums/showthread.php?p=3929837#post3929837

Don't pass the "format" argument of struct.pack as a bytestring.

---

src/calibre/ebooks/oeb/polish/create.py

Metadata objects are unicode strings, but we tried to write the content directly to a .txt file opened in binary mode.

py3: fix creation of empty record with .txt format

---

recipes/liberty_times.recipe

1. Use https:// now as that becomes their default.
(http:// urls are all redirected to https://)
2. Several URL were replaced. The current list can be found at: https://service.ltn.com.tw/RSS
The URLs for logo and cover images were also replaced because the old
one can no longer be found.

Update feed URLs of Liberty Times.

---

setup/test.py
src/calibre/utils/run_tests.py

The Calibre test suite currently allows to specify individual or groups of tests to be executed. What is missing are options to exclude individual or groups of tests from the set of all available tests. This would especially be helpful when packaging Calibre for Linux distributions, e.g., when certain dependencies (like libunrar) can not be made available or some tests are known to be flaky on the build server. It is much easier to maintain a short list of tests to be excluded than a long list of tests to be executed.

Add options to exclude test modules and individual tests from test run

---

src/calibre/ebooks/metadata/sources/amazon.py

try to fix
```
Making google query: https://www.google.com/search?q=%28hidden_isbn+or+hidden_isbn%29+site%3Awww.amazon.jp
Failed to find any results on results page, with title: (hidden_isbn or hidden_isbn) site:www.amazon.jp - Google Search
No search engine results for terms: (hidden_isbn OR hidden_isbn)
```
should be ```site: www.amazon.co.jp```
confirm from my local with `calibre-debug -g`
it seems  site:www.amazon.jp does not work, site:www.amazon.co.jp works fine. 
I assume amazon japan changes their spider policy...etc

[metadata]fix amazon japan for referrer

---

src/pyj/read_book/view.pyj

In flow mode, at the beginning of a chapter X, when scrolling up with a touch screen to go to the chapter X-1, sometimes, we go to the chapter X-2 instead. 
This is because the flag to indicate that a loading is in process is set to false too early. When it is set, the scrolling to the end of the chapter X-1 is not yet done. When the next touch move event happen (the finger is still moving on the screen), the _check_for_scroll_end will then detect that we are at the beginning of the chapter X-1 and requests another change of chapter. Because the loading flag was already set to false, this change of chapter is accepted and we are at the chapter X-2.
The code is quite dense and I do not have experience on it. I hope the fix is appropriate.

Fix bug when scrolling up to the previous chapter

---

src/calibre/gui2/dialogs/metadata_bulk.py

If you have books with series and series_index > 1, and use bulk metadata to clear_series, then sort by series puts these at the bottom of the list because the series_index has not been reset to 1.

Fix series sort after using clear_series

---

resources/content-server/reset.css
src/pyj/read_book/iframe.pyj
src/pyj/read_book/touch.pyj

Hi,
With this branch I fix the lag when scrolling with a touch screen in flow mode at the beginning of a chapter:
-  After changing of chapter by scrolling, the following start events are not cancelable and trigger the error "**Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.**". I guess there is a bug in Chromium with the scrollTo fonction called just before the touch. It somehow creates lags. To fix it, the only solution I found is to add the **touch-action:none** to the style of the body. It does not seem to break any touch interaction in the viewer. 
- I also found that the touch end event is not triggered when changing of chapter. This is probably the bug …

Fix touch lag when changing chapter in flow mode

---

src/calibre/devices/smart_device_app/driver.py

Should be a byte string, rather than a character string. Fixes error when connecting from Calibre Companion.

Fix string encoding

---

src/calibre/devices/kobo/books.py
src/calibre/devices/kobo/driver.py

The new firmware has a Series Tab which uses the seriesId in the database to group the books.

Update for Kobo firmware and the Series Tab

---

src/calibre/ebooks/metadata/sources/douban.py

the API response is
```
{
"rating":{
"max":10,
"numRaters":6223,
"average":"9.4",
"min":0
},
"subtitle":"",
"author":[
"George Orwell"
],
"pubdate":"1961-1-1",
"tags":[
{
"count":1426,
"name":"乔治·奥威尔",
"title":"乔治·奥威尔"
},
{
"count":1229,
"name":"反乌托邦",
"title":"反乌托邦"
},
{
"count":837,
"name":"1984",
"title":"1984"
},
{
"count":778,
"name":"小说",
"title":"小说"
},
{
"count":767,
"name":"政治",
"title":"政治"
},
{
"count":524,
"name":"极权",
"title":"极权"
},
{
"count":441,
"name":"外国文学",
"title":"外国文学"
},
{
"count":412,
"name":"社会",
"title":"社会"
}
],
"origin_title":"",
"image":"https://img9.doubanio.com\/view\/subject\/m\/public\/s1435696.jpg",
"binding":"Mass Market Paperback",
"translator":[
],
"catalog":"",
"pages":"268",
"images":{
"small":"https://img9.doubanio.com\/view\/subject\/s\/public\/s143 …
```

douban.py: download hi-res cover

---

recipes/la_jornada.recipe

Old domain (www.jornada.unam.mx) has started to trigger HTTPS errors, so switch completely to the new domain

Change domain to www.jornada.com.mx

---

src/calibre/gui2/viewer/toolbars.py

When starting ebook-viewer standalone without a book, set_book_path has never been called and there is no pathtoebook attribute yet. In this case, we certainly don't need to compare it to the current book.

viewer: handle recently opened list when started without a book

---

recipes/mit_technology_review.recipe

this is re this bug [report](https://bugs.launchpad.net/calibre/+bug/1869553)
adding storyContent class because it is the upper div of most p tags in the articles. 
Only the headline article does not wrap the p tags under storyContent class. that's why the previous recipe only downloads the headline article and all the rest failed to download

mit_technology_review: add keep_only_tags and remove_tags

---

recipes/handelsblatt.recipe

This is an update of the recipe for the German newspaper "Handelsblatt". Most notably, it fixes the integration of images by converting the useless `data-src` attributes to `src` attributes (which then can be handled by Calibre). It also adds new rules to remove more distracting elements and does some code cleanup.

Update Handelsblatt recipe

---

src/calibre/ebooks/html/input.py

Decoding may fail on the header chunk if the file is utf-8 encoded and the chunk ends on a continuation byte.
Not sure if this is the best solution, but it worked for me when I encountered the issue today.
Without it calibre fails with:
```
File "/usr/lib64/calibre/calibre/ebooks/html/input.py", line 120, in __init__
self.is_binary = level > 0 and not bool(self.HTML_PAT.search(header))
TypeError: cannot use a string pattern on a bytes-like object
```
for utf-8 encoded input, for which the 4096th byte happens to be a continuation byte (part of a German Umlaut in my case).

Bypass decoding errors during html detection

---

src/calibre/srv/tests/loop.py

This check broke with Python 3.5, because REQUEST_TIMEOUT changed
from being simply an integer constant to being an instance of the
new HTTPStatus enum:
https://docs.python.org/3/library/http.html#http.HTTPStatus
on Python 3.5+, `str(http.client.REQUEST_TIMEOUT)` gives
`"HTTPStatus.REQUEST_TIMEOUT"`, not `"408"`.
Simply comparing as `int` not `unicode_type` should work with all
Pythons (2, 3 before 3.5, and 3.5+). `int(REQUEST_TIMEOUT)` gives
you `408` in all cases.
This may not have been noticed till now because this check seems
to be a kind of safety valve: it seems that usually, the
`res = conn.getresponse()` call should raise `socket.timeout`
itself, and this is some sort of backstop in case it doesn't. I
caught this in Fedora Rawhide package builds: it seems that on
most arches, we …

Fix test_workers timeout response check with Python 3.5+

---

src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/tag_browser/view.py

This is a significant change to the tag browser.
Two additions:
1) right-click "rename" on an intermediate node renames that node and all the children.
2) Drag & Drop inside a hierarchical category moves the source to the target
Important behavior changes:
1) deleting an item deletes that item and now in addition all its children.
2) renaming an item renames it and now in addition all its children.
3) you can now operate on virtual intermediate nodes that aren't on any book
For #3, consider the tag "foo.bar.mumble" which is on a book. The tag browser creates
2 virtual nodes: foo and foo.bar. Before you couldn't rename and delete them. Now you can.
Before, renaming a non-virtual node with children left a new real node for the renamed node and a new virtual node for the children. There was …

Enhancement #1880264: Additional functionality for tag hierarchies

---

recipes/gazeta-prawna-calibre-v1.recipe

This patch removes obsolete 'gazeta-prawna-calibre-v1.recipe'
and adds new one gazeta-prawna-calibre-new.recipe instead
Signed-off-by: Tomasz Jozwiak <tjozwiakgm@gmail.com>

recipes: update gazeta prawna recipe

---

setup/mathjax.py

The release tarballs contain an es5/ directory with the actual mathjax code. However, when building against a system mathjax it is likely the es5/ directory is skipped and the directory name is just /usr/share/mathjax/
Detect this by moving the es5/ component to the definition of the mathjax source root, but only appending it if the --path-to-mathjax actually contains such a directory.

build: detect mathjax directory with or without es5/ subdir

---

src/calibre/devices/kobo/driver.py

No changes needed other than the firmware and database versions.

Bump supported firmware version for Kobo devices

---

src/calibre/srv/content.py

remove the '!' character from file name for downloading a kepub file from kobo browser
since kepub file with a '!' in name doesn't work on a kobo device(at least on my kobo forma)

remove '!' from filename for kobo

---

recipes/atlantic_com.recipe

Article title was missing from the text of the article.

Update The Atlantic to include article title

---

src/calibre/gui2/library/views.py

I recognize that using resizeColumnToContents when setting the column width to default gives different answers depending on when it is invoked. For me, the differences are acceptable as they settle on original behavior the next time calibre is restarted.

Add ability to save the current on-device column width.

---

src/calibre/gui2/metadata/single_download.py

When using the Download Cover feature, the thumbnail view of the downloaded covers would show covers stretched into a fixed aspect ratio. Images that are not in that standard aspect ratio are distorted, potentially making it more difficult to select one that looks good. This pull request changes it to preserve the aspect ratio of the downloaded image so that it appears as intended, accurate to how it will appear in the cover grid.

Preserve cover aspect ratio in the download preview

---

src/calibre/gui2/actions/show_quickview.py
src/calibre/gui2/dialogs/quickview.py
src/calibre/gui2/dialogs/quickview.ui

Added several operations to the quickview book and item list context menus. As a result the search button became superfluous and was removed.

Enhancement #1891765: Add operations to quickview's context menu.

---

src/calibre/ebooks/metadata/sources/douban.py

The original apikey (`0df993c66c0c636e29ecbb5344252a4a`) has been banned for a while. Detailed discussion can be found [here](https://www.v2ex.com/t/699393).
The new one (`054022eaeae0b00e0fc068c0c0a2102a`) is valid in my curl tests.
Please check the validity of a new build though.
Thanks for your efforts. 😀

Updated DOUBAN_API_KEY

---

src/calibre/utils/mdns.py

SMART_DEV (   0.24:  0.015) _startup_on_demand registration with bonjour failed
File "C:\CBH_Data\calibre.git\calibre_dev\src\calibre\devices\smart_device_app\driver.py", line 1957, in _startup_on_demand
File "C:\CBH_Data\calibre.git\calibre_dev\src\calibre\utils\mdns.py", line 168, in publish
File "C:\CBH_Data\calibre.git\calibre_dev\src\calibre\utils\mdns.py", line 149, in create_service
TypeError: __init__() got an unexpected keyword argument 'address'

Fix (I think) for exception:

---

recipes/economist.recipe

The [current edition page](https://www.economist.com/weeklyedition) doesn't contain the cover anymore. I change it to download from [the archive page](https://www.economist.com/weeklyedition/archive).

fetch the economist cover from archive page

---

src/calibre/devices/usbms/device.py

Continue the outer loop, break of the inner loop.
Else you get a `usb_dir` `NoneType` exception in `os.path.join` if there's a device without idProduct, idVendor, bcdDevice sysfs files.
```
File "/usr/lib/calibre/calibre/gui2/device.py", line 201, in do_connect
dev.open(detected_device, self.current_library_uuid)
File "/usr/lib/calibre/calibre/devices/usbms/device.py", line 809, in open
self.open_linux()
File "/usr/lib/calibre/calibre/devices/usbms/device.py", line 560, in open_linux
main, carda, cardb = self.find_device_nodes()
File "/usr/lib/calibre/calibre/devices/usbms/device.py", line 471, in find_device_nodes
ven, prod, bcd = map(e, ('idVendor', 'idProduct', 'bcdDevice'))
File "/usr/lib/calibre/calibre/devices/usbms/device.py", line 470, in …
```

Nested loop continue logic fix

---

recipes/la_jornada.recipe

This was removed in commit 735da787caf6a80272e3dcc0c21ef4946d9fd867, but I'm not sure why. It works perfectly here.

Restore cover download for la_jornada.recipe

---

recipes/la_jornada.recipe

old domain still works but it will probably stop working any day, so better to use the new one

Change cover url to new domain www.jornada.com.mx

---

resources/default_tweaks.py
src/calibre/gui2/custom_column_widgets.py

There are two changes:
1) the 'today' and 'clear' buttons for date columns are now right adjusted.
2) Labels are now fixed width. Word wrap is disabled. There are two new tweaks to
set the fixed widths for edit metadata single and bulk.

Fix enhancement #190009: Width of custom date columns.

---

src/calibre/gui2/tag_browser/view.py

1) add separate lines to expand item and expand item and children
2) add collapse lines for all parent nodes, not just the immediate parent and the category root

Make the tag browser expand and collapse menu items consistent.

---

src/calibre/gui2/__init__.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/tag_browser/view.py
src/calibre/gui2/ui.py

1) ensure that at startup the booklist gets the keyboard focus instead of quickview
2) Allow the tag browser to get keyboard focus

Two independent commits:

---

src/calibre/gui2/actions/__init__.py
src/calibre/gui2/keyboard.py

When testing different plugins in different libraries I noticed that my keyboard shortcuts in completely different plugins would sometimes disappear.  I've seen it for years.
What happens is that some plugins (Reading List, View Manager & FanFicFare at least) change what menu actions are available depending on library.  Changing _any_ keyboard shortcut discards shortcuts to menu actions that aren't visible/available in the current library.
This change preserves those shortcuts by only removing shortcuts explicitly back to 'default'.
This could conceivably cause shortcuts for removed plugins to hang around indefinitely.  But then, I thought that was a 'feature'; if you reinstall a plugin later, it still has your previous shortcuts?

Still save keyboard shortcuts to actions that aren't visible in current library.

---

src/calibre/utils/fonts/sfnt/loca.py

The tostring() method was renamed to tobytes() in Python 3.2 and has since been deprecated and removed in Python 3.9.

Replace obsolete alias tostring() with tobytes()

---

src/calibre/devices/kobo/driver.py

Wasn't checking for nulls properly, so could get an error in unusual circumstances, and also not do the update in others.
Plus a firmware version bump for an upcoming release.

Fix handling of null series index on Kobo devices

---

src/calibre/gui2/notify.py

This is part of my ongoing work at reducing the number of permissions required for the Calibre Flatpak package (likely useful for Snap too).
The new notification code is programmed to conform to the interface described at https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Notification.
As can be seen in the code, that interface does not expose the ability to set a timeout. To remedy this I set a timeout on the Calibre side and manually cancel the notification after the given number of milliseconds. **However**, practical experimentation in KDE shows that notifications submitted via this API have a default timeout of 10 seconds and display a visual cue how long it will take until they expire. Additionally, interacting with the popup (mouse-over) will …

Replace unused legacy KDENotifier with XDPNotifier for sandboxed Linux application contexts

---

src/calibre/linux.py

Changes to the generated AppStream XML files:
* Added OARS (Open Age Rating Service) metadata
* Added release history to the main Calibre GUI AppStream file based on the contents of `Changelog.yaml` with a layout similar to that on the website
These changes combined make the generated main AppStream file pass the `appstreamcli validate` check, reducing the need to patch it downstream.
(By product of the work at https://github.com/flathub/com.calibre_ebook.calibre/pull/53.)

Improve Linux/XDG AppStream file generation

---

src/calibre/gui2/tag_browser/view.py

If required (in a VL) ask the user whether to apply the rename in the entire or virtual library.

Re-enable the edit keys in the tag browser.

---

src/polyglot/plistlib.py

plistlib.Data is deprecated from Python 3.4 and fully removed in Python
3.9.
Skimming over the code, it's look like nothing uses this data structure.
Let's remove it.

polyglot: don't try to import plistlib.Data

---

src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/tag_browser/view.py

For the record:
1) When the option to give the tag browser focus is enabled:
- Clicking on the tag browser should always give it focus, even if a
node is toggled in the process
- Toggling a node should not give the focus back to the library view
2) When the option to give the tag browser focus is disabled:
- Clicking on the tag browser should never give it focus, and the
shortcut to give it focus should have no effect.

Tag browser focus changes discussed in other PR.

---

src/calibre/utils/network.py

Like #1268, but for the other D-Bus API that can be trivially be converted to a sandbox compatible alternative.

Use and prefer XDP interface for checking for network online status

---

recipes/folhadesaopaulo_sub.recipe

Hello!
I have updated recipe for Folha de São Paulo to actual syntax. Somethings got changed from original:
* First version supported only UOL (SSO Auth from Folha's owner) and not Folha authetication. Now, due to UOL auth changes to a JavaScript dependent schema for base auth and password hash, only Folha authentication got supported
* I did a separation only for main sections and their articles because I do not know if Calibre supports subsections. Original script already did like this, but its a noticeable information.
This PR closes https://bugs.launchpad.net/calibre/+bug/1905334
Is this PR able to be merged?

* Update Folha de Sao Paulo for 2020 syntax

---

src/calibre/utils/icu.c
src/calibre/utils/matcher.c

ICU stopped defining the macros FALSE and TRUE in its headers with 68:
https://github.com/unicode-org/icu/commit/c3fe7e09d844

Fix build with ICU >= 68

---

recipes/substack.recipe

This recipe uses the RSS feeds which Substack provides for each newsletter. Unlike the built-in RSS recipe, this one also lets Calibre download all posts from your paid subscriptions.
If you don't add a username and password, it will work exactly like the built-in recipe.

Recipe for Substack newsletters

---

src/calibre/ebooks/oeb/polish/upgrade.py

- Don't remove toc property from spine element, when keeping the NCX file

Fix removal of toc reference in spine element

---

recipes/economist.recipe

A new function edition(date) allows the user to specify a past edition. The default, date='', takes the current edition. The proper cover URL appears in the Calibre desktop app, though not on Kindle Oasis -  a minor remaining issue. Much respect and admiration for Kovid Goyal's work.

Get a past edition of the Economist (e.g., date='2020-11-28').

---

src/tinycss/tests/tokenizing.py

There is a small typo in src/tinycss/tests/tokenizing.py.
Should read `special` rather than `specal`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, specal -> special

---

src/calibre/gui2/dialogs/saved_search_editor.py
src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/view.py

Because it is useful I decided to continue to permit hierarchy for saved searches even though behavior will be a bit strange.
The following behaviors exist and will not be changed.
- Renames will not rename all items in the the hierarchy.
- Intermediate nodes that aren't 'real' searches will not offer the rename option.
- Drag & drop is disabled.
In addition I changed the behavior of "Add search" in "Manage saved searches". It used to act like a rename if the target name already exists, throwing away the old search expression. It now refuses.

Fix for Bug #1909738: Strangeness with hierarchical searches

---

src/calibre/gui2/tag_browser/view.py

The := operator was introduced in python 3.8. I don't think making calibre incompatible with previous python versions is worth the use of the new operator here.
FreeBSD at least uses python 3.7 by default and this would cause problems in providing calibre to users, and require them to custom compile software to get it.
I can also patch it locally on FreeBSD ports tree but I'd rather have this patch accepted.
The := operator was introduced in a2411ef0a0f3517ae06a509000561c90168a10fa

Use python 3.7 compatible syntax.

---

recipes/mediapart.recipe

As mentioned in this previous PR: https://github.com/kovidgoyal/calibre/pull/1333
I find a way to fix the problem of disappearing covers for Mediapart in the Kindle menu (a redimension of the image to a portrait format and a change of the cover from .png to .jpeg)

fix Mediapart covers disappearing in Kindle menu

---

recipes/mediapart.recipe

Hi @kovidgoyal ,
Another PR on my side. This one is not finished yet. I wanted to ask you if there is an easy way to add the date on the Cover image. 
I saw that something like that exist in the `default_cover` function and I was wondering if you could help me implement it. 
Right now the cover_url is https://raw.githubusercontent.com/lhoupert/calibre_contrib/main/mediapart.jpeg
I would like to display the date in bottom part of the image (above the pixel 250 of the bottom).

cover update2

---

recipes/mediapart.recipe

Hi @kovidgoyal  I didn't finish the previous PR. I wanted to add information about the weekday and the time on the cover. This new PR should fix that see the results below:
The test may be failing like previously. It may be due to Qt Alignment? I got a depreciation warning on my computer:
```
qp.drawText(r, Qt.AlignmentFlag.AlignJustify | Qt.AlignmentFlag.AlignVCenter | Qt.AlignmentFlag.AlignCenter, date)
test_print_cover_img.py:62: DeprecationWarning: an integer is required (got type Alignment).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
```

add edition on cover

---

recipes/mediapart.recipe

After adding timezone information to display the "french time" on the cover. I forgot to add timezone information on the `article_date` variable which is parsed from the website.
The date check was failing and no article was added in the feeds. Now everything should work fine.

[recipe - Mediapart] fix bug in article date-check 

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_dialog.ui
src/calibre/gui2/dialogs/template_dialog_box_layout.py
src/calibre/gui2/preferences/template_functions.ui

1) Make the dialog scrollable.
2) Add rows where a developer can put more fields while maintaining alignment.
3) Allow passing in a dictionary of formatter functions, allowing the developer to temporarily add new functions.
4) Adjust some sizes to make the dialog scroll more nicely

Improvements to the template editor dialog

---

src/pyj/read_book/shortcuts.pyj
src/pyj/read_book/view.pyj

Add a shortcut option for syncing last position and annotations. The option is only added for non-standalone viewer mode since book syncing only applies there. No default binding is assigned.
----------------
Testing done:
This is my first time contributing to calibre, so apologies in advance if I missed anything.
In terms of code, I'm actually not sure if importing and using `globals.runtime` is the right way to go here. Having callsites pass in a `is_standalone_viewer` argument to `shortcuts_definition` is potentially cleaner - and if we do that we can also merge `add_standalone_viewer_shortcuts` and `shortcuts_definition`. Let me know if you want me to make that refactor instead.
Thank you for your hard work on calibre!

E-book viewer: Add shortcut option for syncing

---

src/calibre/ebooks/metadata/sources/search_engines.py

The certificate is corrected by now:
```
* Server certificate:
*  subject: CN=cc.bingj.com
*  start date: Jan 19 01:42:44 2021 GMT
*  expire date: Jul 19 01:42:44 2021 GMT
*  subjectAltName: host "cc.bingj.com" matched cert's "cc.bingj.com"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft RSA TLS CA 01
*  SSL certificate verify ok.
```

restore HTTPS when accessing cc.bingj.com

---

src/calibre/gui2/ui.py

Em dash is a more visible and more beautiful separator that also looks more native on systems like macOS. A number of applications have switched to using em dash as window title separator, including Firefox, VS Code, and Wireshark. 
See the discussion here: https://bugzilla.mozilla.org/show_bug.cgi?id=1279647

Use an em dash to separate window title fragments

---

.github/workflows/ci.yml
.github/workflows/translations.yml

The container runs successfully now.
Switching off of the "base" container reduces the runtime by 20s. The old one is frozen and does not get updated, so it has to do tons of updates.

ci: remove glibc workaround

---

src/calibre/gui2/device.py

The bug seems limited to fetching device information during processing of device.DeviceSignals.device_connection_changed(False)

Bug #1919128: Template: Sometimes returns device name after eject.

---

src/calibre/gui2/device.py

The previous fix didn't work for programmatically ejected unmanaged and standard devices

More Bug #1919128: Template: Sometimes returns device name after eject.

---

manual/template_lang.rst
src/calibre/utils/formatter.py

$authors is the same as field('authors'). $$pubdate is the same as raw_field('pubdate').

Add field references to the language syntax.

---

recipes/economist.recipe
recipes/economist_free.recipe

The `economist_free.recipe` file is for backward compatibility and it can't be a symbolic(or hard) link?

get the economist cover url from json

---

src/calibre/gui2/widgets2.py

Apologies for not checking this before the last commit.

Fix the color for separators wrong in dark mode.

---

setup/install.py

options for Develop() are not automatically added to Install(), so the new option in commit 8fb6d5f37e8055ce720bd0b1d56587f88c0071f285966ba17e72b2b12672aa73 only worked for the former. And since consolidate_paths unconditionally checked opts.system_plugins_location, trying to run an ordinary install ended in:
```
File "/build/calibre-git/src/calibre/setup/install.py", line 117, in consolidate_paths
self.system_plugins_loc = opts.system_plugins_location
AttributeError: 'Values' object has no attribute 'system_plugins_location'
```

setup: fix installing without develop mode + system plugins option

---

recipes/guardian.recipe

Images were scaled to 100% height/width. Fixed by removing CSS.
Before: https://imgur.com/a/2VG9W7E
After Patch: https://imgur.com/a/DgUhS9G

Fix Guardian Recipe CSS: Images are distorted

---

src/calibre/db/cache.py
src/calibre/db/search.py
src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/tag_browser/view.py

The actual fix is in cache.py line 2218. Another change added the virtual fields to vl:x searches. The rest are improvements to error messages.

Bug #1924247: Possible to create recursive VL that crashes Calibre

---

resources/default_tweaks.py
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py

- Fix a serious regression breaking calling stored templates introduced on 12/4. This easily could be serious enough to provoke an interim release. Apologies.
- Add a tweak to set the tab stop width in the template editor.

Two commits: 

---

setup/arch-ci.sh

This reverts commit b8d8cf27e290f75791679cb3bce3f250904f2367.
libraqm (an obscure PIL functionality) was recently switched to be directly linked by Pillow, rather than dlopened, which meant it was a bit of a hidden dependency since calibre uses the imagingft module. But it is now directly depended on by the Arch packaging, so it no longer needs to be installed to get a functional Pillow.

Revert "Fix building on Arch"

---

src/calibre/gui2/store/stores/gutenberg_plugin.py

Collected works may lack the author name field, and its HTML div. This
interrupted the search results processing.
For example, searching on title or author using "erasmus" yielded no or
two results out of 25 max.
- Title search now works as expected.
- Author search omits discussed results. Apparently at a later stage a
match is required between 's.author' and the query.

Fixed Gutenberg-store search issue (missing author names)

---

src/calibre/ebooks/metadata/mobi.py

This pull request adds two features:
1. Save ASIN from EXTH header to the 'mobi-asin' metadata.
2. Save ASIN to EXTH headers if the book's metadata has 'mobi-asin' record, this can be used by plugins to update a book's ASIN for Word Wise and X-Ray.

Add ASIN to MOBI EXTH header and metadata

---

src/calibre/linux.py

This fix provides proper "lang" attribute in "description" tag.

Fix AppStream warnings in metainfo file

---

manual/template_lang.rst
src/calibre/gui2/dialogs/smartdevice.ui
src/calibre/utils/formatter_functions.py

1) Remove "Currently used only by calibre companion" from the wireless device connection setup dialog. This is no longer true.
2) New formatter function 'date_arithmetic' that simplifies computing a new date from an existing one

Two independent commits

---

src/calibre/devices/kobo/driver.py

Adding device ids, strings and cover details for the new Elipsa device. Firmware version is still to come, but, this will allow the device to be recognised.
And added an extra line to the new firmware version warning message pointing to the Kobo forum.

Add support for Kobo Elipsa

---

recipes/hindu.recipe

Summary:
* Fix: loading lead image of articles
* Fix: avoid duplicating of subheading
* Add: article summary to show up in TOC
Explanation:
The lead image markup seems to have changed since the last edit to this
recipe. Hindu now uses a `<picture>` element with a placeholder <img> and
the actual URL in many `<source>` tags. All img's with `data-src-template`
now lie outside the included tags of the soup (the removed for loop was
having no effect).
Articles contain identical `h2.intro` tags at two different places. Only
one is displayed on the website based on screen size, but the recipe is
including both, making subheadings appear twice.
Even for articles without an `h2.intro` tag, a summary is present in the
standard meta tag; enough for a more informative table of contents (e.g. …

Fix & improve The Hindu recipe

---

src/calibre/ebooks/pdb/haodoo/reader.py

It was broken before because the comparison on line 94 would compare header.ident (a unicode string) to BPDB_IDENT (a byte string), which is not comparable in python3.

Fix haodoo reader to properly pick encoding in python3

---

recipes/hindu.recipe

* Remove redundant date and timestamps cluttering every article
* Place intro immediately beneath the heading, as in print edition
- duplicate intro is now removed using CSS
* Visual styling

Recipe: make Hindu better resemble print edition

---

src/pyj/read_book/paged_mode.pyj

Before, pageup failed when the page margins were greater than half the
screen width, because previous_screen_location() went backward by
screen_inline, which did not account for the margins but worked most of
the time due to later rounding. Now this has been fixed.
Signed-off-by: Morgan Seltzer <MorganSeltzer000@gmail.com>

Fixed Pageup Occasionally Failing

---

src/calibre/gui2/throbber.py

It is no longer possible to pass floats to C functions where ints are expected, so explicitly convert to int in this case.

Fix ThrobbingButton init with Python 3.10

---

src/calibre/gui2/__init__.py
src/calibre/gui2/library/alternate_views.py
src/calibre/gui2/store/search/results_view.py

These currently raise deprecation warnings, but will no longer get autoconverted in python 3.10
- Some Qt functions expect int, not float, and got truncated automatically.
- The QSocketNotifier is sip.voidptr wrapping an int file descriptor

python 3.10: explicitly cast some numbers to int

---

src/calibre/utils/formatter.py

The problem: recursion triggered by field references of composite columns changed the state of the 'calling' interpreter.

Bug #1933591: Possible column template bug: Unknown identifier.

---

src/calibre/gui2/preferences/main.py

In commit 06847efbeef3fc52501222f8d7afcb19f9d853f2 the init_dbus function got removed due to not being needed in jeepney. But it still got imported and run in a manually launched `__main__` test.

remove references to deleted dbus code

---

src/calibre/ebooks/metadata/xmp.py

A pdf contains xmp data like this:
```xml
<dc:creator>
<rdf:Seq>
<rdf:li>A</rdf:li>
<rdf:li>B and C</rdf:li>
</rdf:Seq>
</dc:creator>
```
This kind of less rigorous xmp data may cause a bug in calibre.
After add this book to db. I found:
- authors field in `books` table is `['A', 'B and C']`
- author in `authors` table is `['A', 'B', 'C']`
And the inconsistency can make this book **added multiple time without triggering duplicate**.
The `MetaInformation` to insert into `books` table is directly  provided by pdf plugin. But each author form  `MetaInformation` will process by [string_to_authors][] again before being inserted into `authors` table. See [calibre/cache.py#L1418](https://github.com/douo/calibre/blob/f6517cc81888fba2ddb668b6414cae177c25b77d/src/calibre/db/cache.py#L1418).
if …

Split author field in xmp author metadata to keep consistency

---

src/calibre/ebooks/conversion/config.py

https://bugzilla.redhat.com/show_bug.cgi?id=1922761 reports the following
failure:
```
File "/bin/ebook-edit", line 20, in <module>
sys.exit(ebook_edit())
File "/usr/lib64/calibre/calibre/gui_launch.py", line 119, in ebook_edit
main(args)
File "/usr/lib64/calibre/calibre/gui2/tweak_book/main.py", line 98, in main
_run(args)
File "/usr/lib64/calibre/calibre/gui2/tweak_book/main.py", line 66, in _run
from calibre.gui2.tweak_book.ui import Main
File "/usr/lib64/calibre/calibre/gui2/tweak_book/ui.py", line 29, in <module>
from calibre.gui2.tweak_book.boss import Boss
File "/usr/lib64/calibre/calibre/gui2/tweak_book/boss.py", line 28, in <module>
from calibre.ebooks.oeb.polish.main import SUPPORTED, tweak_polish
File …
```

conversions: use makedirs(exist_ok=True)

---

setup.py

A tuple comparison is equivalent to the more complicated check,
and exit() is the same as raise SystemExit().

setup: simplify version check

---

manual/customize.rst

And while we are at it, add a simple disclaimer that plugins and themes are not part of calibre and support for them is handled externally via their support threads.

manual/customizing: reword intro, mention that plugins can be shared

---

src/calibre/devices/eb600/driver.py

The new device uses Kobo vendor id. Also, show the names for this and the epos.

Add vision 6 to tolino driver

---

recipes/el_pais.recipe

The recipe works again after these changes, the current recipe only process the headline and subheadline correctly.

Make El Pais recipe work with redesigned site

---

recipes/readitlater.recipe

Hi! :wave: I think this is my first time interacting with this project, so there's a chance I might've missed something.
This recipe wasn't working (at least for me), where it would consistently fail with the following error when trying to download an article:
```
File "calibre/utils/threadpool.py", line 100, in run
File "calibre/web/feeds/news.py", line 1186, in fetch_obfuscated_article
File "<string>", line 157, in get_obfuscated_article
File "<string>", line 142, in get_textview
File "re.py", line 201, in search
TypeError: expected string or bytes-like object
```
I believe this is because Pocket don't allow access to their "Article View" API by default:
https://getpocket.com/developer/docs/v3/article-view
This change uses the original URL of the …

Fix Pocket/readitlater recipe

---

src/calibre/gui2/proceed.py

In the same vein as https://github.com/kovidgoyal/calibre/pull/1461/, need to explicitly cast to int before the value is passed in to Qt to prevent a TypeError with py310.
Addresses https://bugs.launchpad.net/calibre/+bug/1954708

py310 support: explicit cast to int

---

src/calibre/gui2/metadata/basic_widgets.py

Not sure why I had excluded the slash as a valid character in the identifier. There are a few sites that do this.

Don't exclude slashes when parsing URLs for identifier rules

---

src/calibre/srv/loop.py

This is similar to: https://github.com/redis/redis-py/pull/1797
Currently, calibre/srv/loop.py's `Connection.close()` won't continue to close the socket if it encounters an `OSError` on `socket.shutdown`. An `OSError` can happen on `socket.shutdown` if the other side of the connection disconnected already. Not running `socket.close` prevents garbage collection from cleaning up the socket and will use more memory than necessary (maybe even causing a leak?).
This PR puts a separate try/except around `socket.close` and `socket.shutdown` to allow the socket to be closed after a failed shutdown.

close Connection socket after server disconnect

---

src/calibre/gui2/preferences/look_feel.py

This isn't the requested fix, which I am not going to do. Instead it extends the number of books in the test section of the template dialog from 1 to all selected.

Enhancement 1956007: cc_icons dropdown in Template Tester.

---

resources/mime.types

Current XCF media type is `image/x-xcf` .
See also:
Re: [Gimp-developer] Mime type application/x-xcf in /etc/mime.types vs image/x-xcf in gimp.desktop
https://mail.gnome.org/archives/gimp-developer-list/2021-July/msg00001.html

media-types: use image/x-xcf rather than application/x-xcf to match gimp.desktop

---

recipes/equestria_daily.recipe

The website https://www.equestriadaily.com/ often uses images in its articles, and from what I have seen the images get compressed so much that text is basically unreadable on them.
This fix mitigates this issue by reducing the compression factor from 16 to 4, which slightly increases the size of the newspaper but makes it more enjoyable and readable.

Reduce image compression in equestria_daily recipe

---

recipes/respekt_magazine.recipe

I tried to run the recipe today and I would get this error 
```
calibre, version 5.35.0 (linux, embedded-python: True)
Conversion error: Failed: Fetch news from Respekt Magazine – Print
Fetch news from Respekt Magazine – Print
Conversion options changed from defaults:
verbose: 2
output_profile: 'kindle'
Resolved conversion options
calibre version: 5.35.0
{'asciiize': False,
'author_sort': None,
'authors': None,
'base_font_size': 0,
'book_producer': None,
'change_justification': 'original',
'chapter': None,
'chapter_mark': 'pagebreak',
'comments': None,
'cover': None,
'debug_pipeline': None,
'dehyphenate': True,
'delete_blank_paragraphs': True,
'disable_font_rescaling': False,
'dont_compress': False,
'dont_download_recipe': False,
'duplicate_links_in_toc': False,
'embed_all_fonts': False, …
```

Fix 308 error that started appearing today

---

src/calibre/db/backend.py
src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui

1) Ensure the height of a widget doesn't grow in two column mode.
2) Add an option to ignore the column selection and order specifications.
See the tooltip for the option for the justification.

Two changes to edit metadata custom columns:

---

src/calibre/gui2/preferences/coloring.py

I added some info on the difference between "with text" and "without text" icons, as I couldn't understand the effect that option had before testing it

Update Column icons tooltip information

---

resources/default_tweaks.py
src/calibre/gui2/__init__.py
src/calibre/gui2/custom_column_widgets.py
src/calibre/gui2/metadata/single.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui

They are:
- 2 column mode in the default single edit
- The 4 tweaks for eliding custom column labels

Migrate the remaining edit metadata tweaks to gprefs.

---

recipes/japan_times.recipe

I have made an improved version of the recipe.
I removed the Javascript message, as well as the bullet points after the title and the "Related" section at the bottom of the article, just leaving the main text. I could not, however, keep the article author's name.
I set a masthead URL so we get the logo at the top of the Sections menu and fixed the feed URLs (there were http instead of https URLs, as well as the Life feed being wrongly set to the Opinion feed URL. I added the Top Stories feed, too.

Recipes - Fix and improve Japan Times recipe

---

src/calibre/gui2/actions/mark_books.py

After using it for a bit it I think it makes more sense to put the latest value into the combo box and show up to 4 older values in the buttons. This allows reusing the latest value by pressing return and doesn't duplicate values.

Mark w/text: Change the way history is shown in the buttons.

---

recipes/economist.recipe
recipes/economist_free.recipe

the "image" value could be null, for example: https://www.economist.com/special-report/2022/04/20/sources-and-acknowledgments

Fix The Economist recipe NoneType is not iterable error

---

src/calibre/devices/kobo/driver.py

Drop the database version for the new bookstats feature in the released firmware 4.32.19501 as a change was removed by Kobo at the last minute.
Also commented out some logging related to this change that I missed with the original checkin.

Reduce dbversion for Kobo Bookstats

---

src/calibre/gui2/actions/mark_books.py

1) Don't accept blanks as a text label
2) Show only the first 40 labels in the "Show marked with text" submenu. Some plugins define thousands of labels.

Two changes to the new marked stuff:

---

recipes/queueacmorg.recipe

Retain the magazine RSS feed and remove the rest of the feeds which have not been updated in many years.

Update ACM Queue recipe

---

src/calibre/db/view.py
src/calibre/gui2/library/views.py

1) The listeners weren't called if only labels changed in the is_marked set.
2) refresh_ids returned no rows if any one of the ids was invalid.
3) I used the wrong method in views.py. I have ids but called the method that expected rows.

Fix some problems with the new marking code.

---

src/calibre/devices/kobo/driver.py

Missed a check in determining if collection management should be done.
And Kobo have released another firmware versions. No changes are needed to support it.

Missed change for collections template and bump firmware version

---

recipes/nature.recipe

The recipe was returning the error below. Also improved the article extraction with changes to `keep_only_tags`/`remove_tags`.
```
File "runpy.py", line 194, in _run_module_as_main
File "runpy.py", line 87, in _run_code
File "site.py", line 39, in <module>
File "site.py", line 35, in main
File "calibre/ebooks/conversion/cli.py", line 419, in main
File "calibre/ebooks/conversion/plumber.py", line 1108, in run
File "calibre/customize/conversion.py", line 242, in __call__
File "calibre/ebooks/conversion/plugins/recipe_input.py", line 137, in convert
File "calibre/web/feeds/news.py", line 1056, in download
File "calibre/web/feeds/news.py", line 1225, in build_index
File "<string>", line 68, in parse_index
AttributeError: 'NoneType' object has no attribute …
```

Fix recipe for nature.com

---

recipes/economist.recipe
recipes/economist_free.recipe

The economist website changes the `a` tag class name to random string. The current recipe can only download three articles.

Get articles data from json

---

manual/develop.rst

This adds two things to documentations:
1. Links to installers (I picked the non 64bit version for Windows)
2. Clarifying and emphasazing that one needs to use package used by upstream to use CALIBRE_DEVELOP_FROM, not the package provided by distribution
See also here: https://www.mobileread.com/forums/showthread.php?t=294791

Clarifies which Linux package to use

---

src/calibre/web/feeds/news.py

I think this should appear here: https://manual.calibre-ebook.com/news_recipe.html so documenting it.

Document publication_date

---

src/calibre/web/feeds/news.py

As discussed here: #1642 (comment), this makes the title in a recipe use the date when a given publication was issued (if set by a recipe) instead of current time.

Use proper date in recipes

---

recipes/economist.recipe

A follow up to this https://github.com/kovidgoyal/calibre/pull/1665 that implements this for the Economist.

￼ Use publication date in title instead of current date

---

recipes/new_statesman.recipe

Updates the URL for the New Statesman RSS feed found at https://www.newstatesman.com/rss-feed

Update New Statesman RSS feed URL

---

src/calibre/ebooks/metadata/opf2.py

While trying to investigate a bottleneck with calibredb I noticed that the same file was being accessed twice:
```
13:44:07 access("/opt/calibre-book-box/B07BZBWSKN.jpg", R_OK) = -1 ENOENT (No such file or directory)
13:44:07 access("/opt/calibre-book-box/B07BZBWSKN.jpg", R_OK) = -1 ENOENT (No such file or directory)
```
It seems a bug in guess_cover was causing it to return os.access(path) instead of just the path.

opf2.py's OPF.guess_cover doesn't return the path

---

resources/calibre-mimetypes.xml

Assume the required version of shared-mime-info is 1.8, which seems to
be a good low-enough baseline according to:
https://repology.org/metapackage/shared-mime-info/versions
(e.g. CentOS 7, Debian 9)
This makes it possible to drop the definition of `application/epub+zip`,
provided by newer versions of shared-mime-info (and with more details
than this removed definition).

Assume shared-mime-info 1.8

---

manual/gui.rst
src/calibre/gui2/dialogs/search.py
src/calibre/utils/search_query_parser.py
src/calibre/utils/search_query_parser_test.py

1) Add a docstring syntax to the search query parser. """text""" uses text unchanged without escape processing.
2) Add tests for docstrings.
3) Update the search section of the manual.
4) Change the advanced search dialog to use docstrings for template searches.
5) Pass some books to the template dialog in advanced search to help with debugging template searches.

Several interlocking changes:

---

src/calibre/gui2/pyqt6_compat.py

My EpubSplit plugin uses `menu.exec_(self.mapToGlobal(event.pos()))` which starting throwing:
```
TypeError: exec_() takes 1 positional argument but 2 were given
```
`pyqt6_compat.py` restored `exec_()` (thanks for that) but not with arguments.  This change allows for arguments.

Pass variable args to back compat method exec_()

---

src/calibre/devices/nook/driver.py

New ID update for glowlight  2021 to distinguish different ebook hardware.

Barnes & Noble NOOK model type update.

---

format_docs/pdb/ereader.txt
format_docs/pdb/mbp.txt
format_docs/pdb/mobi.txt
format_docs/pdb/pdb_format.txt
format_docs/pdb/pml.txt
format_docs/pdb/ztxt.txt
format_docs/rb.txt
src/calibre/ebooks/rtf2xml/char_set.py
src/calibre/ebooks/rtf2xml/field_strings.py

Typos in format_docs/ and src/calibre/ebooks/rtf2xml

Fix leftover typos

---

src/calibre/devices/kobo/driver.py

For this firmware version, Kobo bumped the database version but for the firmware version, they only changed the build number.

Update Kobo database version for new firmware

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_dialog.ui
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

1) Correct an error message.
2) Inline the switch() function for performance.
3) Add a tooltip explaining that an advanced template can create a compound icon by separating the file names with colons

Three changes to the template system.

---

src/calibre/ebooks/oeb/transforms/rasterize.py

I ran into this problem when converting an epub book into mobi, the error messages are as attached
```
Convert book 1 of 1 (经济学原理(第7版)微观经济学分册)
Conversion options changed from defaults:
read_metadata_from_opf: '/var/folders/fl/bh95gz354ts78xfyq9wl4t4m0000gn/C/calibre_6.1.0_tmp_4jar7646/c4r4o_m2.opf'
output_profile: 'kindle_pw3'
cover: '/var/folders/fl/bh95gz354ts78xfyq9wl4t4m0000gn/C/calibre_6.1.0_tmp_4jar7646/247_972b.jpeg'
verbose: 2
Resolved conversion options
calibre version: 6.1.0
{'asciiize': False,
'author_sort': None,
'authors': None,
'base_font_size': 0.0,
'book_producer': None,
'change_justification': 'original',
'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
"'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
"'i')) or @class = …
```

fix a potention bug of unexpected type 'float'

---

recipes/mediapart.recipe

Pages structure is not the same depending on source types : adding workarounds to perform a second search to get articles.

Fix Mediapart site changes

---

src/calibre/gui2/icon_theme.py

Click "Restore default icons" before icon themes loaded will cause an error.

Check `themes` attribute exists before using it

---

bypy/sources.json

This will fix [template with C linkage](https://github.com/brailcom/speechd/issues/616) error when compiling from source.

Bump speech dispatcher version from 0.10.2 to 0.11.1

---

src/calibre/customize/builtins.py
src/calibre/gui2/actions/manage_categories.py
src/calibre/gui2/tag_browser/ui.py

There are two requests here.
1) Add apply button. Because the work is done after the dialog has closed, changing this is more work than I am willing to do.
2) Add toolbar / shortcut / context menu support for Manage categories. Done.

Enhancement 1984017 - Add Apply button to Manage Tags

---

src/calibre/db/categories.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/tag_browser/model.py
src/calibre/srv/metadata.py

1) Ensure that the server displays columns added using the command line.
2) Make "official" the fact that get_categories returns an ordered dict.
While in the process, move the general methods category_display_order and is_standard_category from the gui to db.get_categories().
Finally, improve the tooltip for L&F / Tag browser / hierarchical items

Changes to improve robustness:

---

src/calibre/gui2/dialogs/quickview.py
src/calibre/gui2/preferences/look_feel.py

It worked without this fix, at least on Windows. Better to make it right, though.

enum fix: Qt.DisplayRole => Qt.ItemDataRole.DisplayRole

---

resources/default_tweaks.py

The default tweaks **per_language_title_sort_articles['fra']** contained an incorrect value that caused **L’** to be duplicated, but **D’** is missing.

Fix: Incorrect value in the default tweaks per_language_title_sort_articles['fra']

---

manual/template_lang.rst
src/calibre/utils/formatter_functions.py

Following a [little discusion](https://www.mobileread.com/forums/showthread.php?t=348976) with @cbhaley, here is the implementation of a string comparator case-sensitive.
Although it is a marginal case, providing a build-in function would be useful and will be complementary the default behavior of calibre.

Add strcmpcase() to template language

---

manual/template_lang.rst
src/calibre/utils/formatter_functions.py

Following a [little discusion](https://www.mobileread.com/forums/showthread.php?t=348976) with @cbhaley, here is the implementation of a string comparator case-sensitive.
Although it is a marginal case, providing a build-in function would be useful and will be complementary the default behavior of calibre.
Second Pull, due to mistakes on my part.

Add strcmpcase() to template language [2]

---

src/calibre/devices/kobo/driver.py

Unfortunately Kobo slipped a new f/w version out; the driver currently lists it as unsupported. Only change required was a constant

Update supported f/w version for new release

---

src/calibre/gui2/actions/booklist_context_menu.py
src/calibre/gui2/library/views.py

1) add a dialog to set the width without using the mouse.
2) Change the name from "Book list context menu" to "Book list header menu" to avoid confusion with the context menu on book list cells.

More accessibility changes related to the book list header context menu:

---

src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/view.py

1) Fix child categories not displaying if the parent category doesn't exist.
2) Ensure that only the top most user category in a hierarchy can be hidden.

Two bug fixes involving user categories:

---

src/calibre/utils/formatter.py

The Python template can return a value other than a string.
If the call of the template is done without strip the result, the invalid value is returned without raising an error.

ensure that the Python template returns a string

---

src/calibre/gui2/init.py

When your "unlock the tabs", calibre assumes that the 'All books' tab is always on the left, when it is not necessarily the case.
Bug 1: Close button on 'all book' tab
Bug 2: No close button on a virtual library tab that can be closed

When "unlock tabs" no close button for 'all book'

---

src/calibre/db/view.py
src/calibre/gui2/library/alternate_views.py

See https://www.mobileread.com/forums/showthread.php?p=4265937#post4265937 for an explanation.
The "exotic" part is changing _map_filtered to a property with a setter. The setter constructs a dict {book_id:row}. view.id_to_index() uses the dict instead of .index on the list.

Two performance improvements related to large libraries.

---

format_docs/pdb/mobi.txt
src/calibre/ebooks/pml/pmlml.py
src/calibre/ebooks/rtf2xml/preamble_div.py
src/pyj/read_book/tts.pyj

Found via `codespell -q 3 -S./Changelog.*,./resources/dictionaries  -L alo,ans,pard,ro`

Fix various typos

---

src/calibre/customize/builtins.py
src/calibre/gui2/actions/saved_searches.py

The action can be triggered by a toolbar button, a shortcut, or on the booklist context menu.

Add an action to show saved searches in a menu.

---

src/calibre/gui2/actions/manage_categories.py
src/calibre/gui2/actions/saved_searches.py
src/calibre/gui2/dialogs/saved_search_editor.py
src/calibre/gui2/layout.py
src/calibre/gui2/search_box.py

- Add some "manage" actions to the saved searches menu
- Make the saved search button on the search toolbar and the saved searches action use the same menu
- Change some of the icons to use the existing dedicated saved search icons.
- Display the menu under a toolbar action or a menu action if either exists. **NB: I don't know if displaying under a menu works on a Mac or Linux**
- Make manage categories and saved searches use the same code to place the menu on the screen.

Several things related to saved searches:

---

resources/default_tweaks.py
src/calibre/gui2/__init__.py
src/calibre/gui2/bars.py
src/calibre/gui2/layout.py
src/calibre/gui2/preferences/search.py
src/calibre/gui2/preferences/search.ui
src/calibre/gui2/preferences/toolbar.py
src/calibre/gui2/search_box.py

Given that the saved searches action and the saved search button on the search bar now do the same thing, it seems reasonable to allow the user to choose whether the saved search button shows. I went from there to "Why not allow adding other buttons to the bar?" There is a lot of available real estate on that bar. This commit does that using a new toolbar in preferences / toolbars.
I didn't use a QToolBar, instead constructing a 'classic' toolbar in an QHBoxLayout. That gave me more control over the look and placement. And also, I had no end of trouble trying to work through how to use a QToolBar that isn't attached to a QMainWIndow.
In the process I removed the legacy Saved Search combo box, its associated buttons, and the tweak. I am sure there are some people still using the years-old …

Make tools on the search bar customizable.

---

src/calibre/gui2/actions/booklist_context_menu.py
src/calibre/gui2/actions/manage_categories.py
src/calibre/gui2/actions/saved_searches.py
src/calibre/gui2/bars.py
src/calibre/gui2/preferences/search.py
src/calibre/gui2/search_restriction_mixin.py

- Bug #1993574: virtual libraries don't work
- Update the search bar when closing the search preferences window.
- and one to deal with your comment.
Re:
The buttons on the search bar dont behave like they do in the toolbars.
Clicking on a button with a menu pops up the menu but does not perform
the action. And right clicking on them has no effect. This will be
confusing and a source of bug report noise. So maybe if the action has a
menu, have it open on right click only, depending on popup_type in the
action definition.
This problem arose because my code for keyboard shortcuts in Saved searches and Manage categories didn't work if the buttons on the search toolbar had menus. The popup menu appeared in some seemingly random spot. Of course it wasn't random, but ... I fixed it by changing …

Three commits:

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter.py

On a breakpoint open a dialog displaying variables in the template's frame.
Also indicate when the debugger is waiting for the 'Go' button. This fixes problems when people don't notice they have checked the Enable breakpoints box.

Template debugger: Add breakpoints for python templates. 

---

bypy/linux/site.py
bypy/macos/site.py
bypy/windows/site.py

This pull request fixes the `module 'site' has no attribute 'USER_SITE'` error when run pip in calibre's embedded interpreter.
Fixing this error would enable plugins to install packages compatible with calibre by running command like this:
```
calibre-debug /usr/lib/python3.10/site-packages/pip/__pip-runner__.py -- -t install_path package_name
```

Add `USER_SITE` to site.py to fix error in pip

---

src/calibre/gui2/custom_column_widgets.py

Clicking clear on DateTime setting the apply box is wrong. Fixed.

[Bug 1996020]:  Bulk Metadata Editor: Inconsistency on 'Clear' button

---

src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/view.py

Changed saved search nodes generated by walking a hierarchy to do nothing when clicked and to have an appropriate tooltip. Also removed the search icon for these saved search nodes, since they aren't searches.

Bug #1996559: Saved Search: Renamed saved search oddities

---

src/calibre/gui2/preferences/search.py
src/calibre/gui2/tag_browser/view.py

There are two independent problems here.
1) The exception is caused by right-clicking in the white space of the tag browser. I can't make it happen right-clicking anywhere else. It has nothing to do with grouped searches.
2) The "creation of grouped search terms" problem has been there since forever. The search preferences didn't tell the tag browser to completely rebuild the tree. Restarting calibre fixed it.

Bug(s) #1997137: Tag browser error.

---

src/calibre/gui2/actions/choose_library.py
src/calibre/gui2/dialogs/check_library.py
src/calibre/library/check_library.py

I added tooltip text saying that ignoring folders and files in book folders is asking for data loss.
I also added the ability to open the check dialog when no errors were detected to make it easier to change settings.

Enhancement #1998705: Exclude folder names from “Check Library” results.

---

recipes/fokus.recipe

This PR adds a recipe for the Swedish weekly news and current affairs magazine [Fokus](https://www.fokus.se/).
As the `epub` format is not among the supported file types in GitHub PRs, I'll instead share [an example output `epub` of the recipe over Dropbox](https://www.dropbox.com/s/p1gy17uy9pv43mq/fokus.epub?dl=0).
Thanks for your great work, @kovidgoyal!

Add Fokus (fokus.se) recipe

---

src/calibre/db/cache.py
src/calibre/gui2/actions/similar_books.py

Fixed by adding a new API method db.cache,split_if_is_multiple_composite(). This method converts the value to a list if the composite is "tags-like". The intention is that plugins etc can use the method if needed.

Bug #1999571: Similar books: Grouped search problems.

---

src/calibre/gui2/search_restriction_mixin.py
src/calibre/gui2/tag_browser/model.py

1) Clear the temporary VL if the search box is empty instead of giving an error. 
2) Escape regexp special characters in tag browser first letter searches. Use super-quoting to make escaping work reliably.
Re #2: without these changes the tag browser produced invalid reqular expressions if an item began with a regexp special character.

Two minor improvements:

---

src/calibre/devices/usbms/driver.py

When macOS sends file to e-reader device, it also sends a AppleDouble format file has the same name with "._" prefix. Ignore these files so they won't be added to the device metadata file.

Ignore AppleDouble files on ebook device

---

src/calibre/gui2/preferences/toolbar.py

one forgoten character => string not loaded for translation (oups)

'The buttons on the search bar' not translated

---

src/calibre/db/backend.py
src/calibre/db/schema_upgrades.py

SQLite has historically supported using double quotes for string literals against SQL standards.
The default for supporting this has been recently changed upstream [1] (6.f)
Ref: https://sqlite.org/quirks.html#dblquote
https://www.sqlite.org/releaselog/3_41_0.html [1]
The patches I'm sending are what I've tested in FreeBSD, since the FreeBSD ports tree is following upstream practice and changing the default.

Fix improper use of double quotes.

---

src/calibre/gui2/preferences/create_custom_column.py

Sorry about the churn, but this bothered me.

Fix using an integer constant for Qt.CheckState.Checked

---

manual/url_scheme.rst
src/calibre/db/backend.py
src/calibre/db/cache.py
src/calibre/db/fields.py
src/calibre/db/lazy.py
src/calibre/db/schema_upgrades.py
src/calibre/db/tables.py
src/calibre/db/tests/add_remove.py
src/calibre/db/tests/writing.py
src/calibre/db/write.py
src/calibre/ebooks/metadata/book/render.py
src/calibre/ebooks/metadata/opf2.py
src/calibre/gui2/actions/show_book_details.py
src/calibre/gui2/book_details.py
src/calibre/gui2/dialogs/book_info.py
src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/ui.py

DB changes:
1) Add link columns to "normalized" tables. All such in-memory tables have an attribute self.link_map.
2) Add API to set and get links for fields
3) get_metadata now includes an attribute giving the link maps for the book. Book link maps are cached.
4) ProxyMetadata can return link maps
5) Added a test for the API.
URL Scheme:
1) Added a "book-details" URL that asks calibre to open a book info window on a book in some library
Book Details:
1) You can now have multiple book info windows.
2) If an item as an associated link then that link is made available using "(item link)" link text.
3) Book info windows on books in other libraries have no links
UI:
1) the Manage Category editor presents a fourth column for links.
OPF:
1) The OPF used for backing up (metadata.opf) contains …

This is a large commit.

---

manual/template_lang.rst

Proposed change to documents: 
1. Moved the plugboard section up (just below custom columns section)
2. Clarified that all template modes are available (line 127, if you want to undo the first change).

Plugboard section in template language documents

---

resources/default_tweaks.py

Added several entries (Software, Games, Entertainment, Media, and Studios) commonly used for video game developers & publishers to author_name_copywords. This is for users who store game manuals and documentation in a Calibre library.

Added entries to author_name_copywords

---

src/calibre/gui2/actions/__init__.py
src/calibre/gui2/actions/show_book_details.py
src/calibre/gui2/book_details.py
src/calibre/gui2/dialogs/book_info.py

Commit 1:
Add the ability to name the shortcut for qactions in InterfaceActionPlugin.
Commit 2:
1) Remove the ability to open book-details link windows using a query. It was never documented and ui.py didn't support it.
2) Simplify management of book details windows. There can now only be three windows, all non-modal on top of calibre, all with calibre as the parent. Each window has a "purpose". The first is the normal book details slave window, the second is a locked book details window, and the third is a book-details link window.
3) Add more menu actions to Show Book Details: open a locked window and close all book details windows. Use this menu where the menuless qaction was previously used.

Two commits:

---

src/calibre/utils/copy_files.py

Hi,
On FreeBSD we are using Python 3.9 by default and I was getting this error while building calibre:
```
Setting up command-line completion...
Installing zsh completion to: /wrkdirs/usr/ports/deskutils/calibre/work/stage/usr/local/share/zsh/site-functions/_calibre
Installing bash completion to: /wrkdirs/usr/ports/deskutils/calibre/work/stage/usr/local/share/bash-completion/completions/
File "/wrkdirs/usr/ports/deskutils/calibre/work/calibre-6.16.0/setup.py", line 119, in <module>
sys.exit(main())
File "/wrkdirs/usr/ports/deskutils/calibre/work/calibre-6.16.0/setup.py", line 104, in main
command.run_all(opts)
File "/wrkdirs/usr/ports/deskutils/calibre/work/calibre-6.16.0/setup/__init__.py", line 239, in run_all
self.run_cmd(self, opts)
File …
```

Adapt union syntax to work on python 3.9

---

resources/default_tweaks.py
src/calibre/gui2/library/models.py
src/calibre/gui2/library/views.py
src/calibre/library/field_metadata.py

1) Add a tweak to change the heading for standard columns
2) Add "id", "formats", and "path" as standard columns. They are by default hidden, like "languages"

Two semi-dependent changes:

---

src/calibre/library/comments.py

in v4, the switch to QtWebEngine introduced a bug where, in "HTML comments", paragraphs with a single \<br> produced an visual extra gap in the render, problem will have been solved by using non-breaking space \<p>&amp;nbsp;\</p>
(topic https://www.mobileread.com/forums/showthread.php?t=325991)
However, the "calibre.library.comments > markdown" still produces HTML with \<p>\<br>\</p> causing the rendering of "Markdown comments" in Book Details (and Book Info) to still have this extra gap.
This commit is to fix this and do a more consistent rendering between "HTML comments" and "Markdown comments"

fix comments markdown

---

src/calibre/gui2/markdown_syntax_highlighter.py

Improve the Markdown Highlighter for the following:
1. Use a map/dict to init the highlighter theme
2. basic bold and emphasis
3. improve HorizontalLine and HeaderLine

Improve the Markdown Highlighter

---

src/calibre/gui2/markdown_syntax_highlighter.py

fix imbricated bold/italic which does not behave the same way if you use underscore or asterix, single char italic, link overflow
and reorder highlighting

fix some markdown highlighter

---

src/calibre/gui2/actions/open.py
src/calibre/gui2/actions/view.py
src/calibre/gui2/library/models.py
src/calibre/gui2/tag_browser/model.py

1) Make model.refresh_rows() also clear the extra files cache for those books. Rationale: if someone changes the contents of data/ outside of calibre then this provides a way to get calibre to recheck.
2) Add opening the data folder to the Open action. Allow it to have a shortcut. Create the data folder if it doesn't exist.
3) Bug #2018227: User Categories: "Hide empty categories" failing for sub-categories

Now three independent commits

---

src/calibre/gui2/markdown_editor.py
src/calibre/gui2/markdown_syntax_highlighter.py

Add support of HTML entity to the Markdown Highlighter. Also, apply the local bold and italic to the entity.

HTML entity to Markdown Highlighter

---

src/calibre/gui2/metadata/single_download.py

There was an extraneous 'as' in the context menu option. I removed it.

Minor string change for save_alternate_cover

---

src/calibre/ebooks/metadata/book/render.py
src/calibre/gui2/preferences/look_feel.py

Currently, in the Book detail, the Path field can show a second link for the extra data of the book. Unfortunately, this second link is hard coded to be displayed in oneline only.
This commit allows the user to choose between oneline or multiline display, via the "Categories on separate lines" in the _Preference->Loonk & Feel->Book detail_ options.

Book detail: Path field can be display on multiline

---

src/calibre/gui2/library/delegates.py

TextDelegate, CompleteDelegate, CcTextDelegate class share the same setEditorData() function.
Create a common/shared EditableTextDelegate to effectively pass on any changes in setEditorData().

Group setEditorData() in a shared class for Texts delegates

---

recipes/prospectmaguk_free.recipe

This PR adds a new recipe for [Prospect Magazine (UK)](https://www.prospectmagazine.co.uk/issues/) that does not require a subscription.
There is an old existing [subscription-required recipe](https://github.com/kovidgoyal/calibre/blob/93f60a674d2a6b63178ca42ee1c4b064c6f60a12/recipes/prospectmaguk.recipe) for the same site that I believe is broken. I do not have a subscription to fix it, so I've left it as-is.

Add Prospect Magazine UK (Free) recipe

---

src/calibre/gui2/trash.py

Insert a line return into the Tool Tip on the trash dialog, to break a very long text.

Fix very long Tool Tip on trash dialog

---

recipes/high_country_news.recipe

Because it say `en-Us` rather than `en` or `en-us` it appears in a branch on its own.
Since this site is web -design oriented and not specific to the USA, I have chosen to change it to `en` rather than `en-us` so it appears under English rather than English (United States).
Note: This is one of many language tweaks that are needed to clean up the UI. I will try to do as many as I can - please advise whether you would like them submitted as a single PR or in individual PRs.

[Recipe] High Country News - Fix group in builtin recipe UI tree

---

recipes/wash_post.recipe

This pull request adds all official public feeds for Washington Post (https://www.washingtonpost.com/ ) and reorders them to match the order presented on that page.

Add all official Wapo Feeds

---

src/calibre/web/feeds/news.py
src/calibre/web/fetch/simple.py

I've noticed for many popular sites like NYTimes that implement bot protection, there is an opportunity to differentiate the delay based on the targeted url host. For example, for NYTimes, static assets like images are hosted on static01.nyt.com which is not as strictly protected as www.nytimes.com.
This PR allows users to programmatically determine the delay based on the url to be downloaded. 
Based on my own testing with nytimes.com and bloomberg.com, this can gain up to a 50% reduction in run time, more if the pages are image heavy.
```python
import random
from urllib.parse import urlparse
from calibre.web.feeds.news import BasicNewsRecipe
class DemoGetDelayRecipe(BasicNewsRecipe):
title = "Demo Get Delay"
__author__ = "ping"
description = "Demo `get_delay()` usage"
language = "en" …
```

Implement get_delay() for news recipes

---

Changelog.old.txt

Changelog.old.txt don't have the close brace for the last entry.
This result than the last entry is ignored if you try to parse it to retrive the JSON with setup.changelog

fix Changelog.old.txt not closed

---

src/calibre/gui2/actions/edit_metadata.py

Fix: When the DataFilesManager is lauched by the default action `EditMetadataAction.manage_data_files()`, the field "Folder" is not updated in the book details panel (update also any composite column that use a extra data files function).

Refresh the GUI when DataFilesManager is lauched

---

src/calibre/gui2/dialogs/template_dialog.py

Fix a inconsistency that return a turple for custom fields with multiple value for the "default book" in the template editor, instead of a list.
mi.get('author') + mi.get('#custom_multiple') => TypeError - can only concatenate list (not "tuple") to list.

fix inconsistency field type for default book

---

src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/tag_list_editor.py

1) Add a context menu to the notes widget. Remove the keyboard handler as it isn't needed. 
2) Allow passing an item string value instead of an item_id to __init__ 
3) Make the notes widget self contained, making the signal advisory instead of mandatory 
4) Add a delete note button to the widget.

Some refactoring and improvements:

---

recipes/wash_post.recipe

The Washington NFL team was renamed in 2022. Updating news recipe to reflect the new name, "Commanders"

update Washington football team name in Washington Post recipe

---

setup/build.py

PyQt-builder uses qmake under the hood, which has a frustrating habit of not respecting standard stuff like $CC / $CFLAGS unless the project authors go out of their way to manually specify to use the same value as gotten from the environment.
Implement this for the same environment variables that we currently respect when building internal extensions *without* PyQt-builder.

build: pass on the user's compiler and compiler-flags settings to qmake

---

src/calibre/gui2/store/search/results_view.py

Current versions of PyQt seem to generate code incompatible with our class definition:
```
File "/home/eschwartz/git/calibre/src/calibre/gui2/actions/store.py", line 49, in do_search
return self.search()
^^^^^^^^^^^^^
File "/home/eschwartz/git/calibre/src/calibre/gui2/actions/store.py", line 55, in search
sd = SearchDialog(self.gui, self.gui, query)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/eschwartz/git/calibre/src/calibre/gui2/store/search/search.py", line 38, in __init__
self.setupUi(self)
File "/home/eschwartz/git/calibre/src/calibre/gui2/store/search/search_ui.py", line 84, in setupUi
self.results_view = ResultsView(parent=self.verticalLayoutWidget)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ResultsView.__init__() got an …
```

fix crash in Get Books when regenerating UIC files

---

src/calibre/spell/__init__.py
src/calibre/spell/import_from.py

Three commit for bug fix that prevent the download of some dictionaries.
1. **fix incorrectly relative paths**<br>Some dictionaries apparently put the dic and aff file in a sub-directory dictionaries and incorrectly make paths relative to that directory instead of the root, for example: [ca](https://github.com/LibreOffice/dictionaries/tree/master/ca)
2. **fix alternative string-list representation in xcu**<br>A alternative representation for string-list use \<it\> tag for each item of the list, for example: [tr-TR](https://github.com/LibreOffice/dictionaries/tree/master/tr_TR)
3. **fix script variante includes in the lang_code**<br>Some dictionaries add a script variante in their lang_code, for example: [mn-MN](https://github.com/LibreOffice/dictionaries/tree/master/mn_MN)

Fix online dictionaries

---

recipes/wsj.recipe
recipes/wsj_free.recipe

archive.is version no longer works. It is also paywalled now. [https://archive.is/latest/https://www.wsj.com/world/middle-east/u-n-world-leaders-push-to-get-gaza-aid-flowing-after-biden-pledge-3b59283b](https://archive.is/latest/https://www.wsj.com/world/middle-east/u-n-world-leaders-push-to-get-gaza-aid-flowing-after-biden-pledge-3b59283b)
that was too fast. :( 
Even browser access to paywalled content with googlebot headers is removed.

revert WSJ

---

setup/__init__.py

Choose oldest file when 2 or more files for `targets` parameter.
This requires `newer()` works propely to select newer files.

Really choose oldest file modification time in target files

---

src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/tag_list_editor.py

Add a NoteTableWidgetItem to provibe a specific context menu for the Note and some function around, in the Authors and 'Tags' manager table dialog.
This is some kind of reimplementation of NotesItemWidget previously deleted, but in a more lighter way since we're using a simple TableWidgetItem as parent class. The actual behavior to use a text checkmark is conserved.
The other commits are:
1) use 'named column index' wherever needed
2) moving the context menu relative to NameTableWidgetItem to be more consitant

Add NoteTableWidgetItem

---

src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/edit_authors_dialog.ui
src/calibre/gui2/dialogs/tag_list_editor.py
src/calibre/gui2/dialogs/tag_list_editor.ui

1. Improve performance by caching all icons.
2. Use different icons instead of a check mark for notes. Sorting uses the icon.
3. In manage tags, make the edit button on the left work on all editable cells. Correct the tooltip.
4. In manage tags, put the button press shortcut descriptions into the tooltips.
5. In manage authors, add an "Edit cell" button that works with all editable cells.

Several changes:

---

src/calibre/gui2/__init__.py
src/calibre/gui2/dialogs/edit_authors_dialog.py
src/calibre/gui2/dialogs/tag_list_editor.py

1. Add an icon cache to QIcon.
2. Use the cache for every icon getter in these dialogs.
As I said in the comments, I didn't add the cache to QIcon.ic (__call__) because I don't know the rules. If 'names' are not context sensitive then the cache can be added to __call__ and cached_icon() can go away .

Icon cache changes:

---

manual/develop.rst
manual/function_mode.rst
manual/template_ref_generate.py
src/calibre/customize/builtins.py
src/calibre/linux.py

The [development environment setup guide](https://manual.calibre-ebook.com/develop.html) mentions that Python 3.8 was the minimum version required. There were some leftover print statements in the documentation that should be updated to print functions to reflect Python 3+.

Change print statements to print functions

---

recipes/apple_daily.recipe
recipes/houston_chronicle.recipe
recipes/scmp.recipe
recipes/singtaohk.recipe
recipes/sueddeutsche_mobil.recipe
recipes/sueddeutschezeitung.recipe
setup/browser_data.py
setup/plugins_mirror.py
src/calibre/utils/date.py

[Python 3.12 has deprecated](https://docs.python.org/3.12/whatsnew/3.12.html#deprecated) `datetime.utcnow` and `datetime.utcfromtimestamp`.
In this change I updated most instances of it. I tested only on 3.10.1, but all of the changes I made should be compatible with 3.8+. (I couldn't figure out how to run Calibre with different versions of Python that I have installed. Is there a way to give `calibre-debug` a python executable to use?)
I tested the changes to `calibre/utils/date.py` thoroughly to have identical output before/after. The other recipes and scripts, I tested by separately running the changed snippets of code.
I left the uses of `datetime.utcfromtimestamp` in the following files, as I'm not sure where the output is being used, and whether it's ok for the datetimes to be …

Remove deprecated utcnow, utcfromtimestamp

---

setup.py

According to the development guide, and the usage of the `:=` operator, the minimum required Python version is 3.8.
`setup.py` still checked for 3.7, so I updated it.

Fix minimum required Python version in setup.py

---

recipes/substack.recipe

Substack feed includes a large content section, but it's usually not the entire article.

Don't use embedded content for Substack

---

pyproject.toml
setup/check.py

In the update [commit](https://github.com/kovidgoyal/calibre/commit/6bc1831a84be2045406bde7ba47b60e957e9c4cb) of the minimum Python version required by `setup.py`, we forgot to also align `ruff`, `black` and `pyupgrade`.

Fix minimum required Python version for ruff, black and pyupgrade

---

recipes/new_yorker.recipe

Today's download of the New Yorker fails to import via Send to Kindle and opening the epub in calibre I see this error:
```Parsing failed: redefinition of the xmlns prefix is forbidden```
which is fixed by adding `svg` to `remove_tags` as was suggested here a few years ago:
[Parsing failed: redefinition of the xmlns prefix is forbidden
](https://www.mobileread.com/forums/showpost.php?p=4178438&postcount=8)
After applying this fix, Send to Kindle was successful.

Update New Yorker: Remove svg tags

---

src/calibre/gui2/__init__.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/tag_browser/ui.py
src/calibre/gui2/tag_browser/view.py

1) Add the capability to show the icons next to the text, unaligned. Set via an option in look&feel. This change required recording the icon position on a per-item basis instead of a per-category basis.
2) Add the possibility of keyboard shortcuts to "show counts" and "show average rating" so they are the same as the show icons ones.

Two changes related to the icons in tag browser:

---

src/calibre/gui2/ui.py

This differs from the patch I sent. I moved the "show()" to happen before the plugin initialization_complete() methods are called, just in case they use something like isVisible(). The view_manager plugin now works correctly, which it didn't in 7.2.
Tested with small and large libraries.

Fix the "flash" when starting on windows (at least).

---

src/calibre/gui2/central.py
src/calibre/gui2/preferences/look_feel.py

1) In the central widget, use instance variables instead of class variables. I don't think this matters now, but it might if central can ever be reinstantiated. 
2) Slight wording change on the new option's help text.

Two small changes:

---

recipes/wsj.recipe

Currently the WSJ recipe runs into an error on every article download:
```Failed to download article: Goldman Scores a Win With Sharply Higher Earnings from https://www.wsj.com/articles/goldman-sachs-reports-sharply-higher-earnings-helped-by-asset-and-wealth-management-58b28520
File "calibre/utils/threadpool.py", line 99, in run
File "calibre/web/feeds/news.py", line 1205, in fetch_obfuscated_article
File "<string>", line 96, in get_obfuscated_article
TypeError: can only concatenate str (not "NoneType") to str
```
This causes the script to fail and generate an empty epub:
The WSJ recently implemented a captcha when visiting articles without JS:
Because of this the recipe always gets a 401 error when checking for redirects. A 401 error causes …

WSJ Redirect Workaround

---

recipes/github.recipe

Creates a news recipe for the Github Blog at https://github.blog/, with feeds for all categories as listed on: https://github.blog/category/.

feat: creates a recipe for the Github Blog

---

setup/browser_data.py
setup/resources.py

The `cafile` parameter of `urlopen` has been deprecated since python 3.6, and is [removed in the upcoming 3.13](https://docs.python.org/3.13/whatsnew/3.13.html#urllib).
It's used in the `setup.py recent_uas` command. I replaced it with an SSL context, and cleaned up the json dumping code.
Note: I don't really use this feature - I just searched for deprecated functions.

Replace deprecated urlopen cafile parameter

---

.gitattributes

This PR adds an attribute to `*.recipe` to override the unknown syntax language for syntax highlighting through GitHub.
Sometimes syntax highlighting is picked up correctly on GitHub which uses linguist[^1], when the `*.recipe` includes a shebang for python it will syntax highlight. Other times it does not.
This change adds an attribute to `*.recipe` to mark it as a python language to linguist, following the documentation on overrides[^2].
- Example with highlighting (where highlighting already worked python syntax picked up via shebang): [recipes/ambito_financiero.recipe]
1. [Example without highlighting (where highlighting didn't work): recipes/ad.recipe][recipes/ad.recipe]
2. [Same example on my fork with this PR, syntax highlighting enabled][recipes/ad.recipe linguist-language …

Update .gitattributes - mark *.recipe as linguist-language=python

---

src/calibre/customize/builtins.py
src/calibre/gui2/actions/all_actions.py
src/calibre/gui2/actions/sort.py

Use case:
- Action discovery. Eventually this action could be added to the default toolbar built by the welcome wizard.
- Ease of access to infrequently used actions.
- Shows shortcuts in most cases.

Add an action to show a menu all available GUI and plugin actions.

---

src/calibre/gui2/actions/all_actions.py

User plugin can self implement a menu without using the attibute `action_add_menu`. In this case, the menu is not detected by "All Actions" and don't show them when the plugin entry is selected.
A sizeable number of actuals user plugins do that.

Show menu if the plugin self implement a menu without `action_add_menu`

---

src/calibre/gui2/actions/__init__.py
src/calibre/gui2/actions/convert.py
src/calibre/gui2/actions/delete.py
src/calibre/gui2/actions/edit_metadata.py
src/calibre/gui2/actions/embed.py
src/calibre/gui2/actions/mark_books.py
src/calibre/gui2/actions/polish.py
src/calibre/gui2/actions/toc_edit.py
src/calibre/gui2/actions/tweak_epub.py
src/calibre/gui2/actions/unpack_book.py

All actual implementation of `accepts_drops` for built-in InterfaceAction are a "from_library" drag-and-drop. Create a subclass that implement the relatives methods.

Create subclass InterfaceActionWithLibraryDrop (DRY)

---

src/calibre/gui2/actions/preferences.py

Dealing with ampersand escapes is really a bother!

Don't escape the ampersand in the shortcut name.

---

src/calibre/db/fts/text.py

Following the spec of the \<ruby\> tag, it's better to ignore only the sub-tags \<rt\>, \<rp\> and \<rtc\>, because the root text inside the \<ruby\> tag is what we want indexing.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby

Full text search: imporve <ruby> parsing when indexing books

---

src/calibre/ebooks/oeb/polish/container.py

In this case data and regex are bytes, so repl argument should be bytes as well. Before this fix, we would sometimes get this error:
```
calibre, version 7.3.0 (linux, embedded-python: False)
Conversion error: Failed: Convert book 1 of 1 (xxxxxxxxxx)
--- snip ---
2024-03-24 23:43:49 [INFO] Upgrading to EPUB 3...
File "/usr/bin/calibre-parallel", line 21, in <module>
sys.exit(main())
^^^^^^
File "/usr/lib64/calibre/calibre/utils/ipc/worker.py", line 214, in main
result = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/calibre/calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
gui_convert(input, output, recommendations, notification=notification,
File "/usr/lib64/calibre/calibre/gui2/convert/gui_conversion.py", line 25, …
```

Fix EPUB conversion: Use bytes replacement pattern for bytes-based re.sub

---

src/pyj/read_book/prefs/selection.pyj
src/pyj/read_book/selection_bar.pyj
src/pyj/session.pyj

I would like to add an option to selection-bar to copy highlight information using a template. This way user could easily define a template and paste their highlights into a markdown for example with readily available links to the source. 
The behavior is as follow:

Add custom templates for cite action

---

src/calibre/ebooks/chardet.py
src/calibre/gui2/progress_indicator/__init__.py
src/calibre/utils/icu.py

Specifically, these fallbacks exist for people running from source with binaries so outdated they are older than 6.2.

drop fallbacks for people running from source with outdated binaries

---

src/calibre/gui2/search_box.py

Reason: it is sometimes easier to reason about searches as "I want whatever this doesn't match". In addition, most calibre search tools are "positive", returning matches. This context menu action lets you easily reverse a search, returning everything that doesn't match.
NB: "Reverse" could be "Invert". I don't know which is the better word.

Add menu action "Reverse current search" to the search bar context menu.

---

manual/faq.rst

Goto -> Go to, better link to the manual Content server page

Fix typos in FAQ page

---

src/calibre/srv/pre_activated.py

In my debian testing setup, I found that the systemd socket activation of calibre-server doesn't work (calibre 7.11, python 3.11.9).
When troubleshooting, I narrowed down to pre_activated.py.
https://github.com/kovidgoyal/calibre/blob/22ce34442c38e7182653a32978a124aef89b760c/src/calibre/srv/pre_activated.py#L37-L41
There is a hidden error:
```text
AttributeError: module 'ctypes' has no attribute 'util'
```
There are already places in [gui_launch.py](https://github.com/kovidgoyal/calibre/blob/22ce34442c38e7182653a32978a124aef89b760c/src/calibre/gui_launch.py#L78) and [scanner.py](https://github.com/kovidgoyal/calibre/blob/22ce34442c38e7182653a32978a124aef89b760c/src/calibre/utils/fonts/scanner.py#L39) using `from ctypes.util import find_library`, so I think this fix is fairly safe to …

fix ctypes AttributeError in pre_activated.py

---

bypy/sources.json
bypy/windows.conf
bypy/windows/wix.py

Was trying to build a Windows binary and had some difficulties. I figured out how to get it to build, but I think the instructions could be updated to make it easier for others. Done in conjunction with https://github.com/kovidgoyal/bypy/pull/12
Bump ZLIB to 1.3.1
- Version 1.3 is no longer available at the link in sources.json
Support WIX Version 5
- Virtual Symbol "WixUISupportPerUser" needs to be overridden in WIX V5 https://wixtoolset.org/docs/fivefour/
Improve Windows VM Setup Instructions
- Add Specific VS Packages Required for Building Deps
- Add instruction to include cl.exe, nmake.exe and vswhere.exe in path
- Add html5lib as a Python Package for Qt-WebEngine Build
Add --dont-notarize to Window Build Steps
- Without disabling notarize, the script still attempts to sign the build

Improve Windows Build Instructions and Fix Some Compatibility Issues

---

src/calibre/devices/usbms/driver.py
src/calibre/gui2/device.py

- multiple author match support
- debug print
- NO_AUTHOR_MATCH tag for Author mismatch
- '&' > 'and' support in book title
Before:
After:
Note: Author `C` - with `NO_AUTHOR_MATCH` when Author changed in calibre after book was pushed to the device
Also tried to report this as a bug but failed :| https://bugs.launchpad.net/calibre/+bug/2070045
Windows 11
Kobo Clara BW

improvements for device.py:

---

src/calibre/devices/kobo/bookmark.py
src/calibre/devices/kobo/books.py
src/calibre/devices/kobo/driver.py
src/calibre/devices/kobo/kobotouch_config.py
src/calibre/devices/paladin/driver.py
src/calibre/devices/prs505/driver.py
src/calibre/devices/prs505/sony_cache.py
src/calibre/devices/prst1/driver.py
src/calibre/devices/usbms/books.py
src/calibre/devices/usbms/driver.py
src/calibre/ebooks/metadata/sources/update.py
src/calibre/gui2/device.py
src/calibre/gui2/device_drivers/tabbed_device_config.py
src/calibre/prints.py

debug_print could be useful in many more places than just for the devices, so move debug_print into the more generic prints module

move debug_print into prints module

---

recipes/instapaper.recipe

- Add new IDs and classes to be stripped, remove out-of-date elements
- Add Instapaper masthead logo
- Embed Gutenweb stylesheet for improved article styling

Tweaks to modernise Instapaper news recipe

---

recipes/bloomberg.recipe
recipes/mediapart.recipe

* Updates Mediapart and Bloomberg recipes to handle Google News cookie consent.
* Fixes Mediapart login by updating the username field from `name` to `email`.
* Addresses a display issue in Mediapart by excluding the class `screen-reader-only`.

Fix Mediapart and Bloomberg recipes

---

src/calibre/devices/kobo/driver.py

This should add support for tolino shine (5th Gen.), shine color and vision color, but has only been tested with the shine 5.
Please note that the new tolino firmware 5.x uses 0 and 1 instead of "false" and "true" for boolean values. For now, I adapted the queries only if db version is >=188 _and_ device is tolino.
There's only one cover image extension used, and no folder tree. I tweaked the code to match.

Support for new (2024) tolino devices

---

src/calibre/gui2/lrf_renderer/bookview.py

LRF viewer will not start from command line.
See also: https://github.com/kovidgoyal/calibre/pull/2198
```python
File ".../lrfviewer", line 21, in <module>
sys.exit(main())
^^^^^^
File ".../calibre/gui2/lrf_renderer/main.py", line 312, in main
main = file_renderer(stream, opts, logger=logger)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".../calibre/gui2/lrf_renderer/main.py", line 263, in file_renderer
m = Main(logger, opts, parent=parent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".../calibre/gui2/lrf_renderer/main.py", line 72, in __init__
self.setupUi(self)
File ".../calibre/gui2/lrf_renderer/main_ui.py", line 35, in setupUi
self.graphics_view = BookView(parent=self.viewer_page)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BookView.__init__() got an …
```

LRF viewer will not start from command line

---

recipes/high_country_news.recipe
recipes/theoldie.recipe
src/calibre/customize/conversion.py
src/calibre/gui2/markdown_syntax_highlighter.py
src/calibre/gui2/preferences/create_custom_column.py
src/calibre/linux.py
src/calibre/utils/threadpool.py
src/calibre/web/feeds/news.py

Foiund via `codespell -q 3 -S "./Changelog.*,./resources/dictionaries" -L alo,ans,bu,fo,lokale,lokales,nd,pard,ro,tha,te,ths,ue,vai `

Fix various typos in codebase

---

bypy/macos/__main__.py

ULMO, available in 10.15+, uses LZMA compression, which is both stronger and faster than the deprecated bzip2 (UDBZ).

bypy/macos: use ULMO

---

bypy/macos/__main__.py

The launchers were getting compiled with no optimization at all. If one runs `objdump --disassemble calibre-launcher.dylib --no-show-raw-insn`, the result is a lot of loads and stores from the stack. Probably not critical at all for performance, but ugly and silly nevertheless.
```as
calibre-launcher.dylib:
(__TEXT,__text) section
_run:
2f30:       pushq   %rbp
2f31:       movq    %rsp, %rbp
2f34:       subq    $48, %rsp
2f38:       movb    %cl, %al
2f3a:       movq    16(%rbp), %rcx
2f3e:       movq    %rdi, -8(%rbp)
2f42:       movq    %rsi, -16(%rbp)
2f46:       movq    %rdx, -24(%rbp)
2f4a:       andb    $1, %al
2f4c:       movb    %al, -25(%rbp)
2f4f:       movl    %r8d, -32(%rbp)
2f53:       movq    %r9, -40(%rbp)
2f57:       movl    -32(%rbp), %eax
2f5a:       movl    %eax, …
```

fix(bypy/macos/__main__): Use -Os

---

src/calibre/srv/tests/loop.py

In python 3.13, this flag was added to the default created ctx. This seems reasonable for production validation, but the unittest code generates a certificate that fails this. Inside test code, it seems fine to relax the constraints again. Our goal is to test the server itself, anyway, not the ssl module.
See also: https://github.com/python/cpython/issues/107361

tests: fix SSL test on python 3.13 by being more lenient about VERIFY_X509_STRICT

---

recipes/jot_down.recipe

This PR addresses an issue in the jot_down.recipe file where the recipe was incorrectly extracting only the comments section instead of the main content. 
The following changes have been made to fix this issue:
1. Updated the keep_only_tags list to ensure that only the main content is extracted from the Jot Down website. The tags now include:
- div with class entry-content
- Removed div with id comments
**Changes:**
Recipe Fix:
Updated the keep_only_tags list in the jot_down.recipe file to correctly extract the main content.
**Testing:**
Verified that the updated tag matching logic correctly extracts the main content from the Jot Down website.

Update jot_down.recipe to Correctly Extract Main Content Instead of Comments

---

src/calibre/devices/kobo/driver.py

New tolino Shine 5 firmware 5.2.190625 uses db version 190. No significant changes noticed.

Bump supported dbversion in kobo/tolino driver

---

src/calibre/gui2/tts/types.py

We already gracefully handle the lack of speechd having the `speech-dispatcher` command utility available, and respond by disabling that backend. Go one step further, and disable it if the module is missing too.
It's not even the default engine. It seems fair for piper users to not require having this installed. The build tests will assert its presence either way so it's not like it will go unnoticed.

tts: gracefully handle the lack of a speechd module

---

src/calibre/test_build.py
src/calibre/utils/run_tests.py

TTS support can be gated on e.g. Gentoo's USE=speech, so we don't want to run the basic selfcheck of speech support if this is disabled. We do want to run the general Qt checks, though (and also do a selfcheck of speech support if the USE=speech is enabled!) -- so add a sneaky environment variable that we can use to conditionally skip running those parts.

tests: add variable to suppress TTS tests

---

src/calibre/devices/kobo/driver.py

New Tolino Shine 5 firmware 5.3.195056 still uses db version 190.

Bump supported fw version in kobo/tolino driver

---

src/calibre/db/tables.py

I was able to reproduce the problem by renaming a series with a link to an existing series then running Manage Series. I can't guarantee that this fixes all cases, but it does fix this one.

Fix the link_map containing invalid item_ids.

---

src/calibre/ebooks/conversion/plugins/pdb_output.py
src/calibre/ebooks/pdb/__init__.py
src/calibre/linux.py

Set ordering is unstable (uses the hash for ordering), so the output file would be different every time. Sort the sets into lists before writing. In various places there were unnecessary "conversions", e.g. sorted() always returns a list, so 'list(sorted(…))' is not useful.
In one place output is fixed to say: "Choices are: doc, ereader, ztxt" instead of "['doc', 'ereader', 'ztxt']".
For module constants, just create the object directly. The code is easier to read/edit when the list is constructed directly with items that are ordered in the same way that is shown in various outputs (instead of being sorted dynamically).
There is some more syntax confusion in src/calibre/linux.py. For example, '"%s" % (x)' is the same as '"%s" % x', because just putting something in parentheses does not …

Use stable ordering when writing shell completions

---

src/pyj/read_book/flow_mode.pyj
src/pyj/read_book/prefs/scrolling.pyj
src/pyj/read_book/settings.pyj
src/pyj/read_book/view.pyj
src/pyj/session.pyj

This change makes scrolling with the mouse wheel in Flow mode stop at a boundary/section, preventing abrupt section changes. This has been requested multiple times:
https://bugs.launchpad.net/calibre/+bug/1861630
https://bugs.launchpad.net/calibre/+bug/1853634
https://bugs.launchpad.net/calibre/+bug/1800248
**Implementation:**
A new preference 'scroll_mouse_boundary_delay' is added to specify the delay before crossing a boundary. It defaults to zero, which disables this feature. A value of 0.5 seconds works well.
When scrolling through a boundary, the page change request is ignored/cancelled at first, and only allowed if the user scrolls again after a delay. The net effect is that moving the mouse wheel multiple steps in one go will now stop at the boundary instead of unexpectedly moving …

Viewer: add a delay/pause when scrolling through a boundary in Flow mode

---

src/calibre/ebooks/pdf/reflow.py

Ensure average_character_width is never zero.
Check header/footer page has text when finding top/bottom.

Divide-by-zero fix and header check fix

---

recipes/substack.recipe

Space is causing an invalid URL.

Remove space on substack replacement

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_dialog.ui
src/calibre/utils/ffml_processor.py
src/calibre/utils/formatter_functions.py

Contains:
- The FFML processor in the new file utils.ffml_processor.py.
- converted documentation in formatter_functions.py.
- changes to template_processor.py to use FFML. Includes a new "show documentation" dialog.
What remains:
- Deal with translations somehow. Proposal in email.
- Changes to the manual to use FFML output when generating function documentation.
- Changes to template_lang.rst.

Formatter Function Markup Language first pass. 

---

src/calibre/utils/ffml_processor.py
src/calibre/utils/formatter_functions.py

This commit assumes your answer to my last email (about :ref:) is "yes". If it isn't then reject the commit.

Add :ref: links. Also reorder code to be closer to alphabetical order.

---

src/calibre/gui2/dialogs/ff_doc_editor.py
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/preferences/template_functions.py
src/calibre/gui2/preferences/template_functions.ui
src/calibre/utils/ffml_processor.py
src/calibre/utils/formatter_functions.py

It is an action so it can be opened easily, should a document writer want to use it. It is also available in the Stored templates / User functions dialog.
It is possible that no one other than me will use it. :)

The documentation editing tool with changes to support it.

---

src/calibre/gui2/dialogs/ff_doc_editor.py
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/dialogs/template_dialog.ui
src/calibre/gui2/dialogs/template_general_info.py
src/calibre/gui2/ui.py
src/calibre/utils/ffml_processor.py

- Add an action to ui.py to define a possible shortcut for opening the template documentation editor.
- Better exception handling in the template doc editor
- Add a dialog giving general information about formatter functions. Use FFML to test it.
- Add a button to template_dialog.py to open the general information dialog.
- Add escaping characters to FFML. Characters are escaped with backslash. Useful if one wants to enter something that looks like FFML but is supposed to be text. Example: escaping the opening bracket in \[CODE] turns it into a string instead of a tag.

Changes and bug fixes:

---

manual/template_lang.rst
src/calibre/utils/formatter_functions.py

1. Alphabetize the function list in Single Function Mode
2. Add some text explaining why the documentation have 'value' as the first parameter but the calls don't.
3. Change the first parameter of some functions to 'value' and add them to the list of SFM functions.

Changes to/involving template_lang.rst

---

src/calibre/utils/formatter_functions.py

Three various small fix
1. Add `&` operator and `$` prefix to their doc function
2. Remove space in some functions arguments
3. Fix various unquoted arguments

Various small fix

---

src/calibre/ebooks/pdf/reflow.py

Improve the tests for automatic header/footer detection.
Some fixes to page merge.
Merging paragraphs across a page boundary could fail if the merged page had all text merged and removed.

Additional header/footer checks

---

src/calibre/gui2/jobs.py

This prevents the job details dialog not being opened as otherwise the currentIndex returns -1, preventing the dialog opening.

Set focus on jobs_view table when "Show jobs detail" is clicked

---

src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/formatter_functions.py

The template documentation dialog:
* One string wasn't translated.
* The "Show in English" box wasn't being respected for the "No documentation provided" message.
* Documentation for stored templates wasn't formatted correctly
formatter_functions:
* remove a debug comment

Minor improvements:

---

recipes/the_saturday_paper.recipe

This removes a lot of extra stuff showing up at end of each articles in the current saturday paper recipe.

No extra junk at each of sat paper articles

---

src/calibre/ebooks/pdf/reflow.py

This adjusts bug 2089436, though it is not a complete fix.
The file is so short that the stats for line/paragraph breaks do not work fully.
The file produced has 2 paragraphs rather than 1 merged, but the text is in the right order.
Approximately:
Patterned chiffon," she sang it off. "You must love to craft how to galvanise the
right smell.”
Other longer test files still seem to produce the correct merging.

Bug 2089436. Error in reflowing lines from PDFs

---

src/calibre/gui2/dialogs/template_dialog.py

When calibre encounter a malformed doc for template function, it raise a error and show nothing (no doc, but no function type or code preview either).
If is annoying for a single fontion, when we try to show the full doc for all function, the exception stop the build and make render a empty page.
This commit try to solve this issue by making the build of the html doc more safer by:
1. Try with the original doc
2. Try with english doc
3. If all fail, return the raw doc
If a error occurs during the parsing of the doc, a message will will be add to the to inform the user of the error.

Make template function doc more safer

---

src/calibre/gui2/dialogs/ff_doc_editor.py
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/utils/ffml_processor.py

Added "safe" parsing of FFML that instead of throwing an exception on parse error:
* attempts to change to the English documentation. If this works (no error) then return this along with an error message.
* If the English doesn't work (parse error) or if there isn't any English documentation then produce an error message along with the offending text.
If safe parsing isn't enabled then an exception is thrown when a parse error is encountered.

Bug #2089926: Error with french translation template function doc

---

recipes/lwn.recipe

The field names on the LWN login pages have changed and the recipe needs to be updated to use the new field names.

Fix lwn.net login

---

src/calibre/gui2/dialogs/enum_values_edit.py

1) Rename values in books automatically instead of asking. This avoids leaving invalid values in book metadata. 
2) Delete values from books when deleted from the permissible values list. This avoids requiring bouncing between this dialog and the manage dialog. 
3) Indicate renames with a "Was" column.

Three improvements to the enum values editor

---

src/calibre/utils/run_tests.py

Append the test oeb.polish.tests.structure to the CLI.
The oeb.polish.tests.structure is already implemented, but never callable.

append oeb.polish.tests.structure to CLI test

---

pyproject.toml
src/calibre/db/cli/cmd_catalog.py
src/calibre/db/cli/cmd_set_metadata.py
src/calibre/gui2/add.py
src/calibre/gui2/dialogs/custom_recipes.py
src/calibre/gui2/tweak_book/diff/view.py
src/calibre/gui2/tweak_book/polish.py
src/calibre/library/catalogs/epub_mobi.py
src/calibre/utils/formatter_functions.py

Add 'INT' rule to errors checking to catch wrong resolved translation strings.

Fix wrong resolved translation strings & add 'INT' to Ruff settings

---

setup/check.py

Add a handy option to make pep8 commit.
Automatically fix some of the smallest errors, then perform a pep8 commit. Can be executed only if their is no pending change into the working tree.

add option --pep8 to 'setup.py check'

---

recipes/lwn_weekly.recipe

Borrows a trick from foreignaffairs.recipe to set the publication date in the title as opposed to the conversion date. Bulk conversion (unfortunately) is a frequent thing when catching up after a holiday or crontab breakage. It is really annoying figuring out the LWN weekly edition reading order if they all have the same title based on the conversion date.
The correct way to implement this would have been to override `publication_date()`, but this is not really set-up to be able to derive the publication date from the content. The workaround in foreignaffairs.recipe overrides `timefmt` with the publication date string to get around this. I opted for the same approach.

use the LWN weekly publication date

---

src/calibre/gui2/__init__.py
src/calibre/gui2/actions/__init__.py
src/calibre/gui2/actions/all_actions.py
src/calibre/gui2/init.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui

1. Add the option to show the "GUI actions" button in the status bar. The code to add the Preferences button is commented out.
2. Add a shortcut to All GUI Actions: Ctrl+Alt+Shift+G
3. Fix some existing problems in the All GUI Actions implementation.
4. Add the infrastructure for status line buttons (all in init.py)
5. Make using the shortcut for All GUI Actions place the menu over the button in the status bar, if it exists and is the only button/menu item. (actions.__init__.py)

All GUI options stuff:

---

src/calibre/gui2/tag_browser/model.py
src/calibre/srv/metadata.py

If your use a PTM as template, fail to load the icon "VALUE_ICON_TEMPLATE_ERROR Error in function get_database on line  199: AttributeError - 'NoneType' object has no attribute 'get". The error don't appear inside the template dialog because it simulates a book with a dict.
Recreate traceback:
```
File "calibre/gui2/tag_browser/model.py", line 145, in ensure_icon
File "calibre/utils/formatter.py", line 2007, in safe_format
File "calibre/utils/formatter.py", line 1888, in evaluate
File "calibre/utils/formatter.py", line 1757, in _eval_python_template
File "calibre/utils/formatter.py", line 1761, in _run_python_template
File "calibre/utils/formatter_functions.py", line 199, in get_database
AttributeError: 'NoneType' object has no attribute 'get'
```

fix: tag browser icon not loading when using a PTM

---

src/calibre/ebooks/djvu/bzzdecoder.c

Gcc 15 defaults to gnu23, which makes bool a native type, so it cannot be redefined like this.

Fix build with -std=gnu23

---

src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/view.py

Improve the reset to default icons for category and values in tag browser.
Fix bug when 'Restore {} category default icon' action reset all icons except template.
Fix bug when 'Use the category icon for the default value icon' actions reset also the category icon to default (instead of just the template).

Improve reset icon tag browser

---

src/calibre/gui2/__init__.py
src/calibre/gui2/dialogs/book_info.py
src/calibre/gui2/preferences/__init__.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/preferences/look_feel_displayed_fields.py
src/calibre/gui2/preferences/look_feel_tabs/__init__.py
src/calibre/gui2/preferences/look_feel_tabs/cover_view.py
src/calibre/gui2/preferences/look_feel_tabs/cover_view.ui
src/calibre/gui2/preferences/look_feel_tabs/tb_hierarchy.py
src/calibre/gui2/preferences/look_feel_tabs/tb_hierarchy.ui
src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.py
src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.ui
src/calibre/gui2/preferences/main.py
src/calibre/gui2/tag_browser/model.py

1) add a new tab to Pref / L&F / TB to show the rules viewer. This includes new options to show/hide all category and value icons. They work in the GUI. I don't think they need to be used in the content server because the screen layout there is so different.
2) change the architecture of preferences to support subclasses as tabs.
Doing the first change, which we discussed earlier, provoked me doing the second. Editing look_feel.ui and look_feel.py are very difficult because they are so big. Keyboard shortcuts are all mixed together, as are variables. It is hard to tell what does what. I decided to provide a mechanism to separate tabs into separate .ui and class files. Most of the changes in this PR are to support that.
Testing: as well as doing the new icon browser tab as a separate …

Two changes:

---

manual/gui.rst
src/calibre/gui2/dialogs/template_dialog.py
src/calibre/gui2/tag_browser/model.py
src/calibre/gui2/tag_browser/view.py
src/calibre/srv/metadata.py
src/calibre/utils/formatter.py
src/calibre/utils/formatter_functions.py

1) Make average rating (avg_rating) and count variables available in templates
2) Pass the database to safe_format so it can be used in non-GUI contexts.
The second was needed to make item value templates able to use the DB api or the database formatter functions.
Note: I added the db as a parameter to metadata.py / fillout_tree, passed in from render_categories that already had the db. It seems that this db is a reference to `Cache()`, not `Legacy()`, even though the library broker seems to get the legacy version. I couldn't find where it became `.new_api` so I used the weak reference in cache to get the legacy version. There might be a better way to do this via the library broker.

Improvements to value icons:

---

src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.py

Implement a lazy operations feature for "Look & feel".
This was create to fix a user case when many Icons value are defined, the opening/loading of "Look & feel" dialog can take several time to show (test: 15000 Icons value result of ~10 second of lag).
Fix this by populate the table only when the subtab "Value icon rules viewer" is selected, rather than during the `genesis()` phase of "Look & feel" widget.
Implemented in a generic way than can be used for sections and subtabs.

Implement lazy operations for "Look & feel"

---

src/calibre/gui2/preferences/__init__.py
src/calibre/gui2/preferences/look_feel.py
src/calibre/gui2/preferences/look_feel.ui
src/calibre/gui2/preferences/look_feel_tabs/__init__.py
src/calibre/gui2/preferences/look_feel_tabs/cover_view.py
src/calibre/gui2/preferences/look_feel_tabs/tb_display.py
src/calibre/gui2/preferences/look_feel_tabs/tb_display.ui
src/calibre/gui2/preferences/look_feel_tabs/tb_hierarchy.py
src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.py
src/calibre/gui2/preferences/look_feel_tabs/tb_partitioning.py
src/calibre/gui2/preferences/look_feel_tabs/tb_partitioning.ui
src/calibre/gui2/preferences/look_feel_tabs/tb_quickview.py
src/calibre/gui2/preferences/look_feel_tabs/tb_quickview.ui
src/calibre/gui2/preferences/main.py

- Add infrastructure for automatic handling of lazy operations (now lazy_initialize). There is a new class LazyConfigWidgetBase that supports the lazy operations. It is a drop-in replacement for ConfigWidgetBase
- Convert tab widgets: tb display, tb_partitioning, quickview
Over time I will convert other look & feel tabs, if for no other reason than to speed up opening that set of preferences.

Preferences / Look & feel changes

---

src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.py
src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.ui
src/calibre/gui2/tag_browser/model.py

* Make partitioning icons respect the "Show value icons" option instead of the "show category icons" one
* Add editing of icons, templates, and for_children to the tag browser icon rule viewer.

Two tag browser icon commits

---

src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.py

Fix a exception in icon rulers for custom columns. If their don't exist in the current library, fail to initialize the contents.

fix exception in icon rulers for custom columns

---

src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.py
src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.ui

Add a option to show only rules for category available in the current library.
Also add a note in the ui about that the icon value rules are defined per-user, not per-library.

Option to show only rules for category in current library

---

src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.py

Here the fix to display all the parent values of hierarchical categories.
Also include fix for a exception when trying to edit a rule recently created.
@cbhaley

Fix display all the parent values of hierarchical categories

---

src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.py
src/calibre/gui2/preferences/look_feel_tabs/tb_icon_rules.ui
src/calibre/gui2/tag_browser/model.py

* Add ability to change the value in a rule if that value doesn't exist in the library.
* Clean up tooltips.
* Clean up when buttons are enabled & disabled.
* When an item is renamed in the tag browser, rename the item in a rule.

Several things:

---

src/calibre/devices/mtp/driver.py
src/calibre/devices/mtp/filesystem_cache.py

The new 2024 Kindle models use MTP for file access and no longer allow the use of "Download and Transfer via USB" to obtain books in AZW3 format from Amazon's website. This makes it difficult to import Kindle books into calibre, especially since Amazon has blocked most other methods for obtaining Kindle books.
These changes allow better display of metadata in Device view when an MTP Kindle is connected and allow the import of KFX format books and notebooks from the device. KFX is not the best format for use within calibre, but it is better than nothing.
Best results are obtained if both the KFX Input and DeDRM plugins are installed since on newer Kindles the file containing metadata for books in KFX format is often encumbered with DRM.
This is a replacement for the previous pull request …

Allow import of KFX files from MTP Kindle devices rev 2

---

src/calibre/gui2/ui.py

run_wizard() sets this before shutdown() so I don't see any risk.

Make restart_after _quit available to library_closed plugins.

---

src/calibre/utils/ffmpeg.c

It was added in ffmpeg 7.1 at avcodec API (61, 14) but we were checking for and using it at API 61, which matched in ffmpeg 7.0 and failed to compile.
Fixes: 3e1a9ec3e704c98b19fd870728d0e3fe1b60126b

ffmpeg plugin: correct the version check for avcodec_get_supported_config

---

src/calibre/gui2/preferences/look_feel_tabs/__init__.py
src/calibre/gui2/preferences/look_feel_tabs/cover_grid.py
src/calibre/gui2/preferences/look_feel_tabs/cover_grid.ui

Move also the "Grid rule editor" to its own widget, so that every rule editors use the same logic.

Move "Grid rule editor" to its own widget

---

src/calibre/db/constants.py
src/calibre/ebooks/metadata/book/render.py
src/calibre/gui2/preferences/look_feel_tabs/__init__.py
src/calibre/srv/code.py

Question: should the constant be in calibre.constants instead of calibre.db.constants?

Add option in book details to suppress author search links.

---

.github/workflows/ci.yml
.github/workflows/translations.yml

This PR removes Git credentials/SSH keys after checkout as a security precaution by setting `persist-credentials` to `false`. They are not used after the initial checkout, and this stops them from accidentally leaking through a script; see [`actions/checkout` documentation](https://github.com/actions/checkout?tab=readme-ov-file#checkout-v4).

Remove git credentials after checkout

---

pyproject.toml
recipes/nytimes.recipe
recipes/nytimes_sub.recipe
src/calibre/devices/kobo/driver.py
src/calibre/ebooks/oeb/polish/kepubify.py
src/calibre/gui2/dialogs/connect_to_folder.py
src/calibre/srv/code.py

ruff 0.9.10 fix the issue with the unused unpacked variable which forces to completly hide F841 "unused variable", by spliting this behavior into a other rule. `pyproject.toml` updated and code cleaned accordingly.

Clean unused variable

---

resources/templates/kobo.js
src/calibre/gui2/store/__init__.py
src/pyj/popups.pyj
src/pyj/read_book/cfi.pyj
src/pyj/read_book/viewport.pyj

Found via `codespell -q 3 -S "*.svg,./Changelog.*,./recipes,./resources/dictionaries,./src/unicode_names/names.h" -L alo,ans,bootup,clen,fo,lokales,nam,nd,oclock,pard,re-use,re-used,ro,secnd,som,succeded,te,ue,vailable`

Fix follow-up typos

---

codespell.exclude
pyproject.toml
src/calibre/ebooks/mobi/tbs_periodicals.rst
src/calibre/ebooks/rtf2xml/override_table.py
src/calibre/web/feeds/news.py

codespell include a feature to exclude typo error with a high precision and pretty easy to maintain (put the all line to exclude, I added the file path only for reference) and now it return 0 error/false-positive.
Now that calibre code is compliant with codespell, we could included it into the check workflow, but I'll let you decide if and how you want to add codespell to this.
Also slightly improved default options.

More codespell work

---

src/calibre/gui2/__init__.py

On FreeBSD this prevents a failure when building with Qt 6.9
Adding the env only if `isbsd`, but this could be needed for other OSes too.
The patch was suggested by jhale@FreeBSD.org in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=286051

Disable GPU when running headless

---

recipes/fokus.recipe

Ensure an article contains no duplicated paragraphs by correctly setting the `keep_only_tags` attribute. `keep_only_tags` no longer contains both a parent tag and its child, which was the cause of the duplicated paragraphs.

Ensure deduplication by simplifying `keep_only_tags`

---

src/calibre/gui2/viewer/highlights.py

Several books I read have same chapter names that occurs multiple times across the book. For those books, ebook-viewer will show the highlights as grouped by the chapter names on the highlight widget. This behavior can result in the highlights being shown in inconsistent order as they appear in the book - sometimes a highlight at a position later in the book can appear before another highlight earlier in the book.
This PR changes the behavior of the grouping key to take the spine index into consideration when grouping the highlights. The difference can be seen in the following screenshots.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Improve highlight grouping with recurring chapter names

---

recipes/fokus.recipe

- Identifies the current week's edition of Fokus, including its cover image and all its articles.
- Also improves formatting, for example by making the article ingress italic.

Refactor "Fokus.se" recipe to accommodate new website structure

---

recipes/financial_times.recipe

Use 'https://www.tomorrowspapers.co.uk' as a new source for the front cover of the FT

Add missing front cover to FT recipe

---

recipes/nytimes.recipe
recipes/nytimes_sub.recipe

Fix JSON parsing error for NYT Recipe by replacing `undefined` with `null` and stripping JS functions

Fix JSON parsing error for NYT Recipe

---

src/calibre/utils/formatter_functions.py

1) use [ ] instead of { } so it can be used in single function mode.
2) use zero for empty values.

format_duration() changes:

---

src/calibre/utils/formatter_functions.py

Improve the GPM `format_duration` function by:
- remove the `largest_unit` parameter (it guessed from the template itself)
- improving pattern match
- allowing empty suffixes

Improve GPM `format_duration()`

---

src/calibre/gui2/custom_column_widgets.py

I'm using a few custom columns to track data such as:  
- when I've read a book
- my own comments/notes/etc
Especially the multiline custom-fields are a bit  annoying, because they have a fixed height and I can't resize them to be bigger.  
The "Comments" field under Basic-metadata behaves a bit better, and actually fills the available width of the window.
I've changed all `is_comments` rows to have `row_stretch`.  
This way, multiline (= comment) rows grow with the window, and if there are multiple they all grow equally.

Allow custom-metadata comment rows to grow with the window.

---

src/calibre/devices/mtp/defaults.py
src/calibre/devices/mtp/driver.py
src/calibre/gui2/device_drivers/mtp_config.py

MTP kindles support APNX files within the book sidecar.
This PR uses the existing APNX logic to generate a local file and then upload it to the proper path within the device when sending books to an MTP kindle.

Page number information (APNX) for MTP Kindles

---

src/calibre/gui2/dialogs/tag_list_editor.ui

Double space in Manage Tags dialog tooltip

tag_list_editor.ui - Fix double space

---

src/calibre/ebooks/oeb/stylizer.py

Hi,
I have been converting a few Japanese ebooks from EPUB to AZW3, and I found that the property `-epub-text-emphasis` wasn't translated to `-webkit` for the Kindle.
This style is often used in Japanese to emphasis text:
This PR fixes this issue.

Keep emphasis style on ebook conversion

---

src/calibre/gui2/tts/types.py

Third party redistributors might choose to skip distributing this for a couple reasons:
- missing dependencies
- lack of interest in TTS as a feature
Lay some groundwork for handling this with fewer error message popups. In particular note that speechd / flite depend on PyQt6 being built with it, so support *may* appear dynamically after calibre is installed, and available_engines queries Qt to see what is available. Piper is built as part of calibre though, and if it has been patched out or skipped via `setup.py build --only=xxx` we can at least avoid claiming it's there.
Entrypoints into TTS eventually tend to consolidate into creating the backend. This gives us one consistent place to raise errors for missing backends... which however doesn't handle forcing a backend name. A forced …

TTS: gracefully handle missing piper support

---

src/calibre/ebooks/pdf/html_writer.py

Currently, we are not iterating over the last page wen applying odd-even offsets. This ensures that we apply the offset to the last page and correctly index the margin map.

Fix off by one error with pdf_odd_even_offset

---

recipes/ciperchile.recipe

This diff fixes the recipe for the new source Ciper.
The recipe was outdated and the links it was trying to use to get the information where no longer valid.
I tested this locally by loading the recipe and then running the job to retrieve the articles.

Fix Ciper recipe

---

src/calibre/utils/copy_files.py

If any book formats in a Calibre library are Windows symbolic links, renaming the book (or making any change that prompts Calibre into moving the symlink) will delete the _link target_. This can cause data loss.
Calibre opens symbolic links without `FILE_FLAG_OPEN_REPARSE_POINT`. Therefore the `delete_on_close` functionality will delete the target file and not the symbolic link. On POSIX, `unlink` deletes the link itself (as seen in `UnixFileCopier` class).
**To reproduce:**
1. Create new library.
2. Add new book from file `test.epub`.
3. Go into library folder and move `test.epub` to `X:\test.epub`.
4. Link `X:\test.epub` back to `test.epub`.
5. Calibre will accept this symbolic link.
6. Rename `test` ⇒ `test rename`.
7. File `X:\test.epub` is deleted while symlink still exists but is …

Fix deletion of symlink targets on Windows

---

setup/iso_codes.py

fix a exception in setup.py iso_code because try to read a byte object when you use --path-to-isocodes

fix exception because try to read a byte object

---

src/calibre/gui2/dialogs/check_library.py
src/calibre/library/check_library.py

Add the feature to check a malformed paths and/or malformed formats into a library if running on a case sensitive system, and to fix them.

Check library malformed paths and malformed formats

---

src/calibre/db/cache.py
src/calibre/db/copy_to_library.py
src/calibre/db/legacy.py
src/calibre/db/tests/filesystem.py
src/calibre/db/tests/writing.py
src/calibre/gui2/dialogs/book_info.py

Add a get_book_path() method to Cache. DRY, "migrate" the LibraryDatabase.path methode that as no equivalent in the new api and also allow a more clear behavior if you want use a unsafe book_id.

add get_book_path() to Cache (DRY)

---

src/calibre/db/tests/fts_api.py

Running the tests on a slow QEMU aarch64 Linux virtual machine results in the following failure:
```
> test_winutil (calibre.test_build.BuildTest.test_winutil) ... skipped 'winutil is windows only' [0.0 s]
> test_wpd (calibre.test_build.BuildTest.test_wpd) ... skipped 'WPD is windows only' [0.0 s]
> test_zeroconf (calibre.test_build.BuildTest.test_zeroconf) ... ok [3.6 s]
> test_forked_map (calibre.utils.forked_map.find_tests.<locals>.TestForkedMap.test_forked_map) ... ok [1.2 s]
>
> ======================================================================
> FAIL: test_fts_search (calibre.db.tests.fts_api.FTSAPITest.test_fts_search)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File …
```

fix: add better timeout to fts wait
